### ISSUE TITLE
Documentation subtask About GeoBlacklight

### ISSUE THREAD

**Issue by lenathelibrarian** [geoblacklight/geoblacklight#1012]
Subtask of #1011 

Task is to enhance "About GeoBlacklight" section of geoblacklight.org and other locations as applicable

**Comment by rmseifried** [comment]
[Google doc](https://docs.google.com/document/d/1FNbpYOaV_88-6y1FxYEoc2Yr7S1LLzxntOo_xU8vTyw/edit?usp=sharing) for revised content

**Comment by lenathelibrarian** [comment]
Hi friends! @aranganath24 and I just incorporated these edits and there's a pull request from a fork on my account (https://github.com/geoblacklight/geoblacklight.github.io/pull/138) that Karen has said she or Jack will review today woohooooo
