### ISSUE TITLE
Aardvark metadata JSON schema

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#1023]
### Descriptive summary

We need to produce a [JSON schema](https://json-schema.org/) file for the GBL v4.0 Aardvark metadata schema.

### Expected behavior

GBL contains a [JSON schema file](https://github.com/geoblacklight/geoblacklight/blob/main/schema/geoblacklight-schema.json) for help in validating JSON objects. This schema file is also used by GeoCombine to [validate documents](https://github.com/OpenGeoMetadata/GeoCombine/blob/master/lib/geo_combine/geoblacklight.rb#L14).

We'll need to include a new JSON schema file that defines the properties of the Aardvark schema.

**Comment by karenmajewicz** [comment]
This will be helpful for validation and conversion tools. Complete before next sprint.
