### ISSUE TITLE
Apache Solr - schema.xml and solrconfig.xml support for Aardvark metadata schema

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#1024]
### Descriptive summary

Determine Solr schema.xml and solrconfig.xml design for GBL v4.0 Aardvark metadata schema support.

We've been debating static vs. dynamic field definitions, and perhaps a hybrid approach might be useful for the 4.0 release. The hybrid approach would be to drop the suffix (_s, _sm, _i, _im, etc.) patterns for the core metadata elements and define them "statically" in schema.xml, which simultaneously leaving the dynamic field matchers for keeping local custom metadata element generation simple.

- [ ] Determine static, dynamic, or hybrid approach to schema
- [ ] Consider ManagedIndexSchemaFactory to support Schema API updates ([Additional details](https://lucene.apache.org/solr/guide/8_8/schema-factory-definition-in-solrconfig.html#switching-from-schema-xml-to-managed-schema))

**Comment by karenmajewicz** [comment]
What would be the implications of not specifying _s vs _sm in the metadata when it is tied to the behavior of the application? For example, what would happen if someone uploaded a doc with multiple values in dct_format? Would the record be accepted in Solr, but then err out in the application?

**Comment by ewlarson** [comment]
I would have to test... but I think BL/GBL won't mind very much about single vs. multiple values coming _from_ Solr. Mainly you'd run into Solr indexing issues before you saw any GBL application errors.

Are you thinking that people see those suffixes as helpful rules to follow when generating metadata?

**Comment by karenmajewicz** [comment]
OK- just catching up and clarifying for myself what this means. So, any given field in Solr is still configured to be single or multiple; it would just be our metadata field names don't need to specify it? Therefore, if we make a schema upgrade for the Publisher field from single to multiple via the config file, it wouldn't mess up anyone's existing metadata?

**Comment by karenmajewicz** [comment]
Discuss at next code sprint

**Comment by eliotjordan** [comment]
We've decided to keep using dynamic fields.
