### ISSUE TITLE
Add rake task to copy JTS into solr-wrapper

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#1037]
If we want to fully support JTS in the future, we will need a rake task to copy the jts library into the solr_wrapper solr instance.

Code snippet:

```
desc 'Copy necessary solr dependencies to local solr instance'
  task :copy_solr_dependencies do
    copy_task = lambda do
      FileUtils.cp(
        File.join(File.expand_path(File.dirname(__FILE__)), 'solr', 'conf', 'jts-core-1.15.0.jar'),
        File.join(SolrWrapper.instance.instance_dir, 'server', 'solr-webapp', 'webapp', 'WEB-INF', 'lib')
      )
    end

    begin
      copy_task.call
    rescue Errno::ENOENT # solr instance_dir does not exist
      SolrWrapper.wrap do
        copy_task.call
      end
    end
  end
```

**Comment by ewlarson** [comment]
@cbeer helped us this GBL Summer Community Sprint. He pointed out how they copy CJK tooling into Solr for Searchworks:
https://github.com/sul-dlss/SearchWorks/blob/master/lib/tasks/searchworks.rake#L20-L36

Looks very similar to your snippet above. Maybe you've seen this already?

**Comment by karenmajewicz** [comment]
JTS = Java Topology Suite. 

Is this still relevant now that Geo3D is native to the versions of Solr needed for version 4?

**Comment by ewlarson** [comment]
Closing. Geo3D handle this requirement.
