### ISSUE TITLE
Homepage Map - Incorrect data-map-bbox attribute in v3.3.0 

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#1040]
### Descriptive summary

In GBL v3.3.0, we added support for complex geometries (#1032) and changed the map data attribute from map-bbox to map-geom, to indicate support for much more than simple bboxes. However, we forgot the homepage map also used the data-map-bbox attribute to potentially scope the initial map view from world to something pertinent to the local collection.

### Expected behavior

Homepage map would use the data-map-geom attribute. 

Example v3.3.0 use to scope the homepage map via the new data-map-geom attribute, via a GeoJSON object:
https://github.com/umass-gis/geoblacklight/blob/main/app/views/catalog/_home_text.html.erb#L40

### Actual behavior

Out of the box, GBL's `catalog/_home_text.html.erb` file still references the now unused data-map-bbox attribute.

### Related work

* Support for complex geometries (#1032)

**Comment by karenmajewicz** [comment]
Eliot will work on before the next sprint
