### ISSUE TITLE
Test that sorting and faceting accept multiple values for Index year (solr_year)

### ISSUE THREAD

**Issue by karenmajewicz** [geoblacklight/geoblacklight#1045]
The new Aardvark schema has replaced solr_year_i with gbl_indexYear_im. Verify that these UI components will be compatible:

- [x] Blacklight Range limiter
- [x] Sorting by year
- [ ] Year facet

We should have a spec that exercises this functionality with multiple years.

**Comment by karenmajewicz** [comment]
Create a second ticket to look at Sort

**Comment by ewlarson** [comment]
Confirming that our `gbl_indexYear_im` field does work with the blacklight_range_limit:

![blacklight_range_limit](https://user-images.githubusercontent.com/69827/154118313-76e6902f-3169-447f-ab66-8b76bc54e307.gif)

**Comment by karenmajewicz** [comment]
I updated this issue with more clarifications. The implications of making index_year multivalued potentially include the range limit plugin, the Year facet, and the sorting options.
