### ISSUE TITLE
DEPRECATION WARNING: Calling #render_facet_limit on a non-componentized facet

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#1066]
### Descriptive summary

From: CatalogController#index / Appears 4 times on page load

DEPRECATION WARNING: Calling #render_facet_limit on a non-componentized facet is deprecated and will be removed in Blacklight 8. (called from render_facet_tags at /Users/ewlarson/Rails/geoblacklight/app/helpers/geoblacklight_helper.rb:95)

**Comment by cbeer** [comment]
I think this can be grouped with #1065, right?

**Comment by ewlarson** [comment]
Closing via https://github.com/geoblacklight/geoblacklight/pull/1080
