### ISSUE TITLE
DEPRECATION WARNING: Constraints helpers or partials were overridden; not using components.

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#1069]
### Descriptive summary

CatalogController#index as HTML (search results) / Appears 1 time on page load

DEPRECATION WARNING: Constraints helpers or partials were overridden; not using components. (called from public_send at /Users/ewlarson/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/actionview-6.1.4.1/lib/action_view/base.rb:247)
  Rendered /Users/ewlarson/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/blacklight-7.19.2/app/views/catalog/_start_over.html.erb (Duration: 6.4ms | Allocations: 677)

**Comment by cbeer** [comment]
geoblacklight overrides these methods to display the map bounding box a little nicer?  This might benefit from some upstream work to clarify a good seam for this (maybe something with the `Blacklight::FacetItemPresenter`?).

**Comment by ewlarson** [comment]
Closing. Deprecation no longer appears in v4.0+
