### ISSUE TITLE
DEPRECATION WARNING: document_heading

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#1070]
### Descriptive summary

CatalogController#show as HTML / Appears 1 time on page load

DEPRECATION WARNING: document_heading is deprecated and will be removed from a future release (Use Blacklight::DocumentPresenter#heading instead). (called from ___sers_ewlarson__ails_geoblacklight_app_views_catalog__show_header_default_html_erb__2996271937336792000_80320 at /Users/ewlarson/Rails/geoblacklight/app/views/catalog/_show_header_default.html.erb:2)

**Comment by cbeer** [comment]
I think this is an easy one like #1067 ; as long as it isn't overridden elsewhere, `document_presenter(document).heading` is a drop-in replacement
