### ISSUE TITLE
DEPRECATION WARNING: document_action_path

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#1071]
### Descriptive summary

CatalogController#show as HTML / Appears 5 times on page load

DEPRECATION WARNING: document_action_path is deprecated and will be removed from a future release. (called from ___sers_ewlarson__ails_geoblacklight_app_views_catalog__document_action_html_erb___546524923593399683_80560 at /Users/ewlarson/Rails/geoblacklight/app/views/catalog/_document_action.html.erb:1)

**Comment by cbeer** [comment]
`catalog/_document_action.html.erb` is overridden to inject an icon? I'd consider a CSS-only approach to adding those, a custom action component that can do this, or contributing some icon configuration upstream.
