### ISSUE TITLE
DEPRECATION WARNING: document_action_label

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#1072]
### Descriptive summary

CatalogController#show as HTML / Appears 5 times on page load

DEPRECATION WARNING: document_action_label is deprecated and will be removed from a future release. (called from block in ___sers_ewlarson__ails_geoblacklight_app_views_catalog__document_action_html_erb___546524923593399683_80560 at /Users/ewlarson/Rails/geoblacklight/app/views/catalog/_document_action.html.erb:5)

**Comment by cbeer** [comment]
I think this can be grouped with #1071 ?
