### ISSUE TITLE
DEPRECATION WARNING: Initializing a Blacklight::Configuration::ViewConfig implicitly

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#1076]
### Descriptive summary

Spinning up the app...

DEPRECATION WARNING: Initializing a Blacklight::Configuration::ViewConfig implicitly (by calling split) is deprecated. Call it as split! or pass initialize arguments. (called from <class:Engine> at /Users/ewlarson/Rails/geoblacklight/lib/geoblacklight/engine.rb:14)

**Comment by cbeer** [comment]
I'm not sure I understand the current approach, so I don't get why the `Geoblacklight::Engine` is messing with the view configurations in the first place.

For clarity, if nothing else, I'd probably move that configuration views into the `CatalogController` (that Geoblacklight provides + generates into the app).

**Comment by ewlarson** [comment]
Closing. Deprecation no longer appears in v4.0+
