### ISSUE TITLE
SVG Icons - Remove title element

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#1098]
### Descriptive summary

GeoBlacklight v4 releases (probably v3+ too). SVG icons with a title element will have a duplicate title upon render and the rollover tooltip.

### Expected behavior

SVG icons should render with a sane title and tooltip.

### Actual behavior

SVG icons with a title element render with a duplicate title.

<img width="1033" alt="Screen Shot 2021-10-07 at 3 54 05 PM" src="https://user-images.githubusercontent.com/69827/136463287-2d44d6c2-169b-4f84-af70-7b5c3a693c70.png">

### Steps to reproduce the behavior

You need a test fixture that points at one of the long-form university names. We have some duplicate icons: minnesota.svg (no title, works well) and univerisity-of-minnesota.svg (title present, duplicates).

### Related work

Possibly an unexpected bug from the work here:
https://github.com/geoblacklight/geoblacklight/pull/1088/commits

**Comment by karenmajewicz** [comment]
May have been fixed by last PR
