### ISSUE TITLE
Hard-coded "source" field in Aardvark relationship browse links

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#1099]
### Descriptive summary

GeoBlacklight v4 releases have support for many new item/record relationships, as defined in the `settings.yml` `Settings.RELATIONSHIPS_SHOWN` hash. During our attempt to upgrade the B1G/BTAA Geoportal to GBL v4, we realized the relationship "browse" links are always hardcoded against the "source" field (`dct_source_sm`).

### Expected behavior

The "browse" link should query Solr for the related field from the relationship: `pcdm_memberOf_sm`, `dct_isPartOf_sm`, `dct_relation_sm`, `dct_source_sm`, etc.

### Actual behavior

The "browse" link always queries `dct_source_sm`. Image below is a B1G/BTAA example of the `MEMBER_OF` field rendering correctly, but linking to `dct_source_sm` instead of `pcdm_memberOf_sm`.

<img width="916" alt="Screen Shot 2021-10-08 at 2 15 41 PM" src="https://user-images.githubusercontent.com/69827/136614405-9904a8bb-4de8-4df6-b5ad-2eb972c551c1.png">

### Related work

Work is related to Aardvark relationships commits:
* https://github.com/geoblacklight/geoblacklight/commit/2acd310e6b538cd4d530e7e8058b8d7c317f3ebe
* https://github.com/geoblacklight/geoblacklight/commit/32684bea3c1ac7418cfffbc96619d679ba7b4a1c

PR forthcoming to address the issue.

**Comment by karenmajewicz** [comment]
possibly ready to be closed; review merged PR first.
