### ISSUE TITLE
Missing documentation for v.4.0 to retain map view in search results page

### ISSUE THREAD

**Issue by rmseifried** [geoblacklight/geoblacklight#1107]
### Descriptive summary

The "Map" view is still the default search result view in GBL v4, but a GBL v3 catalog_controller.rb file needs some slight view config adjustments to display the results as expected. This is the [new code that needs to be added](https://gist.github.com/ewlarson/e6eae1520fa307d56714e79e3bfca2f2#:~:text=%23%20GeoBlacklight%20Defaults,view.delete_field(%27list%27)).

Additionally, the Blacklight gem may need udpating in order to get this to work. 

Can this be documented somewhere?

**Comment by eliotjordan** [comment]
Documentation is on the 4.0 upgrade wiki page. 
https://github.com/geoblacklight/geoblacklight/wiki/GeoBlacklight-4.0-Upgrade-Guide
