### ISSUE TITLE
GBL v4 - Solr schema.xml bug - Multiple values encountered for non multiValued copy field dc_publisher_sort

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#1108]
### Descriptive summary

PR forthcoming...

Aardvark allows for multiple publisher values ([dct_publisher_sm](https://opengeometadata.github.io/docs/aardvarkSchema/publisher/)) which are currently copyfield'd into a dc_publisher_sort field in the schema.xml file. However, with Solr, you cannot [sort on multivalued fields](https://solr.apache.org/guide/7_6/common-query-parameters.html).

### Expected behavior

Documents with multiple publisher values should index into Solr correctly.

### Actual behavior

Documents sent to Solr for indexing return:

```
org.apache.solr.common.SolrException: ERROR: [doc=VAC3073-M-00654] Error adding field 'dct_publisher_sm'='[Indiana Department of Geology and Natural Resources, William B. Burford]' msg=Multiple values encountered for non multiValued copy field dc_publisher_sort: William B. Burford
```

### Steps to reproduce the behavior

1. Add an additional publisher value to a fixture doc
1. Index the doc
1. See the error...

### Related work

[B1G GEOMG Issue](https://github.com/BTAA-Geospatial-Data-Project/geomg/issues/171) which uncovered the bug.

**Comment by tpendragon** [comment]
Solr can only sort on single-valued or docValues enabled fields. Multi-valued string fields don't support docValues. To fix this we'd either have to no longer support sorting by publisher (our default CatalogController doesn't use dc_publisher_sort) or find some way to get Solr to copy only the first or last value for the sake of sorting.

If an item can have multiple publishers, it seems unlikely we'd be able to choose which one should be prioritized for sorting. If that's a use case we want to support, we'd have to add it to the Aardvark schema. In the meantime, both #1109 and #1151 simply delete the copyField designation from the schema, allowing documents with multiple publishers to index.
