### ISSUE TITLE
create a DOI for geoblacklight

### ISSUE THREAD

**Issue by thatbudakguy** [geoblacklight/geoblacklight#1112]
as noted in the [community meeting discussion topics from jan. 12th](https://docs.google.com/document/d/1s6VDJqSnFa66Qr1SjT41FX9ccvhm3guU06aR1Y9gdOw/edit#heading=h.lmzlz7ly4j90), an upcoming "geoinformatics handbook" publication will feature geoblacklight. the editor of the handbook chapter on open source geoinformatics is compiling [digital object identifiers (DOIs)](https://www.doi.org/faq.html) for relevant software cited in that chapter, and reached out to check if geoblacklight has a DOI so that it can be included. **the deadline for inclusion of the DOI is january 20th**.

**Comment by thatbudakguy** [comment]
i have used [zenodo](https://zenodo.org/) to mint DOIs for software before, and it seems to be the most popular option currently (but see also [figshare](https://figshare.com/)). there are many features well-suited to depositing software, like a [GitHub integration that automatically mints a new DOI](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content) upon publishing a release. all of the release-specific DOIs can then be [grouped under a single meta-DOI](https://blog.zenodo.org/2017/05/30/doi-versioning-launched/), so that one can cite either the software itself or a particular version. one can also ["reserve" a DOI](https://help.zenodo.org/) so that the ID can be obtained before the actual publication of the software or content.

the current situation is tricky because:
1. there is a short timeframe in which to provide the DOI, and...
2. a new official release of geoblacklight (v4) probably won't occur for some time, but...
3. in the future, it would be nice not to have to (manually) mint a new DOI for every release.

i contacted the zenodo maintainers to ask if they had any advice for this particular situation:
> The auto-deposit feature of the github integration seems great, but is it possible to combine this with the ability to reserve the DOI? Otherwise, I don't think there will be anything to release to trigger the auto-deposit functionality. Relatedly, if I reserve the DOI now, is there any way to ensure it's associated with all following DOIs that are automatically generated from releases?

here was their response:
> This unfortunately is not possible. We recommend that users disable the GitHub integration and go with a "manual" CI/CD-based approach where they make direct calls to the Zenodo REST API for creating new versions.

given that we have a pretty short timeframe, i think it might make sense to just reserve the DOI now so that we can give it to the editor, and tie this DOI to the current (v3.4) release of geoblacklight. for v4 onward, we can either explore the CI approach, or just manually mint DOIs for each new release as needed.

**Comment by karenmajewicz** [comment]
I like this plan. The current (v3.4) release will in use for awhile, and it would be fine for the DOI to point to it for the near future.

**Comment by thatbudakguy** [comment]
@karenmajewicz I went ahead and reserved the DOI `10.5281/zenodo.5851664`. i haven't published the record yet since i need to add all the contributors listed for v3.4, so maybe we could go over it together at the next community meeting and then publish it.

**Comment by karenmajewicz** [comment]
This would be good to revisit during the September sprint.  Maybe we could do this during the September 14th Community Meeting?

**Comment by thatbudakguy** [comment]
record is public! https://zenodo.org/record/5851664#.YyIdelLMK2B
