### ISSUE TITLE
Combine "Downloads" and "Export formats" content areas

### ISSUE THREAD

**Issue by hackartisan** [geoblacklight/geoblacklight#1131]
### Descriptive summary

During usability testing at Princeton, testers were given pause by the separate content areas for "Downloads" and "Export formats". From the user perspective it doesn't seem that this distinction is important, and it creates a decision point that stalls their progress.

Recommend displaying the contents of "Export Formats" in the "Downloads" box and removing the separate content area.

If implemented we would like to see this on main and backported to the 3.x branch.

### Screenshot

![Screen Shot 2022-02-08 at 10 34 32 AM](https://user-images.githubusercontent.com/845363/153021069-18e5f62e-9f0e-47de-9a86-4ab2337631bd.png)

**Comment by hackartisan** [comment]
They often are different, primarily when it comes to their projection.

We discussed labeling these as, e.g. "Original Shapefile" and "Export Shapefile" as a starting point.

**Comment by mferrarini** [comment]
@hackartisan I’ve been thinking about the Downloads & Exports button that you demo’ed at stand-up today…if we’re open to visual changes I have a suggestion to make it look more cohesive with the rest of the sidebar content areas (while still standing out): 

What if the button and dropdown menu were the same width and spanned the width of the sidebar?

We have a similar dropdown in our blacklight instance for downloads so I tweaked that a bit to give a general example of what I mean. I think it would be a nice look, especially if the “Web Services” content area is going to be a dropdown button as well, they would align nicely. Just throwing my two cents in!

![Screen Shot 2022-02-22 at 4 16 54 PM](https://user-images.githubusercontent.com/13121501/155224749-4bd02003-24fd-4098-8db3-02dc9e09c974.png)
![Screen Shot 2022-02-22 at 4 16 59 PM](https://user-images.githubusercontent.com/13121501/155224756-5e8e3807-8bb6-41b9-bf2d-ee94d586fe1c.png)
