### ISSUE TITLE
Update / upgrade javascript

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#1132]
### Descriptive summary

GeoBlacklight javascript code could use modernization. We should have a discussion about this and write up a proposal for how we might upgrade. Since the javascript modules are modified in individual implementations, this could be a disruptive change and we should take that into account.

Possible topics to discuss:

1. Use of `let/const` vs. `var`.
1. Use of [leaflet class structure](https://github.com/geoblacklight/geoblacklight/blob/main/app/assets/javascripts/geoblacklight/geoblacklight.js#L33). 
1. Should we convert to ES6? Could address the class and module problem above.
1. **Blacklight will stop requiring JQuery**
1. BL has dropped support for IE 11
1. How to bundle and ship JS (BL Community question)

### Related work
https://github.com/geoblacklight/geoblacklight/issues/774

**Comment by thatbudakguy** [comment]
thanks for opening this @eliotjordan! i think another thing to bring into this discussion is codifying what browsers the app should support (if that doesn't already exist somewhere). it looks like we are already using babel's `preset-env`, which provides a nice [browserslist integration](https://babeljs.io/docs/en/babel-preset-env#browserslist-integration). that means we could decide formally on what we want to support, create [a `.browserslistrc` or similar](https://github.com/browserslist/browserslist), and let babel do the work of including polyfills for the features we want to support.

i think there are lots of good arguments for converting to ES6, but i'm also not familiar with the landscape of individual implementations. that said, i think it's fair to expect disruptive changes as part of v4, so hopefully it wouldn't be too big of a surprise.

**Comment by eliotjordan** [comment]
At the 2/2/22 Sprint Meeting, we decided to:

- Remove jQuery dependency
- Rewrite javascript as ES6
- Improve javascript coverage with Jest
- Further study and discuss bundling options

**Comment by eliotjordan** [comment]
We've been experimenting with using [vite](https://vite-ruby.netlify.app/) and [jsbundling-rails (with esbuild)](https://github.com/rails/jsbundling-rails) to bundle javascript. Vite is seems very nice.

**Comment by ewlarson** [comment]
IIIF Image/Manifest viewing is something that should be considered during this update/upgrade process:
https://github.com/geoblacklight/geoblacklight/issues/1279

**Comment by karenmajewicz** [comment]
https://docs.google.com/spreadsheets/d/1xhzrtJ0enmnLI7GRWHYUETmo497hDTbRdB2jkgrLR4w/edit?pli=1#gid=0

**Comment by ewlarson** [comment]
2024 Winter code sprint update here.

I made a run through our GBL javascript library and (with ChatGPT's help) updated it to ES6 and dropped our jQuery dependency. That work is in our Blacklight v8 branch:
https://github.com/geoblacklight/geoblacklight/pull/1344

The initial commit of rewritten files is here:
https://github.com/geoblacklight/geoblacklight/pull/1344/commits/02def59296b4f63362dd1ebaf1c4b215d660de08

This rewrite does not migrate us away from Leaflet, which almost all our JS extends from L.<something>.

Hope this proves helpful for us all!
