### ISSUE TITLE
Flaky ArcGIS service is causing tests to fail

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#1142]
### Descriptive summary
https://data.isgs.illinois.edu/arcgis/rest/services/Geology/Glacial_Boundaries/MapServer is down causing test to fail.

**Comment by karenmajewicz** [comment]
I would be happy to remove these, as it is very unpredictable when the services get retired, even from relatively reliable portals like ISGS.

If we really want to have Esri specs in the application, perhaps I could create some on our BTAA ArcGIS Online account?
