### ISSUE TITLE
Deprecation: Remove `require "view_component/engine"

### ISSUE THREAD

**Issue by hackartisan** [geoblacklight/geoblacklight#1148]
This deprecation shows when building internal test app or when running the test suite.

DEPRECATION WARNING: This manually engine loading is deprecated and will be removed in v3.0.0. Remove `require "view_component/engine"`. (called from <top (required)> at /Users/aheadley/src/geoblacklight/lib/geoblacklight/engine.rb:2)

split off from #1133

**Comment by hackartisan** [comment]
This deprecation comes from Blacklight upstream and I expect that when view components 3.0 is released and Blacklight upgrades to it, resolving this deprecation will be part of that process.

Currently Blacklight requires Viewcomponent 2.43. https://github.com/projectblacklight/blacklight/blob/31a3990ccf9e389a0962876b09b6ff31f5e3fd77/blacklight.gemspec

This deprecation was introduced in 2.46. https://viewcomponent.org/CHANGELOG.html#2460

The require is here https://github.com/projectblacklight/blacklight/blob/31a3990ccf9e389a0962876b09b6ff31f5e3fd77/lib/blacklight/engine.rb#L3

The options for silencing this for now are:
* Require a lower version of view component explicitly in the geoblacklight gemspec
* Submit a Blacklight PR locking to view component ~> 2.46 and removing the deprecated line.

This deprecation doesn't seem disruptive enough to warrant either of these actions. We should probably let it lie until it's resolved in Blacklight as part of regular maintenance.

**Comment by ewlarson** [comment]
I agree. This isn't our battle.

Also, it looks like there is no issue on the Blacklight repo for this particular deprecation. Can you add an issue over there and reference this one to loop everything together?

**Comment by hackartisan** [comment]
Thanks. I created https://github.com/projectblacklight/blacklight/issues/2619 and will close this issue.
