### ISSUE TITLE
Update solrconfig.xml with new Aardvark field names

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#1155]
### Descriptive summary

These fields need to be updated with Aardvark field names.
https://github.com/geoblacklight/geoblacklight/blob/bda30cffcfaef8b61d2fa4bd91c5268a67f87f15/solr/conf/solrconfig.xml#L120-L148

**Comment by hackartisan** [comment]
Here's the documentation: https://opengeometadata.github.io/docs/aboutAardvark/#how-do-i-convert-my-version-10-metadata-into-aardvark

**Comment by hackartisan** [comment]
This is already noted in the [upgrade guide](https://github.com/geoblacklight/geoblacklight/wiki/GeoBlacklight-4.0-Upgrade-Guide#apache-solr)

**Comment by hackartisan** [comment]
Do a pass of the solr configurations against the documented schema changes. Bring copy field names in line with the aardvark field names for consistency. Check code for references to the fields.
