### ISSUE TITLE
Improve GitHub Actions configuration

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#1177]
### Descriptive summary

This is a ticket to request improvements to the GitHub Actions configuration file:
https://github.com/geoblacklight/geoblacklight/blob/a567fc2e5b2657c0d1a4d00b8ae47d29ed98e58c/.github/workflows/ruby.yml

Improvements:

1. Make the job titles more descriptive when using a matrix of Ruby versions. Right now, the titles say test 2.7 and test 2.6 and it isn't clear what that's in reference to.
2. Is there a way we can utilize [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) to streamline the configuration?

**Comment by karenmajewicz** [comment]
Is there prior art at Princeton that we can adopt for this?

**Comment by thatbudakguy** [comment]
this may be done? the workflow file was cleaned up so there's only one job, and we now test several more version combos that we didn't before. also, the job names accurately reflect what versions are being tested.

**Comment by eliotjordan** [comment]
This ticket is done. The tests have more descriptive names now:

```
CI / test ruby 3.2 / rails 6.1.7.6
CI / test ruby 3.2 / rails 7.1.3
CI / test ruby 3.3 / rails 6.1.7.6 
CI / test ruby 3.3 / rails 7.1.3
```
