### ISSUE TITLE
Determine minimum Solr version needed for Version 4

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#1195]
### Descriptive summary

We need to figure out which version of the Solr 8 series adds support for the s2 prefix tree. 

Running `rake geobalcklight:solr` using different versions of Solr could get at this issue. Loading documents will fail if  there isn't s2 prefix support.

**Comment by dl-maura** [comment]
8_3 is the first time I see it used in an example: https://solr.apache.org/guide/8_3/spatial-search.html

**Comment by ewlarson** [comment]
https://issues.apache.org/jira/browse/SOLR-13467 / Listed here as fixed in 8.2

**Comment by tpendragon** [comment]
Keeping notes here.

Solr 8.0.0:

```
Failed to execute solr create: INFO  - 2022-02-24 09:56:24.520; org.apache.solr.util.configuration.SSLCredentialProviderFactory; Processing SSL Credential Provider chain: env;sysprop

ERROR: Error CREATEing SolrCore 'blacklight-core': Unable to create core [blacklight-core] Caused by: solr.CaffeineCache
```

**Comment by tpendragon** [comment]
I updated https://github.com/geoblacklight/geoblacklight/wiki/Installation to say Solr 8.3+ and added a note to the solr section of https://github.com/geoblacklight/geoblacklight/wiki/GeoBlacklight-4.0-Upgrade-Guide#apache-solr.
