### ISSUE TITLE
Re-integrate translations deleted with download_generated_body

### ISSUE THREAD

**Issue by hackartisan** [geoblacklight/geoblacklight#1200]
#1194 consolidated several partials to simplify the code. After that consolidation an unused helper was deleted. However, that helper was translating values and we need to integrate that translation back into the new code structure.

Deleted helper / translation calls:
https://github.com/geoblacklight/geoblacklight/pull/1194/files#diff-6063777a82676000ea52777ea425d012302dc963e6655a58f5cb6b484e2a9baeL115

The helper was called here:
https://github.com/geoblacklight/geoblacklight/pull/1194/files#diff-4b2187ce92dee4f1dc0a103c2f94f2a2d667561f62f9535fa3bea26f4ff92c17L5
 (note this file was deleted so the line doesn't highlight until you click "load diff" on app/views/catalog/_downloads_generated.html.erb) 

And the new code that creates those links is here:
https://github.com/geoblacklight/geoblacklight/pull/1194/files#diff-81b5660e2b241be42227a9daa3ca378a6b959b7f3340ab4f5484d32967ec9b09R24

**Comment by hackartisan** [comment]
The translations provided the Label that was to the left of each export button, e.g. "KMZ". Presumably the text needs to be incorporated into the buttons themselves. I think right now the labels look right but maybe aren't going through translation.

**Comment by tpendragon** [comment]
I don't think this is a bug. Thanya changed the label to include the format via accessing the format key.

So:

https://github.com/geoblacklight/geoblacklight/blob/ed66be10f3ce9aea031abaf3ee5782c121a9ec0d/config/locales/geoblacklight.en.yml#L8

points to `download_format` as an argument, which is populated from:

https://github.com/geoblacklight/geoblacklight/blob/ed66be10f3ce9aea031abaf3ee5782c121a9ec0d/app/helpers/geoblacklight_helper.rb#L90-L92

which pulls the format out of the same place as `download_generated_body` used to.

**Comment by tpendragon** [comment]
Okay - I think the issue was that you used to be able to provide different values in the `export_` format links instead of just `formats` - so `shapefile` could always be "EPSG:4326 Shapefile" - is that still a use case @eliotjordan ?

See https://github.com/geoblacklight/geoblacklight/commit/1efec3bc2ea42a55e861267bcd330678adc6645e#diff-5fd69f4fbc735bd538c5f65873b8c75b63439e55b5d60a22ef3f7f9f586f1c03R11-R15 for where these came from
