### ISSUE TITLE
Add clipboard / copy buttons to web services and citation

### ISSUE THREAD

**Issue by hackartisan** [geoblacklight/geoblacklight#1209]
### Descriptive summary

As referenced in https://github.com/geoblacklight/geoblacklight/issues/1122#issuecomment-1039303601, the web services links are quite long and a clipboard button would be a nice feature to add. The citation also seems like a good candidate for a clipboard button.

**Comment by thatbudakguy** [comment]
see related https://github.com/geoblacklight/geoblacklight/issues/926

**Comment by karenmajewicz** [comment]
To review: this might be part of Blacklight core?

**Comment by the-codetrane** [comment]
https://github.com/geoblacklight/geoblacklight/pull/1307

**Comment by ewlarson** [comment]
Move the #1307 copy behavior into GBL JS proper for reuse within the application
