### ISSUE TITLE
Template install fails for geoblacklight ~> 4.0

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#1225]
### Descriptive summary

Running our templated install script fails:

```bash
DISABLE_SPRING=1 rails new gbl_from_template -m https://raw.githubusercontent.com/geoblacklight/geoblacklight/main/template.rb
```

### Expected behavior

You should be able to run the template and generate a fresh Rails/GBL app.

### Actual behavior

Instead, you see this error:

```bash
Could not find gem 'geoblacklight (~> 4.0)' in any of the gem sources listed in
your Gemfile.
```

### Steps to reproduce the behavior

1. Run the template script above
1. See the error

### Related work

We accidentally created this issue when [bumping the GBL requirement to v4](https://github.com/geoblacklight/geoblacklight/commit/6f7ddfb91938b507c8d4083495e324511abfcf38)

Instead of `gem 'geoblacklight', '~> 4.0'` it should read `gem 'geoblacklight', '>= 4.0.0.pre.rc1`

**Comment by ewlarson** [comment]
Despite trying my suggested change above, I cannot find a Ruby version that will complete the install (both Blacklight and GeoBlacklight templates) and run via `bundle exec rake geoblacklight:server` without erroring.

Trying with PR https://github.com/geoblacklight/geoblacklight/pull/1224 merged. Still errors with app/views/catalog/_search_form.html.erb:

For Ruby 2.7.5 to run, I had to overwrite that partial with these lines:

```ruby
<%= warn "#{__FILE__} is a deprecated partial." %>
<%- renderable_fields = blacklight_config.search_fields.values.collect { |field_def| [label_for_search_field(field_def.key), field_def.key] if should_render_field?(field_def)}.compact %>
<%= render((blacklight_config&.view_config(document_index_view_type)&.search_bar_component ||Blacklight::SearchBarComponent).new(
    url: search_action_url,
    advanced_search_url: search_action_url(action: 'advanced_search'),
    search_fields: renderable_fields,
    params: search_state.params_for_search.except(:qt),
    autocomplete_path: search_action_path(action: :suggest)))  %>

```

---

### Ruby 2.7.5
undefined local variable or method `__file__` for #<ActionView::Base:0x00000000025828>

<%= warn `"#{__file__}` is a deprecated partial." %>
<%= render((blacklight_config&.view_config(document_index_view_type)&.search_bar_component || Blacklight::SearchBarComponent).new(
      url: search_action_url,
      advanced_search_url: search_action_url(action: 'advanced_search'),
      params: search_state.params_for_search.except(:qt),
      search_fields: Deprecation.silence(Blacklight::ConfigurationHelperBehavior) { search_fields },

blacklight (7.25.1) app/views/catalog/_search_form.html.erb:1

### Ruby 3.0.2

    generate    geoblacklight:install
       rails    generate geoblacklight:install -f
/Users/ewlarson/Rails/tmp/gbl_from_template/app/controllers/catalog_controller.rb:32:in `block in <class:CatalogController>': undefined method `title_field=' for {:rows=>10}:Hash (NoMethodError)

### Ruby 3.1.2

Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 7.0.3)

    geoblacklight (>= 4.0.0.pre.rc1) was resolved to 4.0.0.pre.rc1, which depends on
      rails (< 6.2, >= 5.2.4)

**Comment by barmintor** [comment]
The `__file__` issue with ruby 2.7 is a bug in a Blacklight deprecation behavior; it's fixed in https://github.com/projectblacklight/blacklight/pull/2714 but not yet released. Your Ruby 3.0.2 issue looks like a hash is being passed in where a struct or a view configuration is expected? Not sure without a little more context.

**Comment by ewlarson** [comment]
Ran through a bunch of template builds locally. No issues installing GBL from the template file for Ruby 2.7.6, 3.0.3 or 3.1.2 using the GBLv4 PR fix here: https://github.com/geoblacklight/geoblacklight/pull/1243
