### ISSUE TITLE
Add ability to display centroids as points

### ISSUE THREAD

**Issue by rmseifried** [geoblacklight/geoblacklight#1231]
### Descriptive summary

The Aardvark schema has a new field for [centroid](https://opengeometadata.org/docs/ogm-aardvark/centroid), but the core application doesn't use the field. It would be really helpful to us if the ability to display centroid data as point locations along with (or instead of) the traditional bounding boxes was a core part of the software - perhaps this can be a feature that is toggled on/off.

### Example of an existing customization

BTAA is using a centroid to show clusters on the home page. See their documentation [here](https://github.com/geobtaa/geoportal/wiki/Homepage-Map-Clusters-and-Centroids).

![Screen Shot 2022-07-11 at 6 33 36 PM](https://user-images.githubusercontent.com/36506059/178369918-8915ead4-6f37-449b-a197-a7b4985f449d.png)

**Comment by karenmajewicz** [comment]
For now, we will document this as a customization

**Comment by ewlarson** [comment]
I'm writing some documentation for this customization.

<img width="1724" alt="Screen Shot 2022-09-15 at 11 40 55 AM" src="https://user-images.githubusercontent.com/69827/190460417-861da2f8-9580-4903-8215-4dc10d7166cf.png">

**Comment by ewlarson** [comment]
With my new documentation, you'll get to this point:

<img width="1724" alt="Screen Shot 2022-09-15 at 2 20 57 PM" src="https://user-images.githubusercontent.com/69827/190491281-b320babf-4d6a-45c2-a2e2-a2f6c1fdb5d1.png">

**Comment by ewlarson** [comment]
Homepage Map Centroid Clustering is documented here:
https://geoblacklight.org/docs/customization/homepage_map_centroid_clusters/
