### ISSUE TITLE
Consider replacing Rubocop with Standard

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#1239]
Could help to keep Rubocop update churn to a minimum.
Tag line: “No decisions to make. It just works.”

https://github.com/testdouble/standard

**Comment by ewlarson** [comment]
Placing "On Hold" for future discussion.

**Comment by dmolesUC** [comment]
On the current head (5b433bc), `standardrb` reports 2978 warnings on 39 separate cops, so unless you really, really like their opinionated style, I'm not sure this is such a good idea.

If RuboCop churn is the problem, that can be solved by setting `NewCops: disable` (currently `enable`) in `.rubocop.yml`.

**Comment by eliotjordan** [comment]
I do like the opinionated style. 🤷‍♂️  Our rubocop config and rubocop-todo is bonkers.

**Comment by eliotjordan** [comment]
Ran standardrb --fix. Not too bad really. I like it. https://github.com/geoblacklight/geoblacklight/pull/1244

**Comment by karenmajewicz** [comment]
we will try this out after version 4 comes out

**Comment by dmolesUC** [comment]
I'll be sad to see the single-quoted string literals go, but 🤷

**Comment by eliotjordan** [comment]
@dmolesUC It is possible to set exceptions, but not having to worry about customizing the linter is compelling. If single-quoted strings are a community preference, we should talk about it. People have passionate opinions about this topic. 😄

**Comment by ewlarson** [comment]
This change has been made. Using Standard now
