### ISSUE TITLE
Improve error message for Geoserver export errors

### ISSUE THREAD

**Issue by karenmajewicz** [geoblacklight/geoblacklight#1240]
### Descriptive summary

When a user selects a generated download from GeoServer, sometimes the export will fail.  I did a text export for this record:  https://geodev.btaa.org/catalog/harvard-g6800-1903-p4 The message I got was: `Sorry, the requested file could not be downloaded. Try downloading it directly from: https://geodata-proxy.lib.harvard.edu/geoserver/proxy/requestfile/wms/reflect`

Eventually, another message appeared saying the export was successful and the Download was ready.

Although, sometimes servers are slow or need maintenance, the initial error message might not be what we want. The link doesn't take users anywhere. What would a better message be?

![Screen Shot 2022-07-14 at 3 00 42 PM](https://user-images.githubusercontent.com/2367677/179075725-5ece135c-33cc-4ccc-9fef-75931ae2f732.png)

![Screen Shot 2022-07-14 at 3 01 48 PM](https://user-images.githubusercontent.com/2367677/179075775-4ac89971-ad19-49e7-8ccb-2f21aec7194e.png)

**Comment by ewlarson** [comment]
Remove the link from the alert, as it will never succeed in downloading the item.

**Comment by the-codetrane** [comment]
@ewlarson happy to pick this up. Just so I'm clear, the request is:
- remove the `link` from the error message (I'm guessing the whole `Try downloading...` sentence can go?)
- Improve the error message with more specific info...?

**Comment by the-codetrane** [comment]
https://github.com/geoblacklight/geoblacklight/pull/1309

**Comment by ewlarson** [comment]
Closed via https://github.com/geoblacklight/geoblacklight/pull/1309
