### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by jjcc** [geoblacklight/geoblacklight#1255]
### Summary
I followed the procedure to run the applicaiton. Failed to start, both "Quick start" and "Start guide for developer". Here's where it was interrupt:
`...rake aborted!
NoMethodError: undefined method `_sidecar_files' for Blacklight::FacetItemComponent:Class

          component_class._sidecar_files(extensions).each_with_object([]) do |path, memo|
                         ^^^^^^^^^^^^^^^
Did you mean?  sidecar_files
/home/jchen/workspaces/wsApption/geoblacklight/app/components/geoblacklight/icon_facet_item_component.rb:7:in `<module:Geoblacklight>'
/home/jchen/workspaces/wsApption/geoblacklight/app/components/geoblacklight/icon_facet_item_component.rb:3:in `<top (required)>'
/home/jchen/workspaces/wsApption/geoblacklight/.internal_test_app/app/controllers/catalog_controller.rb:98:in `block in <class:CatalogController>'
/home/jchen/workspaces/wsApption/geoblacklight/.internal_test_app/app/controllers/catalog_controller.rb:6:in `<class:CatalogController>'
/home/jchen/workspaces/wsApption/geoblacklight/.internal_test_app/app/controllers/catalog_controller.rb:3:in `<top (required)>'
/home/jchen/workspaces/wsApption/geoblacklight/lib/geoblacklight/engine.rb:24:in `block in <class:Engine>'
/home/jchen/workspaces/wsApption/geoblacklight/.internal_test_app/config/environment.rb:5:in `<top (required)>'
/home/jchen/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
/home/jchen/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
rake aborted!
EngineCart failed on with: pid 3195 exit 1

Tasks: TOP => engine_cart:server => engine_cart:generate
(See full trace by running task with --trace)`
### To reproduce:
I tried:  Quick start, Getting Started for Developers ( in documentation), and instruction in github which is the same as quick start. All generate the same failure.

### My environment:
1. OS: Unbuntu 22.04.1 LTS
2. Ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
3. Rails 7.0.4
4. Node v16.17.1
5. npm  8.19.2
6. Java: openjdk 11.0.16 2022-07-19, OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu122.04),OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)

I also check the blacklight gem: blacklight (7.29.0)
Maybe the version of blacklight need to be certain version?

**Comment by ewlarson** [comment]
Hi @jjcc 

Thanks for submitting this issue and my apologies for the slow reply. I cannot replicate your issue this morning. There is a new Blacklight 7.30.0 release (from 7 days ago) that installs when you run our template script now:

```
DISABLE_SPRING=1 rails new app-name -m https://raw.githubusercontent.com/geoblacklight/geoblacklight/main/template.rb
```

Perhaps that new release will resolve the issue you encountered? Please give the template script installation method another chance and let us know if you continue to see the `_sidecar_files` method error.

**Comment by ewlarson** [comment]
Closing. Please reopen if the issue persists after upgrading Blacklight.
