### ISSUE TITLE
Not all solr_documents fixtures pass aardvark schema validation

### ISSUE THREAD

**Issue by mcritchlow** [geoblacklight/geoblacklight#1262]
### Descriptive summary

We are working towards migrating [our existing geoblacklight application](https://gitlab.com/surfliner/surfliner/-/tree/trunk/shoreline) to Geoblacklight 4.0. As part of this, we are going through the data migration process and trying to update our ingest process accordingly for new content.

We were happy to see that [a jsonschema exists for aardvark](https://github.com/geoblacklight/geoblacklight/blob/main/schema/geoblacklight-schema-aardvark.json) that we could use to validate our metadata prior to ingest. As a result of writing some initial code to do this validation process I noticed a few things:

- The upstream fixture I grabbed to test while we were waiting on our own local fixtures failed validation
- The first fixture I received from our local folks managing the metadata failed validation

I realized, in the second case, this was due to our librarian basing her fixture on examples from this repo.

Out of curiosity, I wrote a short `Dockerfile` and script to use the [`json_schemer` gem](https://github.com/davishmcclurg/json_schemer) (which we used locally) to validate all the files in the `spec/fixtures/solr_documents` directory. The output of that is below. In general, the failures are regarding `gbl_indexYear_im` being a string instead of an int. Code and results below.

This raises a few questions for me:

- Is `gbl_indexYear_im` meant to be a string or an int? The difference between the schema and number of fixtures that declare a string leaves it unclear to me what's intended.
- Should these fixtures be validated in the geoblacklight test suite?
- Should geoblacklight provide a way to validate input using `json_schemer` or similar? Or should downstream applications handle that themselves?

I'm happy to help with any work that might come out of that, but my primary goal was to raise the issue here for comment. Thanks for considering.

### Expected behavior

I would have expected all the aardvark json files in the `solr_documents` directory to pass validation, unless they were intentionally setup as a fixture meant to fail validation.

### Actual behavior

Output from validation script:

```
-- solr_documents/tilejson.json failed schema validation
-- validation errors: ["property '/dct_issued_s' is not of type: string", "property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/public_iiif_princeton.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/baruch_documentation_download.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/cornell_html_metadata.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/actual-polygon1.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/actual-raster1.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/umn_state_result2.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/baruch_ancestor1.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/iiif-eastern-hemisphere.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/restricted-line.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/harvard_raster.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/index_map_point.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/index-map-stanford.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/esri-feature-layer.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/xyz.json failed schema validation
-- validation errors: ["property '/dct_issued_s' is not of type: string", "property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/actual-papermap1.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/actual-point1.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/index-map-polygon.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/esri-wms-layer.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/umn_metro_result1.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer", "property '/gbl_indexYear_im/1' is not of type: integer"]
-- 
-- solr_documents/esri-dynamic-layer-single-layer.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/uva_slug_colon.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/esri-dynamic-layer-all-layers.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/wmts-multiple.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/esri-image-map-layer.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/baruch_ancestor2.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/wmts-single-layer.json failed schema validation
-- validation errors: ["property '/dct_issued_s' is not of type: string", "property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/index-map-polygon-no-downloadurl.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/public_direct_download.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/umn_state_result1.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/esri-tiled_map_layer.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
-- solr_documents/princeton-parent.json failed schema validation
-- validation errors: ["property '/gbl_indexYear_im/0' is not of type: integer"]
-- 
```

### Steps to reproduce the behavior

The `Dockerfile` I wrote was:

```dockerfile
FROM ruby:2.7.7-alpine3.16

WORKDIR /schemas
RUN gem update bundler
RUN gem install json_schemer
COPY schema-validator.rb ./
COPY ./schema/ ./
COPY ./spec/fixtures/solr_documents solr_documents/

CMD ruby schema-validator.rb
```
The script is:

```rb
require 'json'
require 'json_schemer'

schema = Pathname.new("geoblacklight-schema-aardvark.json")
validator = JSONSchemer.schema(schema)

Dir.glob('solr_documents/*.json') do |aardvark_fixture|
  fixture_data = JSON.parse(File.read(aardvark_fixture))
  errors = validator.validate(fixture_data)
  if errors.count > 0
    puts "-- #{aardvark_fixture} failed schema validation"
    puts "-- validation errors: #{errors.map { |e| JSONSchemer::Errors.pretty(e) }}"
    puts "-- "
  end
end
```

### Related work

Link to related tickets or prior related work here.

**Comment by ewlarson** [comment]
Thanks so much for the ticket! This is great feedback. Our fixtures were updated to Aardvark early during Aardvark's drafting, but we must have failed to validate them as that new schema took its final shape. I'm very sorry for that oversight.

Please consider the OGM Aardvark documentation here as the official word for all Aardvark metadata:
https://opengeometadata.org/docs/ogm-aardvark

----

Answers to your questions...

> Is gbl_indexYear_im meant to be a string or an int? The difference between the schema and number of fixtures that declare a string leaves it unclear to me what's intended.

From https://opengeometadata.org/docs/ogm-aardvark/index-year -- it should be an array of integers.

> Should these fixtures be validated in the geoblacklight test suite?

Yes. Absolutely, these fixtures should be valid Aardvark.

> Should geoblacklight provide a way to validate input using json_schemer or similar? Or should downstream applications handle that themselves?

Almost everyone adopting GeoBlacklight has a different method for creating JSON and ingesting that data into Solr. The JSON schema included in the GBL repository has been our tool for helping people validate their metadata whatever process they use to generate that data.

I think downstream is the best approach, but if you have any thoughts about offering a "bulk validation" rake task or auditing process we'd love to hear more.

**Comment by mcritchlow** [comment]
Thanks for the quick feedback @ewlarson! That's a great tip to use the provided url as the official word for Aardvark. Will do.

I think the fixtures validating in the test suite / CI and the "bulk validation" rake task _could_ arguably be linked. In that if we're going to validate the fixtures we'll need a way to do it in repo or CI job, which could potentially double as a rake task that downstream adopters could use. I don't have strong opinions on it, and happy to defer to what you all think is best.

I guess if we're not going to provide a rake task, a CI job (similar to linting) that does something similar to the script I wrote would work. Basically I think the job could:

- install the `json_schemer` gem
- iterate/glob over the files in the `solr_documents` directory and validate them ([the gem also provides a CLI executable](https://github.com/davishmcclurg/json_schemer#cli) we could use to do it all in bash/shell)

Alternatively, I suppose we could pull the `json_schemer` gem into the `gemspec` and then write a rake task that supports validating json files in a directory. And call that from the CI schema validation job.

Those are a couple ideas that come to mind initially.

**Comment by amywork20** [comment]
@ewlarson and @mcritchlow - has this been resolved? I see that Matt has done some work on this.

**Comment by mcritchlow** [comment]
Hey @amywork20 , I _think_ this could be considered resolved but would leave it to @ewlarson to make the call.

**Comment by ewlarson** [comment]
Hi @mcritchlow and @amywork20. Yes, this is resolved, but we haven't tagged a release with the updated fixtures yet. If you need one, let me know and I'll push one out.

The fixtures in main are valid Aardvark:
https://github.com/geoblacklight/geoblacklight/tree/main/spec/fixtures/solr_documents

**Comment by amywork20** [comment]
@ewlarson - no need from my end. We have what we need for now. Thanks.

**Comment by ewlarson** [comment]
Closing via v4.1 release.
