### ISSUE TITLE
"Is Replaced By" metadata field does not display the correct relationship

### ISSUE THREAD

**Issue by karenmajewicz** [geoblacklight/geoblacklight#1264]
"Is Replaced By" metadata field does not display the correct relationship

## Explanation

I made up some terms here to be clear about how the related records are set up:
- DECLARING DOC: to indicate the record with a value/ID declared in a relationship metadata field.
- LINKED DOC: to indicate the record **without** a value/ID in a relationship metadata field.

In OGM Aardvark, we have two metadata relationship fields for replacements:
- [dct_replaces_sm](https://opengeometadata.org/docs/ogm-aardvark/replaces)
- [dct_isReplacedBy_sm](https://opengeometadata.org/docs/ogm-aardvark/is-replaced-by)

Like the other relationship fields, records with a value in these fields display with a widget that shows the related record. However, these two fields are UNLIKE the other relationship fields in that they are one-way only. This means that a relationship widget should only appear on the DECLARING DOC. In contrast, a field like "Is Part Of" triggers a widget that displays on both the DECLARING and LINKED Docs.  

---------------------
## Replaces

`dct_replaces_sm` works as expected.  In these screenshots, the DECLARING DOC has the ID of the LINKED DOC in the field "Replaces."

### DECLARING DOC (title: the newer item)
what appears: a widget showing it "Replaces" the old item
![new-item-btaa](https://user-images.githubusercontent.com/2367677/209716637-81c30477-b418-4915-af3a-6885a7d0ec88.png)

### LINKED DOC (title: old item)
what appears: nothing
![older-item-btaa](https://user-images.githubusercontent.com/2367677/209716634-864a8b28-ebee-4e26-9c5e-f5beb69124eb.png)

----------------------
## Is Replaced By
`dct_isReplacedBy_sm` does not work as expected. In these screenshots the DECLARING DOC has the ID of the LINKED DOC in the field "Is Replaced By":

###  DECLARING DOC (title: old item)
what should appear: a widget showing  it "Is Replaced By:" by "the newer item"
![older-item-btaa](https://user-images.githubusercontent.com/2367677/209716634-864a8b28-ebee-4e26-9c5e-f5beb69124eb.png)

### LINKED DOC (title: the newer item) 
what should appear:  nothing
![new-item-btaa-wrong](https://user-images.githubusercontent.com/2367677/209718582-01b83fe5-c610-422b-9db7-ef2ccee604cc.png)

----
The fixtures in our default GeoBlacklight were not set up correctly to test this. Our DECLARING DOC (All Relationships) specifies both `dct_replaces_sm` and `dct_isReplacedBy_sm`. As a result, we mistakenly set up the wrong text for Is Replaced By:

### DECLARING DOC (title: All Relationship)
what should appear: a widget for both "Replaces" and "Is Replaced By"
![older-item-gbl](https://user-images.githubusercontent.com/2367677/209716617-0ca9248b-dfe1-4018-a153-4480d1acbd11.png)

### LINKED DOC (title: Related Record)
what should appear: nothing indicating either "Replaces" or "Is Replaced By"
![related-item-gbl](https://user-images.githubusercontent.com/2367677/209716623-fbad42f2-c8b4-4bc0-95c5-726987399ccb.png)

------
## What should we do?

It is confusing to have these redundant "replace" types of fields. All of the remaining relationship fields function differently. Also, a passive voice clause like "Is Replaced By" is especially hard to grasp immediately when cataloging or troubleshooting records.

I propose that we:

1. Deprecate `dct_isReplacedBy_sm` as a field.

2. Fix the widget for `dct_replaces_sm` to show on both the DECLARING and LINKED docs.  The DECLARING doc should have a widget with the text "Replaces." The LINKED doc should have a widget with the text "Is Replaced By".

**Comment by thatbudakguy** [comment]
just noting here after discussion at today's GBL WG meeting:
- I agree with @kgjenkins that it's probably easier from a cataloging perspective to just add `replaces` to the new record, rather than (or in addition to) trying to go back and add `isReplacedBy` to the old record
- I agree with @karenmajewicz that `replaces` is generally easier to understand because it's not passive voice, and I think making things easier to understand is good

**Comment by karenmajewicz** [comment]
Here is some more info on how the other data relation widgets function:

- Our docs page on Data Relations: https://geoblacklight.org/docs/customization/data_relations_widget/ (this probably needs to be updated)
- An example of a parent type of record that does not have any relationship in its metadata: https://geo.btaa.org/catalog/05d-01 All of the items listed in the "Has Part" widget have a `dct_isPartOf_sm` specified in the metadata.
- Code:
    - [settings.yml for the BTAA Geoportal ](https://github.com/geobtaa/geoportal/blob/develop/config/settings.yml#L193-L197)
    -[ the Descendents query in GeoBlacklight](And it runs a Descendants query: https://github.com/geoblacklight/geoblacklight/blob/64523bf22a6be8816c8c84be1d48f60c0780917a/lib/geoblacklight/relation/descendants.rb#L5)

**Comment by karenmajewicz** [comment]
Updated plan based on metadata conversation:

1. Items may still contain `isReplacedBy`, but GeoBlacklight should ignore that field. It will only be used for documentation and sharing, not display in GeoBlacklight

2. Fix the widget for `dct_replaces_sm` to show on both the DECLARING and LINKED docs. The DECLARING doc should have a widget with the text "Replaces." The LINKED doc should have a widget with the text "Is Replaced By".

**Comment by ewlarson** [comment]
Making the changes described by @karenmajewicz above get us to here:

### All Relationships
* "dct_isReplacedBy_sm":["the-related-record"] / (Field present but ignored in user interface)
* "dct_replaces_sm":["the-related-record"] / "Replaces"

<img width="1303" alt="Screenshot 2023-06-12 at 9 31 24 AM" src="https://github.com/geoblacklight/geoblacklight/assets/69827/99c23f30-ce6e-4d43-be2b-83fbe8d68e47">

### The Related Record
* No "replaces/isReplacedBy" field present on document / "Is Replaced By" 

<img width="1303" alt="Screenshot 2023-06-12 at 9 31 33 AM" src="https://github.com/geoblacklight/geoblacklight/assets/69827/5d806d17-494d-43d9-9341-a0a2b52c0ab1">
