### ISSUE TITLE
Look into cross browser functionality for feature inspection

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#127]

**Comment by ewlarson** [comment]
I will use UMN's BrowserStack license to check show page functionality across browsers for 1.9 (master) and 2.0 (blacklight-7) today.

**Comment by ewlarson** [comment]
Used BrowserStack to manually look at 1.9 (master) on Windows 10: Edge 17, FF 61, Chrome 68, and Opera 54. No issues found looking at http://localhost:3000/catalog/tufts-cambridgegrid100-04 and interacting with JS features.
