### ISSUE TITLE
ViewComponent - Homepage - Map

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#1271]
Add a VC for the homepage map. The feature should provide a mechanism for setting the default map extent and zoom level. It might also allow for configurable Leaflet plugins (geosearch, layer previews, clustering engine, etc.).

<img width="1400" alt="Screenshot 2023-02-28 at 5 08 05 PM" src="https://user-images.githubusercontent.com/69827/222003336-1fd9bf0e-a79f-461e-9329-5ac8e3e5abb3.png">

**Comment by marlo-longley** [comment]
Just wanted to link a potential overlap with work in https://github.com/geoblacklight/geoblacklight/issues/1363

**Comment by dnoneill** [comment]
There is a PR for this. I want to double check that I am understanding this ticket correctly.

> The feature should provide a mechanism for setting the default map extent and zoom level.

Is this outside the bounding box? Is this something else that needs to be added? Are you talking about setZoom in leaflet?

>  It might also allow for configurable Leaflet plugins (geosearch, layer previews, clustering engine, etc.).

Isn't this what Settings.leaflet does? Is there something else I am missing?
