### ISSUE TITLE
ViewComponent - Index - Map

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#1273]
Add a VC for the search results map. We should consider making the map "sticky" to the top of the window so results far down the page will still display their rollover bbox on the map (both BTAA and HGL are doing this now).

<img width="1400" alt="Screenshot 2023-03-01 at 1 00 58 PM" src="https://user-images.githubusercontent.com/69827/222238571-7710ff85-f3c4-4164-b501-a95d54e671c7.png">

### Stanford (GBL default / Map is NOT sticky)
<img width="1723" alt="Screenshot 2023-03-01 at 1 21 03 PM" src="https://user-images.githubusercontent.com/69827/222243591-479f7ca4-1600-4ce2-a352-704ed1b28524.png">

### BTAA Geoportal
<img width="1723" alt="Screenshot 2023-03-01 at 1 03 38 PM" src="https://user-images.githubusercontent.com/69827/222239125-a5d0db88-c8c5-4bb3-bb4b-fbc014522e82.png">

### HGL 
<img width="1723" alt="Screenshot 2023-03-01 at 1 04 35 PM" src="https://user-images.githubusercontent.com/69827/222239316-34654bf6-79d6-4eb9-abd8-aedc38399cb4.png">

**Comment by dnoneill** [comment]
Currently have the PR for this merging into https://github.com/geoblacklight/geoblacklight/pull/1374 because it relies on a lot of the work there.
