### ISSUE TITLE
Item Viewer - IIIF Manifest

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#1279]
### Descriptive summary

Harvesting OGM Aardvark records from BTAA affiliate schools, and I'm seeing a lot of dct_references_s values for IIIF Manifests, however IIIF Manifest viewer support was never baked into GBL proper. It looks like we started to take steps there in 2017, but never got back around to it.

### Expected behavior

I'd expect GeoBlacklight to support viewing IIIF Manifests. Here's an OMG-available doc in the BTAA Geoportal (id: p16022coll247:290 ; rendered via Mirador, a BTAA local enhancement/customization)

<img width="1293" alt="Screenshot 2023-03-05 at 5 48 11 PM" src="https://user-images.githubusercontent.com/69827/222993058-ddff0a9f-b8be-4054-9973-e0105f352ce9.png">

### Actual behavior

Just the standard Leaflet bbox renders...

<img width="1260" alt="Screenshot 2023-03-05 at 5 47 37 PM" src="https://user-images.githubusercontent.com/69827/222993021-f5d16553-7b2f-425d-99df-9748c00b2d12.png">

### IIIF Viewer

I'm not advocating for a new IIIF Viewer -- but that could be point of future discussion. I think we should at least provide a IIIF Manifest viewing option out of the box. As we already include Leaflet-IIIF, that makes some sense to just use here for an initial implementation.

### Related work

GeoBlacklight - Added iiif_manifest to our constants file a handful of years back https://github.com/geoblacklight/geoblacklight/pull/542

Leaflet-IIIF - Has manifest support here:
https://github.com/mejackreed/Leaflet-IIIF/blob/6cb256e8d4d2dd508e98eb8a337dfa5407bee5db/examples/iiif-manifest-example.js

**Comment by karenmajewicz** [comment]
When we add the Manifest option, we should adjust the configuration so that if a record has a value for both `http://iiif.io/api/image` and `http://iiif.io/api/presentation#manifest`, we should prioritize the Manifest.  Right now, if an instance has a Manifest viewer enabled, and a record has values for both, it will default to the Image API.

Would it be a matter of just switching the order of the URIs defined in this file?

https://github.com/geoblacklight/geoblacklight/blob/ffe8e6765f0ffb6c440478c33fea509e034c87f0/lib/geoblacklight/constants.rb#L11-L12

**Comment by ewlarson** [comment]
To use a IIIF Manifest viewer in GBL you have to add it to the ItemViewer and you need to prioritize it in the viewer_preference method here:
https://github.com/geoblacklight/geoblacklight/blob/ffe8e6765f0ffb6c440478c33fea509e034c87f0/lib/geoblacklight/item_viewer.rb#L67-L70

**Comment by ewlarson** [comment]
Will attempt to add support for Clover: https://samvera-labs.github.io/clover-iiif/

**Comment by ewlarson** [comment]
An example of adding Clover to GBL via their vanilla javascript approach: https://github.com/ewlarson/geoblacklight/commit/5182f9d587b09900cb0cc4489f8a4a8348e2849e

Seems we'll want to be able to modify default behaviors, like whether to display the title, close the manifest metadata window, remove the IIIF logo, etc.

**Comment by ewlarson** [comment]
Closing via https://github.com/geoblacklight/geoblacklight/pull/1336
