### ISSUE TITLE
Inline svg images instead of icon fonts

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#132]
I really like the way the icon font looks, but I'm a little concerned that this might not scale as more organizations start to use GeoBlacklight. I think it would be worthwhile to experiment a bit and see if using a directory of SVGs instead of a pre-baked fonts might be a better solution.

**Comment by mejackreed** [comment]
I'm closing this for now. Can be reopened later if someone wants to work on it.
