### ISSUE TITLE
Assess compatibility of OpenIndexMaps 1.0 with latest version of GBL

### ISSUE THREAD

**Issue by karenmajewicz** [geoblacklight/geoblacklight#1325]
### Descriptive summary

The OpenIndexMaps spec was updated in 2021 and I want to assess if we have updated GBL to fully support it.

**Comment by karenmajewicz** [comment]
Check how they function in OpenLayers.  Many OpenIndexMaps have overlapping polygons and Leaflet doesn't handle this particularly well. How do overlapping or concurrent polygons work in OpenLayers?

**Comment by ewlarson** [comment]
@srappel

**Comment by karenmajewicz** [comment]
Closing as #1327 will cover the next steps.
