### ISSUE TITLE
Add icon for Northwestern University

### ISSUE THREAD

**Issue by karenmajewicz** [geoblacklight/geoblacklight#1349]

**Comment by ewlarson** [comment]
Maybe icons should live in a GitHub repo and be accessed outside of GeoBlacklight? A rake task could harvest the available icons for use in local GBL installs.

**Comment by ewlarson** [comment]
@karenmajewicz // Do you have an icon for this issue? We might cut a v4.4.0 release this week and I'd like to get this issue done beforehand.

**Comment by karenmajewicz** [comment]
I asked our NW team member to obtain one from here: https://www.northwestern.edu/brand/visual-identity/logos-lockups/academic-n/ (requires local authentication)
