### ISSUE TITLE
ViewComponent - Show - Default Viewer / Map

### ISSUE THREAD

**Issue by thatbudakguy** [geoblacklight/geoblacklight#1363]
This might share some logic with the homepage map VC #1271 or index map VC #1273, since they will end up rendering leaflet maps (at least some of the time).

We have some existing logic in https://github.com/geoblacklight/geoblacklight/blob/main/lib/geoblacklight/item_viewer.rb that decides what viewer should be used to render the item; this might be a good candidate for migrating into this component (and then maybe making sub-components for each of the viewer types).

<img width="841" alt="Screenshot 2024-06-13 at 2 28 30 PM" src="https://github.com/geoblacklight/geoblacklight/assets/4924494/43a3608a-2fbb-44c0-8bdf-1ee6637aeaf1">

**Comment by marlo-longley** [comment]
This may make sense to wait until #1374 and #1375 are merged and work with that code

**Comment by hudajkhan** [comment]
Will do!

**Comment by hudajkhan** [comment]
These are ow merged so I'll begin working on this.
