### ISSUE TITLE
ViewComponent - Show - Attribute Table

### ISSUE THREAD

**Issue by thatbudakguy** [geoblacklight/geoblacklight#1366]
Displays below the map and changes to look up attribute information when the map is clicked, if a WFS/WCS link is available.

![Image](https://github.com/geoblacklight/geoblacklight/assets/4924494/e137e2de-d9e5-4cd3-acb9-54a344c0712f)

In the Stanford embed viewer, we do this as a custom leaflet overlay, so it's inside the viewer instead of outside it:

![Image](https://github.com/geoblacklight/geoblacklight/assets/4924494/20e1ba48-2152-44a0-9a0c-1a3a0d4fa810)

**Comment by hudajkhan** [comment]
See https://github.com/geoblacklight/geoblacklight/blob/main/app/views/catalog/_show_default_attribute_table.html.erb and https://github.com/geoblacklight/geoblacklight/blob/main/lib/generators/geoblacklight/templates/catalog_controller.rb#L49
