### ISSUE TITLE
ViewComponent - Show - Relations

### ISSUE THREAD

**Issue by thatbudakguy** [geoblacklight/geoblacklight#1367]
Renders in the sidebar; all of the different [relations fields](https://opengeometadata.org/relations-fields/) can create boxes here.

![Image](https://github.com/geoblacklight/geoblacklight/assets/4924494/15fae27e-17d6-4c75-bf8d-4ae25c49bc1a)

**Comment by dnoneill** [comment]
closed with https://github.com/geoblacklight/geoblacklight/pull/1385
