### ISSUE TITLE
ViewComponent - Icons - Iconography Components 

### ISSUE THREAD

**Issue by thatbudakguy** [geoblacklight/geoblacklight#1372]
home, arrow-circle-down, globe, tags, book, public, restricted, ALL the institution logos, datasets, websites, maps, none (?), parent-item, child-item, esri-globe, etc...

**Comment by dnoneill** [comment]
@thatbudakguy I am not quite sure I understand this ticket. Are you suggesting we create components for every icon, i.e. https://github.com/projectblacklight/blacklight/blob/e957632975c4e190ed94a812bee74d774a5459af/app/components/blacklight/icons/icon_component.rb?

**Comment by thatbudakguy** [comment]
@ewlarson what do you think? I think we could get away with just an `IconComponent`, but it seems like blacklight 8 does have special components that only render certain icons.

**Comment by ewlarson** [comment]
Yeah, we have **SO MANY** icons in GBL. I'm fine with a some kind of general `IconComponent` for GBL here.

**Comment by thatbudakguy** [comment]
@dnoneill and I just looked into this and it seems like:

- the `geoblacklight_icon` helper just calls blacklight's own icon helper, which in turn renders an `IconComponent` already
- if you upgrade the blacklight version in geoblacklight, you'll automatically get the new version of that helper
- the `IconComponent` in blacklight does everything we want already

...so it actually seems like all the work here is already done. We're already using view components for every icon!

It seems like the work is more stuff like https://github.com/geoblacklight/geoblacklight/pull/1381, which changes places that render icons into VCs.

Gonna close this but lmk if this sounds wrong.

**Comment by thatbudakguy** [comment]
It's noted in #1411, but just for context, this was reopened because Blacklight 8 has deprecated the `LegacyIconComponent` and instead wants you to create a component for every icon.
