### ISSUE TITLE
fix login button

### ISSUE THREAD

**Issue by dnoneill** [geoblacklight/geoblacklight#1469]
### Descriptive summary

on main when you login the button still appears because render? doesn't know that the user is logged in

![Screenshot 2024-08-08 at 2 35 19 PM](https://github.com/user-attachments/assets/ab41dbe3-fe21-4f39-a90c-face5440cf46)

### Expected behavior
Login button disappears after login

### Actual behavior
login button stays on all restricted records.

**Comment by ewlarson** [comment]
^ Added a screenshot to the original issue to document the bug behavior.
