### ISSUE TITLE
Downloads - Export Shapefiles appears broken

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#1524]
### Descriptive summary

In GBL `main`, Download links are failing.

### Expected behavior

GeoBlacklight v4.4
![Screenshot 2024-08-15 at 2 25 57 PM](https://github.com/user-attachments/assets/e039f13c-ebac-40fc-83b6-094909131d7b)

### Actual behavior

GeoBlacklight v5 (main)
![Screenshot 2024-08-15 at 2 20 51 PM](https://github.com/user-attachments/assets/3c7c62d5-c9cf-43da-ac6d-dd034befac5a)

### Steps to reproduce the behavior

1. Pull `main`
1. Spin up the application
2. Visit http://localhost:3000/catalog/cugir-007950
3. Click on Download > Shapefile
4. See error...

### Related work

#1132

**Comment by peetucket** [comment]
Took a quick look and they all seem to be failing on that fixture, because for some reason the expected mimetype does not match the actual mimetype of the file.

e.g.
```
Started GET "/download/cugir-007950?type=shapefile" for 127.0.0.1 at 2024-08-16 14:29:15 -0700
Processing by DownloadController#show as */*
  Parameters: {"type"=>"shapefile", "id"=>"cugir-007950"}
Solr query: get get {:qt=>nil, :ids=>"cugir-007950"}
Solr fetch (3.3ms)
Geoblacklight::Exceptions::WrongDownloadFormat expected application/zip received application/xml
Wrong download type
Completed 500 Internal Server Error in 614ms (Views: 0.3ms | ActiveRecord: 0.0ms | Allocations: 19309)


Started GET "/download/cugir-007950?type=kmz" for 127.0.0.1 at 2024-08-16 14:29:18 -0700
Processing by DownloadController#show as */*
  Parameters: {"type"=>"kmz", "id"=>"cugir-007950"}
Solr query: get get {:qt=>nil, :ids=>"cugir-007950"}
Solr fetch (4.4ms)
Geoblacklight::Exceptions::WrongDownloadFormat expected application/vnd.google-earth.kmz received application/vnd.ogc.se_xml;charset=UTF-8
Wrong download type
Completed 500 Internal Server Error in 370ms (Views: 0.2ms | ActiveRecord: 0.0ms | Allocations: 15093)
```

this is caught here, which raises the exception: https://github.com/geoblacklight/geoblacklight/blob/main/lib/geoblacklight/download.rb#L46 which is then caught here for display: https://github.com/geoblacklight/geoblacklight/blob/main/app/controllers/download_controller.rb#L7

Not sure why this is happening though.  There were UI changes to download functionality here https://github.com/geoblacklight/geoblacklight/pull/1409/files but this was working then.

**Comment by peetucket** [comment]
The expected mime-types for each file type are defined in the relevant subclasses, e.g.: https://github.com/geoblacklight/geoblacklight/blob/main/lib/geoblacklight/download/kmz_download.rb#L19

Not sure why this mime-type is not matching what Faraday is returning when requesting the file: https://github.com/geoblacklight/geoblacklight/blob/main/lib/geoblacklight/download.rb#L43 and then https://github.com/geoblacklight/geoblacklight/blob/main/lib/geoblacklight/download.rb#L63-L69

**Comment by karenmajewicz** [comment]
This fixture appeared to be missing the Geoserver ID.  Could this fix it? https://github.com/geoblacklight/geoblacklight/pull/1546

**Comment by peetucket** [comment]
Yup, I think that may have fixed it (at least it works me in localhost now).  Good catch.
