### ISSUE TITLE
Viewer popovers are missing their title

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#1545]
### Descriptive summary

In GBL `main` the viewer protocol popovers are missing their title values. The popover definition/content is present, but no title value appears.

### Expected behavior

You should be able to see the title value in the popover.

![Screenshot 2024-08-16 at 4 46 49 PM](https://github.com/user-attachments/assets/1708b9f6-4ad6-468b-89f9-e35388d641ab)

### Actual behavior

No title is present in the popover, only the definition/content.

![Screenshot 2024-08-16 at 4 47 45 PM](https://github.com/user-attachments/assets/f72954cf-6936-4fe5-8347-79bf974dde41)

### Steps to reproduce the behavior

1. Pull `main`
2. Spin up app
3. Visit http://localhost:3000/catalog/cugir-007957
4. Hover over "Tile Map Service (TMS)"
5. See the definition, but no corresponding popover title value.

### Related work

#1544 
#1543

**Comment by jcoyne** [comment]
Perhaps we need `data-bs-title` rather than `data-title`? https://github.com/geoblacklight/geoblacklight/blob/b38827bc97f9c5e06ac807e0f67dc2e7045a0d95/app/components/geoblacklight/viewer_help_text_component.rb#L26
https://getbootstrap.com/docs/5.3/components/popovers/#live-demo
