### ISSUE TITLE
Copy buttons do not work on Web services metadata panel

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#1550]
After clicking any of the "copy" buttons on the Web Services modal of the `catalog/tufts-cambridgegrid100-04
` record, the message "undefined" is copied into the clipboard.

![Screenshot 2024-08-16 at 10 53 55 PM](https://github.com/user-attachments/assets/db9a6bfc-45c8-48b8-801c-45efc929dc3b)

**Comment by ewlarson** [comment]
Same error happened on citations, but was fixed this sprint.
