### ISSUE TITLE
add click to wake to core geoblacklight

### ISSUE THREAD

**Issue by dnoneill** [geoblacklight/geoblacklight#1554]
Currently big ten does click to wake on their maps. Add this to core geoblacklight.

**Comment by karenmajewicz** [comment]
I don't know that everyone in the community wants this feature.  Is it easily configurable? Does anyone else have input on this?

**Comment by dnoneill** [comment]
Yes. It is configurable in settings.

**Comment by jcoyne** [comment]
Is there a place we can go to find out more information about this feature? Why would one want to have to do an extra click?

**Comment by dnoneill** [comment]
The reason is that the map can act as a scroll trap. See further explanation in the readme for the library of what the BigTen is currently using https://github.com/CliffCloud/Leaflet.Sleep/tree/master.

**Comment by srappel** [comment]
This is a big +1 for me! A couple people have complained to me about unintended map searching in the results view as well as the scroll trap issue in an item show view.
