### ISSUE TITLE
Generating engine cart test app updates package.json

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#1569]
It shouldn't touch the main repo package file.

Results of `git diff ./package.json`  

```
 "dependencies": {
+    "@github/auto-complete-element": "^3.6.2",
     "@hotwired/stimulus": "^3.2.2",
     "@popperjs/core": "^2.11.8",
     "@samvera/clover-iiif": "^2.3.2",
+    "blacklight-frontend": "^7.38.0",
     "bootstrap": "^5.3.3",
     "esri-leaflet": "^3.0.12",
     "leaflet": "^1.9.4",
```

**Comment by thatbudakguy** [comment]
I think this might be related to [things Blacklight does during its propshaft install generator](https://github.com/projectblacklight/blacklight/blob/96a3a85c614ac1a4283c102f59fba05edf3c1cd0/lib/generators/blacklight/assets/propshaft_generator.rb#L6-L16). I don't know why this affects the outer `package.json`, though...

**Comment by thatbudakguy** [comment]
#1539 adds these dependencies explicitly, so there won't be any changes once that is merged.

**Comment by thatbudakguy** [comment]
Going to close this since #1539 was merged, but it might be worth returning to since I don't fully understand the root cause.

**Comment by eliotjordan** [comment]
Reopening because it is still an issue.

**Comment by thatbudakguy** [comment]
Yeah, it still seems to alter the `blacklight-frontend` dependency. I think this is part of actions Blacklight takes during its generators, as noted above, but not sure what to do about it. I wonder if other BL8-based apps (Arclight?) also see this?

**Comment by eliotjordan** [comment]
Closing for now as I can't seem to find a root cause or solution. It seems to happen now when blacklight/frontend versions are bumped, which isn't necessarily a bad result.
