### ISSUE TITLE
Replace solr_wrapper with docker compose

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#1611]
Fully remove solr_wrapper and use compose for test and development.

**Comment by eliotjordan** [comment]
As a community, there has been frustration with solr_wrapper for a long time. It's awkward to use and now we have a solr docker. Why not use it? I would much prefer a dockerized solr over solr_wrapper. It served a function, but technology has advanced.

**Comment by eliotjordan** [comment]
Also, I'm working up a PR to move a lot of our fixtures services (WFS, WMS, IIIF) to containers. If that gets merged it would be nice to spin up all the development parts in one command.

**Comment by ewlarson** [comment]
With our CI test suite and PR pre-built packages already all-in on Docker, I'd like to have one technology path for standing the app up for development, code review, and testing.

Nothing wrong with SolrWrapper whatsoever, and I've really liked it for years, but moving to Docker is key to keeping the stack consistent here.

**Comment by eliotjordan** [comment]
I'll add that development experience for our local blacklight apps really improved once we moved to spinning up Solr with Lando (a convenience tool that uses docker). solr_wrapper is acceptable, but running with docker is definitely an improvement.
