### ISSUE TITLE
Clip to map view for download(?)

### ISSUE THREAD

**Issue by drh-stanford** [geoblacklight/geoblacklight#18]
Do we want to implement this?

**Comment by mapninja** [comment]
Down the road. Nice to have, but not critical.

**Comment by mejackreed** [comment]
@mapninja Can you provide some specific use cases on how someone would use this and the benefit they would get from it? In all of my user interviews I never had a request from it.

**Comment by mapninja** [comment]
SUre. A common one would be:Perhaps a user is interested in Census Boundaries for a single US County, or HydroSheds data for a specific area. Rather than downloading the whole country or world, they define an area (either through drawing or zoom/extent) and clip and ship.

**Comment by mejackreed** [comment]
Agreed that is a use of that functionality. My concern is starts to enter the realm of geoprocessing/analysis. Let's keep an eye on this and see how many requests we get for it.

**Comment by mapninja** [comment]
I agree. I would stop with clip and ship and go no further. Particularly useful if we start serving out large raster datasets, like elevation, Lanscan, etc...

**Comment by eliotjordan** [comment]
Clip and ship is outside of GeoBlacklight.
