### ISSUE TITLE
CD/DVD-ROMs icons not shown

### ISSUE THREAD

**Issue by drh-stanford** [geoblacklight/geoblacklight#198]
In the cases where the `dc_format_s` is `CD-ROM` or `DVD-ROM`, then I've set `layer_geom_type_s` to `Mixed` as we don't know what's on the CD/DVD.

In these cases, right now, there's a blank icon, and we should put a icon there.

Here is an example:

  https://kurma-earthworks-stage.stanford.edu/catalog/mit-002149964

where the Solr record looks like:

```
      {
        "layer_slug_s": "mit-002149964",
        "dc_format_s": "CD-ROM",
        "layer_geom_type_s": "Mixed",
      }
```

**Comment by mejackreed** [comment]
Is this still valid? I have some concerns about conflating the two fields to determine the icon. This may be confusing to a user

**Comment by drh-stanford** [comment]
Yes this is old.
