### ISSUE TITLE
Revisit the way solrconfig.xml and catalog_controller.rb interact

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#241]
Currently the way that we are configuring solr and `CatalogController`, we are breaking (I think) several Blacklight features.

From what I can tell here is what is broken:
- adding additional `search_field`s
- `display_type_field` (could be useful for doing better stuff for wms/iiif/etc)
- ... anything else?

**Comment by eliotjordan** [comment]
@mejackreed Is this still an issue after the latest upgrades?

**Comment by mejackreed** [comment]
We covered a lot of this. I'm not sure if search fields are configurable yet? I'll try and look into this next week.
