### ISSUE TITLE
Add Thumbnails to Show Page

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#257]
Adding thumbnails, if available, would be nice for viewing restricted items or items without wms/iiif endpoints.

**Comment by drh-stanford** [comment]
The schema provides for a `dct_references` for a `http://schema.org/thumbnailUrl`. But we'd need to implement this as a fallback on the item view page where WMS or IIIF.

**Comment by krdyke** [comment]
Has anyone done any work towards implementing thumbnail viewing? If not I might take a crack at it, as in the CIC project we're going to have a lotta scanned maps (with stable URLs) and not a lotta IIIF.

**Comment by eliotjordan** [comment]
@krdyke Take a look at some of the thumbnail work I did for Princeton's GeoBlacklight instance. I'll be spending most of July and August to get it up and running.

https://github.com/pulibrary/pulmap/blob/master/lib/thumbnail.rb

**Comment by krdyke** [comment]
Thanks Eliot, that looks great!

**Comment by ewlarson** [comment]
Yes, I think once we complete the "more documentation" part of geoblacklight_sidecar_images we can close this ticket.

**Comment by ewlarson** [comment]
Closing. Feature is documented on GBL Sidecar Images plugin [README](https://github.com/geoblacklight/geoblacklight_sidecar_images/blob/develop/README.md#view-customization).
