### ISSUE TITLE
Question about dct_temporal and multivalues

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#263]
It looks like blacklight_range_limit doesn't like multivalued integer fields and is causing a javascript error on results pages that contain multivalued dct_temporal fields. See https://earthworks.stanford.edu/?utf8=%E2%9C%93&q=1000+meter

Here is the line that is erroring: https://github.com/projectblacklight/blacklight_range_limit/blob/master/app/assets/javascripts/blacklight_range_limit/range_limit_slider.js#L50

Should we remove multivalued dates? Try to fix the plugin? Remove the plugin?

**Comment by jcoyne** [comment]
Fixing the plugin would be great.

**Comment by drh-stanford** [comment]
Aren't we using `solr_year_i` for the date range query? It's single valued and populated.

See https://github.com/sul-dlss/earthworks/blob/master/app/controllers/catalog_controller.rb#L78

**Comment by mejackreed** [comment]
Hmm.. @drh-stanford you right here. Maybe then it is dying on the value `0`. I'll investigate it further, but the records that I was seeing the error on were multivalued ones. Maybe all of our multivalued records begin with `0`?

**Comment by mejackreed** [comment]
Was an issue with zero values in Blacklight Range Limit https://github.com/projectblacklight/blacklight_range_limit/pull/27
