### ISSUE TITLE
Is citation a feature that others want?

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#264]
This currently doesn't really display correctly. Just wondering if others think this is worth working on?

**Comment by gravesm** [comment]
This is something I've had requests for. It's not a high priority for me right now, but if no one else takes it on, I'll end up doing it at some point.

**Comment by drh-stanford** [comment]
We have "Preferred citations" already in our PURL pages, for example:

http://purl.stanford.edu/wg680pz0365

It's not constructed from the geoblacklight schema, however. The schema does have enough information to generate a proper citation though, albiet not likely in a strict APA or whatever format.

**Comment by mapninja** [comment]
Absolutely desired. If we want to make Geoblacklight  part of an infrastructure for peer-reviewable digital projects, this needs to be there.

**Comment by mejackreed** [comment]
Pinging @jayvarner on this.

**Comment by eliotjordan** [comment]
@karenmajewicz Says yes.

**Comment by karenmajewicz** [comment]
I was planning to bring this up at Camp or the next community meeting. We have team members who are planning to write a tutorial on how to cite data and maps and hoped this feature could be added.

**Comment by mapninja** [comment]
+1 from the subject specialist perspective

**Comment by karenmajewicz** [comment]
A potential solution could be to pre-generate citations and add them to metadata. Relevant Dublin Core field: bibliographicCitation (http://dublincore.org/documents/dcmi-terms/#terms-bibliographicCitation)

**Comment by jayvarner** [comment]
Proper citations would be great. Let me know if I can help.

**Comment by andrewbattista** [comment]
Looks like the BTAA has added a rudimentary citation feature to their application. We could move this into the master branch. I would want it to be configurable if we did.

**Comment by karenmajewicz** [comment]
We added a very basic citation widget to each item page that does not explicitly conform to a style: https://github.com/BTAA-Geospatial-Data-Project/geoportal/blob/develop/app/views/catalog/_citation.html.erb We plan to further document it with descriptions of the elements plus how to deal with missing/erroneous values.
