### ISSUE TITLE
bbox for spatial search at world scale seems to be incorrectly calculating

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#273]
Doing a world scale spatial search tends to not include results. This appears to be an issue with the way that the spatial search js calculates the bounding box it is looking at.

**Comment by mejackreed** [comment]
This method: https://github.com/geoblacklight/geoblacklight/blob/master/app/assets/javascripts/geoblacklight/modules/geosearch.js#L11-L20

I think that `wrap()` may not be appropriate in all cases.

**Comment by gravesm** [comment]
Do you have an example bounds that's not working?

**Comment by gravesm** [comment]
I think this pull request should fix the problem you're seeing, but can you check to make sure you are getting the correct results?
