### ISSUE TITLE
Deprecate solr_bbox and parse new WKT syntax

### ISSUE THREAD

**Issue by drh-stanford** [geoblacklight/geoblacklight#297]

**Comment by drh-stanford** [comment]
- [ ] Change `Settings.GEOMETRY_FIELD` to use `solr_geom`
- [ ] Implement `SolrDocument.bounding_box_as_wsen` to be able to parse the WKT syntax for ENVELOPE(W E N S)

**Comment by mejackreed** [comment]
Maybe also...
 - [ ] remove `solr_bbox` from fixture data

**Comment by mejackreed** [comment]
Some rationale behind all of this:

 - `bbox` is a new field type in Solr. Currently we have it set as a type rpt and we don't want to confuse others
 - We eventually want to use the type `bbox` to use the overlap ratio feature
 - Adding in WKT parsing as we want to use WKT for everything in the long run
