### ISSUE TITLE
Download tracking, cleaning up cache, and background downloading

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#306]
We've been brainstorming around potentially needed features as we gain users. These include:
- track downloads to a specific user

Users can then see the files that they previously downloaded and download them again.
- ability to "clean up cache"

Downloads that are created are never really tracked after they are cached. Download counts can help us delete stale cached files.
- Adding in background processing for these downloads (ActiveJobs) will allow long running downloads to process in background and then be sent to user when completed.

**Comment by eliotjordan** [comment]
Refs: #294

**Comment by andrewbattista** [comment]
This issue looks like it’s a throwback but I still think there’s a need for it or some functionality like it.

**Comment by karenmajewicz** [comment]
no desirable/ needed behavior right now
