### ISSUE TITLE
Email Bookmarks should allow multiple emails

### ISSUE THREAD

**Issue by mapninja** [geoblacklight/geoblacklight#310]
Email Bookmarks dialog should allow multiple email addresses to me entered, either : or, delimited

**Comment by mejackreed** [comment]
Can we expand on this feature a bit more? What is the intended use? For emailing a class or something?

**Comment by mapninja** [comment]
Exactly. Thinking of a workgroup or class situation. Also, it's just a
standard feature on most email to popups (Airline itineraries, etc...), so
people expect it. Not critical, but nice to have in order to meet normal
functional expectations. I'd say this is low priority, just something I
noticed while putting together a demo.

**Comment by mejackreed** [comment]
Ok so I am going to close this issue as it seems that the feature request feels more appropriate to be included as a feature request to Blacklight core, https://github.com/projectblacklight/blacklight/issues or individually adopted at EarthWorks https://github.com/sul-dlss/earthworks/issues . This probably shouldn't be implemented in GeoBlacklight as it really is an intermediary to Blacklight and can be implemented in localized versions of the software. Adding a ticket to EarthWorks: https://github.com/sul-dlss/earthworks/issues/214
