### ISSUE TITLE
Deployment Requirements and Enhancements clarification

### ISSUE THREAD

**Issue by cbeer** [geoblacklight/geoblacklight#312]
From https://github.com/geoblacklight/geoblacklight/wiki/Deployment-Requirements-and-Enhancements:

> One great thing about GeoBlacklight is that it's vanilla installation is simple and does not require any external services. 

Some would argue Solr and a database are external services. Is there a better word?

**Comment by mejackreed** [comment]
Probably.  Maybe:
```
A simple GeoBlacklight installation requires only access to Solr and a database.
```

**Comment by cbeer** [comment]
:+1:
