### ISSUE TITLE
Look at pulling out References classes into a separate gem 

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#329]
Maybe OWSLib-ruby ?

**Comment by eliotjordan** [comment]
If other applications make use them, I can see the advantage of gemifying reference classes. What did you have in mind as far as uses outside of GeoBlacklight?

**Comment by mejackreed** [comment]
Still thinking it through fully. On case I could see is GeoCombine using it to create or translate references on metadata transforms. May not be necessary though. 

I just don't want to replicate the logic. But after adding comments and tests to `References` and `Reference` they feel pretty specific to GeoBlacklight and GeoCombine might not benefit from it.

**Comment by mejackreed** [comment]
Nah.
