### ISSUE TITLE
Solr_bbox replacement for map search functionality?

### ISSUE THREAD

**Issue by sgbalogh** [geoblacklight/geoblacklight#332]
Hi all. I'm working with a development instance of GeoBlacklight, and the search-by-map-position functionality has stopped working for me, I think as a result of updating the app (if that's a possibility?). I see "bbox=" search criteria in the URL that is generated by the app, but it is never successful at faceting by those criteria.

I see from some of the discussion here that bbox has been depreciated –– is the app handling this search in a different way now? I'm running the most recent version of GeoBlacklight (.0.10.0) and Solr 5.0. Any help would be much appreciated!

**Comment by mejackreed** [comment]
Stephen, thanks for the issue contribution.

Do you have the search builder configured in your `catalog_controller.rb` file?

See: https://github.com/geoblacklight/geoblacklight/blob/master/lib/generators/geoblacklight/templates/catalog_controller.rb#L24 

You can also configure the solr field to use for spatial search using `config/settings.yml`

```yml
#Main Solr geometry field used for spatial search and bounding box. Should be type 'rpt'
GEOMETRY_FIELD: 'solr_geom'
```

See https://github.com/sul-dlss/earthworks/blob/master/config/settings.yml#L6

**Comment by sgbalogh** [comment]
Thanks for the reply, Jack. I had rails generate a search_builder.rb file, but it's unclear to me how to customize it in relation to the map view. (I did notice that mine is identical to the Earthworks search_builder: https://github.com/sul-dlss/earthworks/blob/master/app/models/search_builder.rb)

My spatial search solr field is also set to solr_geom, and all of the records that I'm working with have WKT "envelope" geometry in the solr_geom field. I keep getting the feeling that I'm missing something. If it might illuminate this issue more, this is the query that I see being executed whenever I move the map around and use it to search:

```
Solr query: {"qt"=>"search", "facet.field"=>["dct_provenance_s", "dc_creator_sm", "dc_publisher_s", "dc_subject_sm", "dct_spatial_sm", "dct_isPartOf_sm", "solr_year_i", "dc_rights_s", "layer_geom_type_s", "dc_format_s"], "facet.query"=>[], "facet.pivot"=>[], "fq"=>[], "hl.fl"=>[], "start"=>0, "rows"=>10, "q.alt"=>"*:*", "facet"=>true, "f.dct_provenance_s.facet.limit"=>9, "f.dc_creator_sm.facet.limit"=>9, "f.dc_publisher_s.facet.limit"=>9, "f.dc_subject_sm.facet.limit"=>9, "f.dct_spatial_sm.facet.limit"=>9, "f.dct_isPartOf_sm.facet.limit"=>9, "f.solr_year_i.facet.limit"=>11, "f.dc_rights_s.facet.limit"=>9, "f.layer_geom_type_s.facet.limit"=>9, "f.dc_format_s.facet.limit"=>9, "sort"=>"score desc, dc_title_sort asc", "stats"=>"true", "stats.field"=>["solr_year_i"]}
Solr fetch (8.9ms)
```

I don't see any reference to solr_geom in that search string. Could that be the issue, and is that something I can customize by adding logic to the search builder?

**Comment by mejackreed** [comment]
Is the `SearchBuilder` configured in `catalog_controller.rb`?

See: https://github.com/geoblacklight/geoblacklight/blob/master/lib/generators/geoblacklight/templates/catalog_controller.rb#L24

**Comment by sgbalogh** [comment]
Yes, it is –– as far as I can tell. My catalog_controller.rb is identical to this template. Am I incorrect to do that, and should I be configuring SearchBuilder some other way?

I've noticed that when the Solr query generated by moving the map is activated, I receive this error just like this from my Solr core:

```
'error'=>{
    'msg'=>'Can\'t parse point \'23.642578 -4.390229 72.421875 29.382175\' because: java.lang.NumberFormatException: For input string: "-4.390229 72.421875 29.382175"',
    'code'=>400}}
```
My rails app is here, in case that might help settle this: https://github.com/sgbalogh/nyugeoblacklight

**Comment by gravesm** [comment]
That error message seems to suggest that your solr_geom field is a LatLon. What does your schema.xml say for that field?

**Comment by sgbalogh** [comment]
Here is what my schema.xml has about that:
```
<dynamicField name="*_geom" type="location_rpt" stored="true" indexed="true"/>
```

And this is a sample solr_geom field in a record (in fact, the only record in my Solr index at the moment):
```
<field name="solr_geom">ENVELOPE(-125.81, -71.908, 60.973, 0.546)</field>
```

The lon/lat coordinates from that error message in my previous comment were generated by the map interface –– they are the coordinates of the region that the user selects that are sent along with all of the other active search criteria.

**Comment by drh-stanford** [comment]
I haven't tried using Solr 5.0 -- we're using 4.10.4 in production here. The `ENVELOPE` syntax was introduced in 4.10 with the upgrade to Spatial4J 0.4, and is documented here: https://spatial4j.github.io/spatial4j/apidocs/com/spatial4j/core/io/WktShapeParser.html. 

To verify your schema, in the Admin UI for Solr, use the Schema Browser to verify that the `solr_geom` field is of type = `org.apache.solr.schema.SpatialRecursivePrefixTreeFieldType`. Your `schema.xml` looks correct to me though: https://github.com/sgbalogh/nyugeoblacklight/blob/master/jetty/solr/blacklight-core/conf/schema.xml

**Comment by mejackreed** [comment]
@sgbalogh I cloned your repo and indexed two documents using the Solr binary you have committed in `/jetty`. It is version 4.10.3.

Here are the docs I committed:
https://raw.githubusercontent.com/OpenGeoMetadata/edu.stanford.purl/master/bd/427/dr/8948/geoblacklight.json

https://raw.githubusercontent.com/OpenGeoMetadata/edu.princeton.arks/master/08/61/2q/01/v/geoblacklight.json

The spatial search seemed to be working fine by me. Is it possible that there is another instance of Solr running? What happens if you issue a spatial search from filter query to Solr directly?

http://127.0.0.1:8983/solr/blacklight-core/select?q=*%3A*&fq=solr_geom%3A%22Intersects(-82.924805+29.726222+-58.535156+43.739352)%22&wt=json&indent=true

**Comment by sgbalogh** [comment]
Jack and Darren,

Thanks so much for helping with this. Jack –– yes, sorry, my repo is a bit under-documented, but I am actually connecting to Solr 5.0 running on a different Amazon cloud image just by setting the SOLR_URL variable when I begin the WEBrick server, and not the 4.10 install that is part of the repo. GeoBlacklight is definitely connecting to this Solr 5.0 index; I can tell because I've been clearing my index and playing around with a couple records at a time, and the changes to it always propagate instantly to GeoBlacklight.

To your other question, I tried doing that very spatial search on the Solr 5.0 index and get the same error as earlier. Here is the full result of the query: https://github.com/sgbalogh/nyugeoblacklight/blob/master/docs/select.json

Maybe tomorrow I should try installing Solr 4 again? I originally ditched my 4.10 index because of this problem, but that was also before I configured SearchBuilder.

Thanks again for the help. Hopefully this thread will be of use to others, and not just a result of something strange that I messed up along the way.

**Comment by mejackreed** [comment]
@sgbalogh Thanks for reporting this. After looking into further, it seems like an issue with the way Solr 5.x handles query parsing. We haven't had anyone using Solr 5.x yet and had not seen this. Looks like there are other people who have run into this problem too.

http://stackoverflow.com/questions/29691615/solr-throws-exception-while-trying-to-index-spatial-data

The temporary fix now is to use Solr < 5.x (4.10.x).
