### ISSUE TITLE
Update Solr query syntax to support > Solr 5.x spatial query parsing

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#333]
Reported by @sgbalogh in #332

**Comment by mejackreed** [comment]
Looks like this could be fixed by using the Envelope query syntax:

```rb
"Intersects(ENVELOPE(-10, 20, 15, 10))" # W, E, N, S 
```

**Comment by sgbalogh** [comment]
I tried sending that as part of a query to a Solr 5 index and it seems to work! Is this (i.e., how the map bounding box translates into a Solr query) something that I can customize with the SearchBuilder?

**Comment by mejackreed** [comment]
Yep, you should be able to open up that class in your app `Geoblacklight::SearchBuilder` and overwrite this method: https://github.com/geoblacklight/geoblacklight/blob/master/lib/geoblacklight/search_builder.rb#L10-L18

Working on a pull request right now for a fix though.

**Comment by sgbalogh** [comment]
Terrific, thank you!

**Comment by mejackreed** [comment]
@sgbalogh See if this branch will work for you https://github.com/geoblacklight/geoblacklight/tree/add-envelope-support

**Comment by sgbalogh** [comment]
Jack, thanks so much for working on this, and sorry for my delay in responding. I tried updating to that branch, but I'm actually not sure I'm doing it correctly (I just changed the GeoBlacklight gem in my Gemfile to this branch and then ran bundler). When I run my app now the Leaflet map is entirely missing. I suspect that I'm simply messing something up while updating, but my plan is to create a new rails app with your 'add-envelope-support' branch next week.

**Comment by mejackreed** [comment]
@sgbalogh Try adding this line into your geoblacklight.js file : https://github.com/sgbalogh/nyugeoblacklight/blob/master/app/assets/javascripts/geoblacklight.js

```
//= require geoblacklight/basemaps
```

It should look something like this:

https://github.com/geoblacklight/geoblacklight/blob/master/lib/generators/geoblacklight/templates/geoblacklight.js

**Comment by sgbalogh** [comment]
@mejackreed I added the line and Leaflet began working on all of the records –– and the spatial search functionality does indeed seem to be working with Solr 5.0 geometries! Thanks for all the help with this.

Oddly however, even though the home page displays a Leaflet window, no base map is loaded on it (and therefore the button to "Search here" is also missing). This isn't the case if I start a search after clicking on a facet first –– the map always appears next to the results, and also on individual records.

The only thing that I found in the code that might be relevant is something like this line: https://github.com/geoblacklight/geoblacklight/blob/master/lib/generators/geoblacklight/templates/catalog_controller.rb#L222 –– but adding that hasn't worked for me.

**Comment by mejackreed** [comment]
@sgbalogh sounds a bit like a caching issue. Any errors in the JavaScript console? Have you restarted your Rails app?

**Comment by sgbalogh** [comment]
@mejackreed I think you're right; I checked my console and saw an error from map.js: "Cannot read property 'mapquest' of undefined". I actually just ended up creating a new rails app, doing a reinstall from the branch with envelope support, and it works perfectly. I was planning on doing this anyway, since I was getting nervous about me not handling updates properly.

In general, how do you suggest updating GeoBlacklight (assuming this might have been one of the problems)? Should I always just start with installing a new rails app from the most current branch that I want to use, and then bring in all of my settings later? Or is it possible to just update the versions in my Gemfile, and run bundle install?

**Comment by mejackreed** [comment]
GeoBlacklight uses semantic versioning (but we are still pre v1.0.0 release). This means most breaking changes should come in major version releases. The ideal way to update the application is by updating the GeoBlacklight gem in the Gemfile.

In this case, as with other new GeoBlacklight releases, there are release notes associated to help those upgrading. Release notes can be found here:

https://github.com/geoblacklight/geoblacklight/releases

An example of how we updated EarthWorks from GeoBlacklight v0.9.2 to v0.10.0 : https://github.com/sul-dlss/earthworks/pull/269
