### ISSUE TITLE
How should we characterize ESRI web services?

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#336]
Would love to have feedback from @ajturner on what ESRI's thoughts may be on this. For context this pull request adds in support for ESRI web services to the GeoBlacklight discovery software https://github.com/geoblacklight/geoblacklight/pull/335

Open questions seem to be:

 - At what unit should those services be referenced in the metadata?
 - Are there authoritative URI's that ESRI uses to reference their own web services?

I wonder if we can get some more examples from UMN from @cheetah90 or anyone else using ArcGIS.com or ArcGIS Server as there geospatial serving platform.

cc @eliotjordan @drh-stanford

**Comment by ajturner** [comment]
I'm happy to help!

I'm not quite sure what you mean by 'unit'? 

Also, for URI, do you mean reference documentation or schema encoding?

If you want more services to test with http://opendata.arcgis.com

**Comment by eliotjordan** [comment]
@ajturner

By 'unit', Jack (jump in if I'm misstating your intention here) is referring to the type (name) of the protocols and formats we use to enable functionality in Geoblacklight. URI referrs to the reference URI for that type. 

[Schema](https://github.com/geoblacklight/geoblacklight-schema/blob/master/docs/geoblacklight-schema.markdown)
[dct_references](https://github.com/geoblacklight/geoblacklight-schema/blob/master/docs/geoblacklight-schema.markdown)

For instance, WMS endpoints have the reference URI ```http://www.opengis.net/def/serviceType/ogc/wms```. The issue here is how to map the various ArcGIS endpoints into this scheme and at what level. One reference for arcgis/rest/services itself? References for each service (MapServer, FeatureServer, IamgeServer)? Or something else?

**Comment by mejackreed** [comment]
Thanks for the response @ajturner ... To answer your questions:

By "unit" I guess the open question is how are ESRI web services related to the "unit" of metadata that was created for them. In GeoBlacklight, discovery and metadata creation happens at the "layer" level. This seems to relate to a specific "layer" from an ESRI endpoint:

Example, MapServer http://services.arcgisonline.com/arcgis/rest/services/Specialty/Soil_Survey_Map/MapServer

has individual layers:
http://services.arcgisonline.com/arcgis/rest/services/Specialty/Soil_Survey_Map/MapServer/0

MapServer service endpoints have a one to many relationship with additional layers?

ImageServer feels like a one to one relationship:
http://imagery.oregonexplorer.info/arcgis/rest/services/NAIP_2011/NAIP_2011_Dynamic/ImageServer

FeatureServer feels like a one to many relationship:
https://services.arcgis.com/rOo16HdIMeOBI4Mb/arcgis/rest/services/Neighborhoods_pdx/FeatureServer

Does this characterization hold true? Are there additional types to include? @cheetah90

We are using URI's as unique keys in the reference metadata to define what type of service something is. This is based off of the work by the OGC CatInterop group:
https://github.com/OSGeo/Cat-Interop/blob/master/LinkPropertyLookupTable.csv

So using the unique URI as a key to define an ESRI MapServer vs ImageServer endpoint would be useful. We could just make one up here, but it would be great if there was something authoritative from catinterop or ESRI ... @smrazgs ?

Thanks for the link to the open data portal. Is the metadata available in a machine readable format? Or an api? Looking briefly through documentation here: http://resources.arcgis.com/en/help/arcgis-rest-api/#/Portals_Root/02r3000001m8000000/ this doesn't seem to work with opendata.arcgis.com

**Comment by eliotjordan** [comment]
@mejackreed You can add '.json' to the urls to get machine readable data.

[Feature Service](http://opendata.arcgis.com/datasets/6f7e1c88ed3b4742ae418205b79fec3b_0.json)
[Map Service](http://imap.maryland.opendata.arcgis.com/datasets/eec719c01a2e4579b7725d4db942d696_4.json)
[Image Service](http://opendata.arcgis.com/datasets/bc68911120424930b5be550d1e1ba3c8.json)

These are the all different item definitions I could find:

type: ItemImage,
item_type: Image Service
url: ../ImageServer

type: ItemLayer
item_type: Feature Layer
url: ../MapServer/{id}

type: ItemLayer
item_type: Feature Layer
url: ../FeatureServer/{id}

This is still confusing, but maybe the 'top level' units are layer types without regard to the service they come from?
 - Feature Layer
 - Raster Layer (or maybe Tile Map Layer and Dynamic Map Layer)
 - Image Map Layer

**Comment by mejackreed** [comment]
:bow: @eliotjordan

**Comment by mejackreed** [comment]
Thinking this is closed now, see #372 . Reopen if needed
