### ISSUE TITLE
SSL Faraday Connection

### ISSUE THREAD

**Issue by waynegraham** [geoblacklight/geoblacklight#337]
I suppose this is a bit of a philosophical question, but I recently ran in to a problem with the metadata view. We have a wildcard SSL certificate form InCommon which is valid, but does not have public audit records (at least Chrome complains about that). Unfortunately it also appears that `Net::HTTP` verifies SSL certs by default, which throws an exception:

```
.../net/http.rb:920:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
...
```

I've worked around the issue by reworking the  `Geoblacklight::Metadata.retrieve_metadata` method (https://github.com/geoblacklight/geoblacklight/blob/master/lib/geoblacklight/metadata.rb#L30-L39) to set the connection to

```
 conn = Faraday.new(url: @reference.endpoint, :ssl => { :verify => false })
```

I'd prefer not to have overrides in my codebase for this, and am trying to figure out the best way to fix this particular issue and wanted some feedback before I wrote a patch up. Here are some initial thoughts:

1. Patch without verifying the TLS cert. The down side is that this method performs an HTTP fetch and there is chance (hopefully a very small chance) that the endpoint server has been been compromised in some way. 
2. Make the metadata view client side only with something like `highlight.js` (or pick your poison). The downside here are CORS issues. 
3. I stop doing TLS everywhere. Our authentication is handed off to pub_cookie, so this isn't horrible as no user information is really handled by the server (other than some session stuff, but rails is pretty decent at that).
4. Convince our central IT group that they should update their wildcard certs to fix the issue. :trollface:

Anyone have thoughts on what fits best with this project?

Thanks,
Wayne

**Comment by mejackreed** [comment]
So this doesn't solve all of the problems, but I'm wondering if you could just reference the raw metadata from GitHub in OpenGeoMetadata? Use OpenGeoMetadata and GitHub as a delivery service for the MD. We are looking at doing that for our metadata rather than rehosting it.

Would this work around your problem?

**Comment by waynegraham** [comment]
That should actually work for the time being (until GH gets attacked by China again). :smile:

**Comment by mejackreed** [comment]
I hear ya @waynegraham ... For us 1 less service to run > China GitHub attacks :smiley_cat:
