### ISSUE TITLE
Add "Open in ArcGIS.com" button

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#344]
This feature has already been investigated in conjunction with #341 . 

There seem to be some problems though associated with adding this feature which seem to detract from use experience.
- ArcGIS.com seems to take url parameters to add a Esri webservice or wms layer. This "feature" is undocumented from Esri and its unclear how long it will even work
  - `url` parameter for an Esri webservice `http://www.arcgis.com/home/webmap/viewer.html?url=http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/`
  - `wms` parameter for a wms endpoint. Note this takes a `visibleLayers` parameter which indicates what layer to show. `http://www.arcgis.com/home/webmap/viewer.html?wms=https%3A%2F%2Fgeowebservices.stanford.edu%2Fgeoserver%2Fwms&visibleLayers=druid%3Acz128vq0535` 
    - **Note** this doesn't work for all WMS services in fixture data
    - Once in ArcGIS.com as a WMS service, there is not really any way for that data to be used or styled
  - ArcGIS.com doesn't seem to provide for a way to import data directly into a mapview. CartoDB oneclick offers this in a really nice way

**Comment by mejackreed** [comment]
My thought on this is punt on it for now, until someone actually needs this in the future.

**Comment by ajturner** [comment]
This is what we used for adding open in ArcGIS to data.gov

**Comment by mejackreed** [comment]
:+1: ah good to know... thanks @ajturner

**Comment by jgravois** [comment]
based on our discussions at Geo4LibCamp, i whipped up a quick example to show how y'all could use `@esri/arcgis-rest-request` to help ArcGIS users login and create an item of their own (pointing at WFS services) and then launch a new map viewer session.

**please** holler if you have any trouble implementing something similar here.

https://github.com/jgravois/geoblacklight-arcgis

![black_to_arc](https://user-images.githubusercontent.com/3011734/52450515-2e5ee780-2af0-11e9-8e42-cc2fc575951b.gif)
