### ISSUE TITLE
RailsConfig issue with GeoBlacklight initializer?

### ISSUE THREAD

**Issue by sgbalogh** [geoblacklight/geoblacklight#345]
I keep running into a 'NoMethod' error when attempting to `rails generate` around `blacklight:install` or `geoblacklight:install`, using GeoBlacklight .10.1: 

`/gems/geoblacklight-0.10.1/config/initializers/rails_config.rb:1:in ``<top (required)>': undefined method ``setup' for RailsConfig:Module (NoMethodError)`

I've tried building the app using different versions of Ruby (all 2+, though), and Rails (all 4+), but I can't seem to get around this. I'm using RVM to manage the different versions of each, if that might have an effect?

Has anyone else experienced this?

**Comment by mejackreed** [comment]
I haven't ran into this, but it looks like railsconfig just released a new version which could be causing problems. Can you confirm which version of railsconfig that is getting required?

```sh
bundle show rails_config
```

**Comment by sgbalogh** [comment]
Ah, I think that's it –– thanks for the suggestion. I was using rails_config 0.99.0, but I just rolled back to 0.4.2 and I'm able to install without error. I guess the newer version is the culprit?

**Comment by sfisher** [comment]
I had the same problem, also.  This seems to be because of some change they made in 0.99.0.

**Comment by mejackreed** [comment]
Thanks for reporting this issue. You should be able to add this in your local application Gemfile until #346 gets merged. 

```ruby
'rails_config', '~> 0.4.2'
```

**Comment by bajajneha27** [comment]
I had the same issue. Changed the Gemfile to have version 0.4.2 and it worked. Thanks!
