### ISSUE TITLE
Add better user experience for users in "web services" modal

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#348]
Currently we just display the url to the web services. We have had several reports about the lack of usefulness of this. Proposed adding WxS specific parameters to modal.

**Comment by mejackreed** [comment]
Something like this?

<img width="751" alt="screen shot 2015-10-14 at 8 48 56 pm" src="https://cloud.githubusercontent.com/assets/1656824/10504412/0c692998-72b5-11e5-99b1-7fdf1d44faa1.png">

**Comment by esjewett** [comment]
This looks great. Just tried the web service and layer as provided here in Palladio (upcoming version 1.1) and it works.

<img width="1123" alt="screen shot 2015-10-15 at 5 11 34 pm" src="https://cloud.githubusercontent.com/assets/4822/10518039/d8fb7f10-735f-11e5-80e2-fa238abd5177.png">

I wonder if supporting WFS as a source for shape files or even feature data might make sense as well. We can look into it once this is available.
