### ISSUE TITLE
Plans for future development (1.0 and beyond)

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#351]
Lets plan for the next major GeoBlacklight development push. Please add features, bugs, requests, issues that we should address as we move towards version 1.0 and beyond.

- [x] ESRI services support (v1.0)
- [ ] Index maps
- [ ] Grouping around 'collections'
- [ ] Multiple direct file downloads per record
- [x] IIIF image download
- [ ] Improved accessibility
- [x] abstraction around [geoblacklight-schema](https://github.com/geoblacklight/geoblacklight-schema) (v1.0)
- [x] Compatibility with Blacklight 6.x (v1.0)

**Comment by eliotjordan** [comment]
@mejackreed @drh-stanford @gravesm @andrewbattista @cheetah90 @jrgriffiniii @bess @stevenvandervalk

**Comment by eliotjordan** [comment]
Documentation. More guides on the geoblacklight site/blog.
- authentication schemes
- local deployment writeups
- AWS deployment (NYU)

**Comment by mejackreed** [comment]
Blog posts!

**Comment by krdyke** [comment]
One thing that's occurred to me is that we might think about adopting Leaflet 1.0. It's only at beta2, but I've used it for a few projects and it's pretty stable. Definitely would not be a priority, but something to throw on the longer term road map perhaps?

**Comment by mejackreed** [comment]
Great idea. For sure I think we can add in once Leaflet 1.0 is released.

**Comment by eliotjordan** [comment]
On the eve of a 1.0 release, I've created a new ticket for future development plans (#439) and moved over unimplemented items from this issue. Unless there are any objections, I'd like to close this and move any discussion to the new issue. Onward!
![onward](https://cloud.githubusercontent.com/assets/784196/17184719/5bc6aee6-53f3-11e6-919d-be7112c2a19a.jpg)
