### ISSUE TITLE
Teaspoon JS tests are failing

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#367]
Running javascript tests via teaspoon raises the following error:

```
.../.internal_test_app/spec/teaspoon_env.rb:1:in `<top (required)>': undefined method `configure' for Teaspoon:Module (NoMethodError)
```

This is also happening in Travis, but it doesn't cancel the build.

**Comment by mejackreed** [comment]
Yep.. it's been happening for a while. Not sure where it got introduced. I tried to fix at some point but gave up :/

**Comment by eliotjordan** [comment]
I went down quite a rabbit hole trying to track down the origin of this one. Glad to know it wasn't just me.

**Comment by mejackreed** [comment]
The rabbit hole is deep my friend :rabbit: !

**Comment by mejackreed** [comment]
+10 internet points to anyone who can fix it!
