### ISSUE TITLE
data-layer-id empty on show page after update to geoblacklight 0.11.0

### ISSUE THREAD

**Issue by dbranchini** [geoblacklight/geoblacklight#376]
The data-layer-id is empty causing the preview to be empty as well.

Here's an example:  /catalog/stanford-cz128vq0535

<div id="map" data-map="item" data-protocol="wms" data-url="https://geowebservices.stanford.edu/geoserver/wms" data-layer-id="" data-map-bbox="29.572742 -1.478794 35.000308 4.234077" data-catalog-path="/catalog" data-available="true" data-basemap="mapquest" class="leaflet-container leaflet-retina leaflet-fade-anim" tabindex="0" style="position: relative;">

I'm running - 
geoblacklight (0.11.0)
blacklight (~> 5.12.0)

It's worth noting that this started to happen after an update to geoblacklight 0.11.0.

**Comment by mejackreed** [comment]
We haven't seen this bug happening lately in GeoBlacklight. Please reopen if the issue persists.
