### ISSUE TITLE
Provide data (wfs) as csv

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#385]
Is this a feature users might want? @mapninja

**Comment by mapninja** [comment]
Well, maybe if they just want the attribute data. The way Geoserver writes geometry to a csv is not nearly as useful as JSON or Shapefile. In fact, I don't know why anyone who wanted text-based spatial data wouldn't go with JSON, instead. But, just getting the attributes might be something someone would want. I'm going to be agnostic on this one. Is there an option to export without a geometry column? That might be useful.
