### ISSUE TITLE
CartoDB OneClick failure with multi-word "provider" attribute

### ISSUE THREAD

**Issue by sgbalogh** [geoblacklight/geoblacklight#386]
Recently changed the application name of our deployment to "NYU Spatial Data Repository", which breaks the "Open in CartoDB" feature; as it turns out, the provider attribute in the OneClick URL does not like multi-word values, regardless of whether the spaces are URL encoded with `+` or `%20`. I played with a few different variations, and can only get CartoDB to recognize the input file when the provider is a single word (or altogether absent).

[Here](https://github.com/geoblacklight/geoblacklight/blob/c4a1d934e482aad2101f83d1dc5038d6c516875c/app/helpers/geoblacklight_helper.rb#L115) is the line responsible for the OneClick param in question. 

Has anyone run into anything like this before? Easiest solution might be to remove all blank space from `application_name` before sending. Could we also just omit this param altogether? Not sure what CartoDB's functionality for `provider` actually is... and relatedly, if it is meant for layer citation purposes, then maybe we should actually be sending the institution as the provider, rather than the application name?

**Comment by mejackreed** [comment]
Also may be worth filing a bug report with CartoDB. They have been responsive on other bug reports.
