### ISSUE TITLE
JavaScript Options:

### ISSUE THREAD

**Issue by drh-stanford** [geoblacklight/geoblacklight#392]
- [ ] Settings
  - [ ] Leaflet Map
  - [x] Leaflet Layers
    - [x] detectRetina : false

- [x] Ability to add Leaflet Control Plugins

**Comment by mejackreed** [comment]
I'm not sure if we need to enable all of these, but I think `detectRetina: false` would be useful.

**Comment by eliotjordan** [comment]
We have a nice mechanism for adding leaflet configuration options in `settings.yml` now. `detectRetina` is configurable. Is this issue ready to close?

**Comment by mejackreed** [comment]
👍
