### ISSUE TITLE
Create guide for adding fullscreen control

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#402]
Create a guide on the geoblacklight wiki for adding leaflet controls; including a fullscreen option.

**Comment by mejackreed** [comment]
Done here: https://github.com/geoblacklight/geoblacklight/wiki/Adding-Leaflet-control-customization-to-GeoBlacklight

<img width="886" alt="screen shot 2016-04-06 at 8 01 57 am" src="https://cloud.githubusercontent.com/assets/1656824/14321740/5270d6f4-fbcf-11e5-92f5-dbfe00a7d5a4.png">

**Comment by eliotjordan** [comment]
Awesome!
