### ISSUE TITLE
Switch to Winkel-Tripel projection

### ISSUE THREAD

**Issue by jcoyne** [geoblacklight/geoblacklight#404]
Mercator project is great for navigation, but it's highly distorted at the high latitudes.

:trollface:

**Comment by eliotjordan** [comment]
I prefer [armadillo](http://bl.ocks.org/mbostock/4463127).

**Comment by mejackreed** [comment]
@jcoyne pull requests welcome :) We would love to add another contributor to GeoBlacklight. 

No Gall--Peters projection? Obligatory West Wing reference: https://www.youtube.com/watch?v=vVX-PrBRtTY
