### ISSUE TITLE
Support for groupings, collections, datasets

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#405]
Relevant to several ongoing discussions. Initial mocks created several years ago now, probably needs some more design work too.

https://drive.google.com/file/d/0BzWuWHFTTIPEaC1KYkVyRkVfTUU/view?usp=sharing

**Comment by eliotjordan** [comment]
@mejackreed Still something you want to tackle.

**Comment by mejackreed** [comment]
Not at the moment.
