### ISSUE TITLE
Map search is triggered during window resize events

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#408]
Map search is triggered when the browser window is resized. This issue was addressed in Princeton University's Geoblacklight instance. This might work as a general solution.

https://github.com/pulibrary/pulmap/pull/164

**Comment by gravesm** [comment]
The window resize might change the bounds of the visible map, changing the search query. Wouldn't you want this to fire a new search?

**Comment by eliotjordan** [comment]
We made a number of customizations to the Princeton Geoblacklight for which this was a serious issue. The main problem is that a spatial search is automatically triggered when resizing the window. 

![bbox](https://cloud.githubusercontent.com/assets/784196/16996667/e6930438-4e77-11e6-932c-f293fa19cf38.gif)
