### ISSUE TITLE
Track and display Provenance and Relations between items in user interface

### ISSUE THREAD

**Issue by andrewbattista** [geoblacklight/geoblacklight#412]
At NYU, we are showing relations between datasets within our collection. For instance, [in our NYU Community Landmarks](https://geo.nyu.edu/catalog/nyu_2451_34514) file, we have a "Data Relations" box that shows the geodatabase from which this was derived. In the record for the "parent" (i.e., the geodatabase), the "children," (i.e., individual layers) would appear in this box.

Some questions are: are there other scenarios where we would want to show relations between records, and if so what are the best ways to do this? What has to happen in the interface and in the metadata?

**Comment by sgbalogh** [comment]
A link to my earlier stab at this is [here](https://github.com/NYULibraries/spatial_data_repository/commit/ee62b673fce5070dc0a7f83432cae66399bd2603). Very aware that the `Relations` class in particular is probably in dire need of some refactoring, but maybe it serves as a good conversation piece regardless? :grimacing:

**Comment by sgbalogh** [comment]
Should also clarify –– my above implementation relies on there being a field in Settings that defines the `SOURCE`. In my case, I am using `:SOURCE: 'dct_source_sm'`, (described at http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=elements#source), and so a record only needs to point to its "parent", and not the other way around, for a data relation to be visualized.

**Comment by drh-stanford** [comment]
Source is a core Dublin Core element so it would be `dc_source_sm` technically.

**Comment by drh-stanford** [comment]
@sgbalogh what values are you putting in the source field? `layer_slug_id` values or the titles of the layers or something else?

**Comment by sgbalogh** [comment]
@drh-stanford: we're putting the slug id values, so something like `nyu_1234_56789`.

**Comment by drh-stanford** [comment]
I put in documentation for `dc_source_sm` here: https://github.com/geoblacklight/geoblacklight/blob/master/schema/geoblacklight-schema.md

**Comment by sgbalogh** [comment]
One issue discussed in today's sprint stand-up:

There are (at least) two types of relation tracking that we want to potentially represent. One that establishes parent/child relations –– i.e., between a geodatabase and a shapefile layer that is a proper subset of that geodatabase –– where both parent and child are records in a GeoBlacklight catalog. Another type of relation is between a dataset and external (URL) sources, like the Census Bureau, NYC Department of City Planning, etc.

**Comment by andrewbattista** [comment]
> Another type of relation is between a dataset and external (URL) sources, like the Census Bureau, NYC Department of City Planning, etc.

This is the instance of Relation that we could/should address moving forward

**Comment by andrewbattista** [comment]
I think we can just assume that people can use this relation however they'd like. I'm closing this, as it doesn't seems current anymore
