### ISSUE TITLE
Add "Open in ESRI Online" button

### ISSUE THREAD

**Issue by andrewbattista** [geoblacklight/geoblacklight#414]
I don't know where the status of this is, or if it requires work done by ESRI, but it would be nice to explore the possibility of adding an "Open in ESRI" online button, akin to the CartoDB button.

**Comment by mejackreed** [comment]
See #344

**Comment by mejackreed** [comment]
Sorry closed as a duplicate ticket. See #344 for reference. Essentially there isn't an API available for this, no support, guarantee of future support, and the way it currently works is pretty shoddy.
