### ISSUE TITLE
Direct download for documentation/codebook from dct:references

### ISSUE THREAD

**Issue by sgbalogh** [geoblacklight/geoblacklight#424]
Any interest in something like this for core? At NYU we are using `http://schema.org/additionalType` as a key, in `dct_references_s`, with a value that is a URL to a direct download link for some sort of documentation related to a record. An example of a record with documentaiton is here: https://geo.nyu.edu/catalog/nyu_2451_34670

This is also reliant on being able to specify URI constants.

**Comment by mejackreed** [comment]
Closed by #461 ?
