### ISSUE TITLE
Move geoblacklight required files from geoblacklight-schema

### ISSUE THREAD

**Issue by drh-stanford** [geoblacklight/geoblacklight#425]
The `geoblacklight-schema` repo is historical and has tools/examples that are not used by GeoBlacklight. This issue is to migrate those files that GeoBlacklight *does* use into the geoblacklight repo. Be *sure* to use Solr 4 files -- see https://github.com/geoblacklight/geoblacklight/issues/409 for Solr 6 issues

- [ ] `schema.xml`
- [ ] `solrconfig.xml`
- [ ] schema doc

Note that there are 2 pathways:
- configuring a development instance of Solr for GeoBlacklight
- configuring a production instance of Solr for GeoBlacklight

**Comment by mejackreed** [comment]
We already have some fixtures in geoblacklight. Should we stick with those or move to `selected.json`

**Comment by drh-stanford** [comment]
ok deleted the fixtures subtask.
