### ISSUE TITLE
UI errors with institution facet display and search box

### ISSUE THREAD

**Issue by sgbalogh** [geoblacklight/geoblacklight#427]
Noticed these issues when using the BL-6 branch (current master). 

<img width="701" alt="screen shot 2016-07-26 at 3 38 46 pm" src="https://cloud.githubusercontent.com/assets/10469527/17152996/6af05dd2-5348-11e6-9220-fe85bda4366a.png">
<img width="257" alt="screen shot 2016-07-26 at 3 21 00 pm" src="https://cloud.githubusercontent.com/assets/10469527/17153001/6fe2ff98-5348-11e6-98e9-f37ace17dd4c.png">

**Comment by sgbalogh** [comment]
For the second error (institution facet display), it does seem to have to do this: https://github.com/projectblacklight/blacklight/blob/master/app/assets/stylesheets/blacklight/_facets.scss#L78 (pointed out by @eliotjordan); correcting the text-indent to approximate how it looked before the update will mess up all of the facets without icons. Perhaps the fix needs to deal with the geoblacklight-icon span?

**Comment by sgbalogh** [comment]
[This twitter-typeahead SCSS] (https://github.com/projectblacklight/blacklight/blob/d55d6f566d203a092f7f40987a37d8988df5500d/app/assets/stylesheets/blacklight/_twitter_typeahead.scss#L6-L13) in Blacklight seems to be related to the issue with the search field; for whatever reason, `width: 100%` is not making it to the browser...

**Comment by sgbalogh** [comment]
Looks like changing the above code in the Blacklight SCSS for twitter-typeahead to this:
```
  .search_q.q.form-control.tt-input {
    width: 100%;
  }
 .search_q.q.form-control.tt-hint {
    width: 100%;
  }
```
fixes it

**Comment by mejackreed** [comment]
Checking to see if I can replicate the issue in Blacklight.

**Comment by sgbalogh** [comment]
Here is a workaround for the .facet-label class [here](https://github.com/projectblacklight/blacklight/blob/master/app/assets/stylesheets/blacklight/_facets.scss#L78 )

```
  .facet-label {
    display: inline-block;
    padding-right: 1em;
    margin-left: 5px;
    text-indent: -15px;
    padding-left: 15px;
    padding-bottom: $padding-base-vertical;
    @include hyphens-auto;
  }
```

<img width="315" alt="screen shot 2016-07-27 at 11 39 08 am" src="https://cloud.githubusercontent.com/assets/10469527/17181810/621d470e-53ef-11e6-9f68-7bb2c1ea046b.png">

**Comment by sgbalogh** [comment]
Closing; broken issues into #438 and #437
