### ISSUE TITLE
what is the range of values for dc_format?

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#429]
I'm wondering if `dc_format_s` is necessary in a geoblacklight schema document, or if it even makes sense. I've always found it a bit confusing. When I look at the format facet I think of  `Shapefile` as a stand-in for `vector` and `GeoTIFF` a stand-in for `raster`.

In my mind, a document describes a geospatial work and all of its metadata, files, and derivative files. In this view, then, `dc_format` indicates the format of the original file. Is this something that users even care about faceting on?

**Comment by mejackreed** [comment]
It might be? If we start adding things like GeoDatabases ? Does that fit under `dc_format` or elsewhere?

**Comment by sgbalogh** [comment]
NYU has been putting file formats like GeoDatabase into `dc_format_s` –– see https://geo.nyu.edu/catalog/nyu_2451_34602.json for example. If nothing else, it is useful insofar as it supplies the name of the file in the direct download link: 
<img width="251" alt="screen shot 2016-07-27 at 11 46 54 am" src="https://cloud.githubusercontent.com/assets/10469527/17181940/dc2eeade-53ef-11e6-8146-3567effbae6f.png">

**Comment by drh-stanford** [comment]
Note that the value of `dc_format_s` is used in the GeoBlacklight application logic so it is a de facto controlled vocabulary.

**Comment by drh-stanford** [comment]
So a suggested solution is to create a simple ontology that builds URIs based on the GDAL/OGR codes and that has better human-readable descriptions. This would eventually be a reusable gem and integrated into the documentation so that the facet values have consistency.

**Comment by drh-stanford** [comment]
Note that https://github.com/geoblacklight/geoblacklight/pull/477 removes the `enum` limitation on the the `dc_format_s` field until we can settle on a controlled vocabulary

**Comment by andrewbattista** [comment]
Now, with addition of LiDAR, Geodatabases, etc. it seems like coming up with a controlled vocabulary is harder. Doesn't mean we shouldn't do it, but if institutions have been effectively functioning without one, maybe we should drop this and keep it non-controlled?

**Comment by KarenMajewicz** [comment]
List of current formats in use by NYU, Stanford, Big10: https://docs.google.com/spreadsheets/d/1JGBz03POnLyfjSIzBH9LZtJLQqlnIvBVdYvZPP92RFo/edit#gid=1741662979

**Comment by andrewbattista** [comment]
This is basically decided (at least for now) with the schema work from last winter, and the addition of the [format-values.md](https://github.com/geoblacklight/geoblacklight/blob/master/schema/format-values.md) file, right? See

**Comment by karenmajewicz** [comment]
The values are pretty much listed on the doc, and custom ones can be used as well.

In terms of @eliotjordan original question on this issue "I'm wondering if dc_format_s is necessary in a geoblacklight schema document..." - if we move forward with the multiple downloads schema change, I believe that we would no longer use dc_format anyways?

**Comment by andrewbattista** [comment]
Correct.... it may render this issue moot. Thus, I am marking this to be closed!
