### ISSUE TITLE
Search box not spanning 100% (twitter-typeahead issue)

### ISSUE THREAD

**Issue by sgbalogh** [geoblacklight/geoblacklight#437]
See image below:
<img width="701" alt="screen shot 2016-07-26 at 3 38 46 pm" src="https://cloud.githubusercontent.com/assets/10469527/17184109/92f7b16c-53f8-11e6-8bae-46a62de16480.png">

[This twitter-typeahead SCSS](https://github.com/projectblacklight/blacklight/blob/d55d6f566d203a092f7f40987a37d8988df5500d/app/assets/stylesheets/blacklight/_twitter_typeahead.scss#L6-L13) in Blacklight seems to be related to the issue with the search field; for whatever reason, width: 100% is not making it to the browser...

Changing the relevant lines to
```
  .search_q.q.form-control.tt-input {
    width: 100%;
  }

 .search_q.q.form-control.tt-hint {
    width: 100%;
  }
```
seems to fix the issue.

**Comment by drh-stanford** [comment]
Not sure if this is related to the search bar but I'm also getting a JavaScript console error for this line in blacklight.css: "Unexpected CSS token: :" The "Search..." is not visible on the home page 

```
filter: progid: DXImageTransform.Microsoft.gradient(enabled = false);
```

**Comment by mejackreed** [comment]
What browser are you seeing that in @drh-stanford .. I cannot recreate in Chrome.
