### ISSUE TITLE
Facet display with geoblacklight-icon issue

### ISSUE THREAD

**Issue by sgbalogh** [geoblacklight/geoblacklight#438]
See below for example:
<img width="257" alt="screen shot 2016-07-26 at 3 21 00 pm" src="https://cloud.githubusercontent.com/assets/10469527/17184172/e09c0486-53f8-11e6-8b5f-babcbdb9a66d.png">

This seems to have to do with [this code](https://github.com/projectblacklight/blacklight/blob/master/app/assets/stylesheets/blacklight/_facets.scss#L77-L84), part of Blacklight core.

Changing the above to:
```
  .facet-label {
    display: inline-block;
    padding-right: 1em;
    margin-left: 5px;
    text-indent: -15px;
    padding-left: 15px;
    padding-bottom: $padding-base-vertical;
    @include hyphens-auto;
  }
```
seems to fix it adequately. See below:

<img width="315" alt="screen shot 2016-07-27 at 11 39 08 am" src="https://cloud.githubusercontent.com/assets/10469527/17184216/104e6598-53f9-11e6-8dcc-0deeec02182a.png">

**Comment by mejackreed** [comment]
I'm thinking the fix here is to actually change the way we render the facet partial. Working on something locally here.. i'll see if i can push it up
