### ISSUE TITLE
Improve wiki page about using the Schema

### ISSUE THREAD

**Issue by drh-stanford** [geoblacklight/geoblacklight#465]

**Comment by mejackreed** [comment]
Not sure... here? https://github.com/geoblacklight/geoblacklight/blob/master/schema/geoblacklight-schema.md

**Comment by drh-stanford** [comment]
yes that's the authoratative location for the elements. the wiki is going to be more explanatory with examples, etc. https://github.com/geoblacklight/geoblacklight/wiki/Schema

**Comment by drh-stanford** [comment]
Hey @kimdurante, can you take a look at the new Wiki page? https://github.com/geoblacklight/geoblacklight/wiki/Schema
