### ISSUE TITLE
Safari chokes on bootstrap-sass CSS

### ISSUE THREAD

**Issue by drh-stanford** [geoblacklight/geoblacklight#468]
See https://github.com/twbs/bootstrap/issues/15256 and https://github.com/sul-dlss/earthworks/issues/317

**Comment by eliotjordan** [comment]
This looks OK in Blacklight 7.01. This might be fixed. We should check to be sure on GeoBlacklight 2.0.

**Comment by eliotjordan** [comment]
Confirmed this is no longer an issue with GBL 2.
