### ISSUE TITLE
Download for generated shapefile downloads is not working

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#473]
The download path for generated shapefile downloads is not working. Discovered this while updating geoblacklight for rails 5. Not sure why it didn't show up earlier.

Example: 

- Go to: https://earthworks.stanford.edu/catalog/mit-us-ma-e25zcta5dct-2000
- Click 'Download Shapefile'
- Click the download link that appears on the flash banner
- Error!

**Comment by eliotjordan** [comment]
This affects all generated downloads (kmz, geojson). Not just shapefiles.

**Comment by drh-stanford** [comment]
This _might_ be a configuration issue with EarthWorks. See https://github.com/sul-dlss/earthworks/issues/320

**Comment by drh-stanford** [comment]
Fixed in https://github.com/geoblacklight/geoblacklight/pull/474
