### ISSUE TITLE
Deprecate dc_type_s

### ISSUE THREAD

**Issue by drh-stanford** [geoblacklight/geoblacklight#476]
Do we use this `dc_type_s` field anywhere? As a facet, for example.

**Comment by KarenMajewicz** [comment]
The Big Ten geoportal is using this as dc_type_sm for not only dataset vs image, but also to classify items with web services and interactive resources (applications).

**Comment by andrewbattista** [comment]
I am motioning to close this issue as the field still seems to be a functioning part of the schema
