### ISSUE TITLE
CSW endpoint

### ISSUE THREAD

**Issue by drh-stanford** [geoblacklight/geoblacklight#48]
We'd like to have a CSW endpoint to integrate with other CSW harvesters.

**Comment by mejackreed** [comment]
We may want to look at the newer CAT 3.0 specification: http://www.opengeospatial.org/standards/cat

This might be much easier to implement and get going as its closer to OpenSearch

**Comment by mejackreed** [comment]
And.. http://www.opensearch.org/Specifications/OpenSearch/Extensions/Geo/1.0/Draft_1#The_.22box.22_parameter

**Comment by eliotjordan** [comment]
Closing for lack of interest.
