### ISSUE TITLE
Regular community sprints

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#484]
Since adoption of GeoBlacklight is picking up and there is a lot of new functionality being planned for future releases, I wonder if it makes sense to schedule community sprints on a more regular basis. Maybe every 4 months? Every six months? Obviously, not everyone can participate in each sprint, but our community is growing and this will (hopefully) be less of an issue. Just a thought.

**Comment by mejackreed** [comment]
Great idea @eliotjordan ! How do you think we can move this forward?

**Comment by eliotjordan** [comment]
I think we could schedule a community GeoBlacklight call for sometime in the near future and make a proposal.

**Comment by eliotjordan** [comment]
We've been consistent with a Winter and a Summer sprint. Mission Accomplished.
