### ISSUE TITLE
WMS inspection fails when geoblacklight is running under a sub url

### ISSUE THREAD

**Issue by gravesm** [geoblacklight/geoblacklight#490]
The location of the WMS handler is hard coded as `/wms/handle` in https://github.com/geoblacklight/geoblacklight/blob/master/app/assets/javascripts/geoblacklight/viewers/wms.js#L52. If geoblacklight is being run under a sub url, for example `http://example.com/geoblacklight/`, this request will fail.

**Comment by andrewbattista** [comment]
Seems worth looking at trying to fix

**Comment by ewlarson** [comment]
Closing. Re-open if real-world example occurs.
