### ISSUE TITLE
Make Map&Table Preview an oEmbed object

### ISSUE THREAD

**Issue by mapninja** [geoblacklight/geoblacklight#492]
Would be nice to be able to embed Map&Table preview from the individual data landing pages in blogs, spotlight, etc... as an Embed. Also would give some of the best functionality (layer level preview) to other discovery portals/platforms, like Blacklight and Spotlight.

**Comment by mejackreed** [comment]
I'm not exactly sure what the feature request here is. Should the show page also respond to an oembed request? Or are you hoping that the attribute inspection could be provided in the Stanford oembed service?

**Comment by mapninja** [comment]
Both, I think. I'd like to see the map preview and attribute inspection moved into an oembed, so that the purl page gets both, as well as providing the ability to embed the previews into other pages (Spotlight, Blacklight, blogs, etc...).

**Comment by mejackreed** [comment]
Ok.. mind opening up an issue here for that? https://github.com/sul-dlss/sul-embed

I don't think this is something within the scope of GeoBlacklight.
