### ISSUE TITLE
JSON Schema has wrong type

### ISSUE THREAD

**Issue by gravesm** [geoblacklight/geoblacklight#496]
I may be missing something, but it looks like the schema has the wrong type associated with it, on line 6:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Schema for GeoBlacklight. See https://github.com/geoblacklight/geoblacklight/wiki/Schema for more details.",
  "id": "http://geoblacklight.org/v1.0/schema",
  "title": "GeoBlacklight Schema",
  "type": "array",
```

I believe the `type` should be `object`.

**Comment by drh-stanford** [comment]
We're using `JSON::Validator.validate(schema, doc, fragment: '#/properties/layer')` in GeoCombine to do the validation. We have a use case where a single .json document has many layers. I wasn't sure what to do about that in the JSON-Schema definition. Any ideas?

See https://github.com/OpenGeoMetadata/GeoCombine/blob/master/lib/geo_combine/geoblacklight.rb#L48

**Comment by gravesm** [comment]
@drh-stanford: This seems to work for both the ruby validator and the python validator I've been using. It would require changing GeoCombine to remove the fragment identifier.
