### ISSUE TITLE
Update and support Leaflet 1.0

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#501]

**Comment by ewlarson** [comment]
I could try giving this upgrade a shot. Are there any known gotchas here?

**Comment by mejackreed** [comment]
The biggest gotcha might be the way with the which the leaflet-rails gem has included assets. Likely we will want to at least smoke test this (specifically points on a map) in `RAILS_ENV=production`. See https://github.com/axyjo/leaflet-rails/issues/63 https://github.com/axyjo/leaflet-rails/issues/59

**Comment by ewlarson** [comment]
Test upgrade to leaflet 1.1.0 displaying similar issues from esri-leaflet here:
https://github.com/Esri/esri-leaflet/issues/967

Will attempt 1.0.0 upgrade now.

**Comment by ewlarson** [comment]
Fixed in master #679
