### ISSUE TITLE
layer_id_s is not required, but can cause issues with loading a page

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#517]

**Comment by KarenMajewicz** [comment]
This seems to be working in the latest release- is it still an outstanding issue?

**Comment by eliotjordan** [comment]
I agree with Karen. This appears to no longer be an issue. @mejackreed do you have any specific examples that we should look at, or is this OK to close?

**Comment by mejackreed** [comment]
Nope no examples here. I think this was from when I was testing w/ non-geo data. Closing until we can figure out a more definite example.
