### ISSUE TITLE
Add default values when using Blacklight::Document#fetch

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#518]
One example: https://github.com/geoblacklight/geoblacklight/blob/master/app/models/concerns/geoblacklight/solr_document.rb#L63

**Comment by andrewbattista** [comment]
@mejackreed we are unsure of what this is about. Is this fixed?

**Comment by mejackreed** [comment]
Hmm.. yeah could be a better issue. I think this may help to allow GeoBlacklight to function when a layer's bbox is not available.

**Comment by karenmajewicz** [comment]
unclear what this is about
