### ISSUE TITLE
Point cloud viewer for GeoBlacklight

### ISSUE THREAD

**Issue by sgbalogh** [geoblacklight/geoblacklight#523]
Any interest in this? NYU has a potential use case now with some LIDAR datasets.

Perhaps http://potree.org/

**Comment by mejackreed** [comment]
This would be cool! Other discussion now happening in IIIF around 3d and 3d viewers too

**Comment by andrewbattista** [comment]
This should be lumped into our recent discussion of creating some configuration options for IIIF viewers

**Comment by andrewbattista** [comment]
Are we OK with closing this under the auspice that the inherent integration of the oEmbed Protocol (see #836 for more info).
