### ISSUE TITLE
Render search bar on all views?

### ISSUE THREAD

**Issue by tampakis** [geoblacklight/geoblacklight#530]
I noticed that in Geoblacklight that the search bar only renders on the home page (a custom one) and on the search results page because of https://github.com/geoblacklight/geoblacklight/blob/3603575c85b81b4070d56f3011dd9b55873a2697/app/views/shared/_header_navbar.html.erb#L19.

Example pages: https://earthworks.stanford.edu/catalog/stanford-dg548ft1892, https://earthworks.stanford.edu/bookmarks

Is it desirable to hide the search bar on these other pages?

**Comment by mejackreed** [comment]
I like the idea of showing it everywhere, seems like it should be. I wonder if @MetaMara ran into any user issues that this could help with

**Comment by MetaMara** [comment]
Just to clarify, we are talking about having the search bar appear on the item pages as well the home and results pages? This actually didn't seem to be a problem for users in our study. For users on the item page, we saw the most used/most desired option as "back to search." It seemed like by the time users were looking through specific items, they were more interested going back to their results and perhaps making adjusting facets instead going back to the search. I don't think it would hurt to add the search bar, as long as it didn't make the "back to search" option harder to find.

**Comment by andrewbattista** [comment]
Ahh, I see now. I was confused, but I agree with Mara here. It wouldn't hurt to have the search bar appear on the individual items. In fact, I think it would help!
