### ISSUE TITLE
Support JTS geometry in a configurable way

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#534]
### Descriptive summary

A prerequisite to #524 and #533. 

JTS (Java Topology Suite) should be able to easily be added to an adopter's solr configuration. This should be optional and part of an automatic generator that can be turned on with an argument passed to the generator.

Some exploratory work was started here: https://github.com/geoblacklight/geoblacklight/compare/add-jts-to-install?expand=1

**Comment by eliotjordan** [comment]
Let's talk about this again.
