### ISSUE TITLE
Rails 4.2 support?

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#543]
### Descriptive summary

CI builds #537 and #542 are built using blacklight 6.10.0, which discarded support/testing for Rails 4.2, and thusly fail:
https://github.com/projectblacklight/blacklight/releases/tag/v6.10.0

Perhaps GBL should also drop support for 4.2?

The build fails due to migration versioning (ex. [4.2] here):
https://github.com/projectblacklight/blacklight/blob/master/db/migrate/20140202020201_create_searches.rb#L2

Rails 5 supports versioning migrations, but 4.2 does not.

### Expected behavior

4.2 build should work.

### Actual behavior

4.2 build fails.

### Steps to reproduce the behavior

Test against 4.2.

**Comment by mejackreed** [comment]
Rails 4.2 support dropped in https://github.com/geoblacklight/geoblacklight/pull/545
