### ISSUE TITLE
Failing test suite

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#569]
### Descriptive summary

Unrelated to any specific GBL commit/code, the [test suite is failing](https://travis-ci.org/geoblacklight/geoblacklight/builds/289661635). It appears to be related to capybara/selenium element visibility issues.

### Expected behavior

I expect the master branch test suite to pass.

### Actual behavior

The master branch test suite fails, with several "Unable to find visible css" errors.

### Steps to reproduce the behavior

clone the repo
bundle exec rake ci

**Comment by ewlarson** [comment]
Debugging notes: Some errors are rails_ujs related, too -- which was added to Rails 5.1.  The most recent BL releases slip us into Rails 5.1+ and the test suite fails.  Locking GBL down to BL 6.11.0 seems to solve things...

**Comment by mejackreed** [comment]
This might be related, but I had to add some compatibility layer in Spotlight: https://github.com/projectblacklight/spotlight/pull/1834/files

I also remember an issue with CSRF needing to be removed or something? This may help.

**Comment by ewlarson** [comment]
Ok, these tests largely fail because the catalog#show tool links -- Metadata, Cite, etc. -- open a modal that insists on re-fetching all the JS assets (layout wrapper, too).  BL 6.11.0 is the last release that doesn't exhibit the bug.

I'll spend some more time chasing down what happened between 6.11.0 and 6.11.1 to see what we can do to solve the issue.

**Comment by mejackreed** [comment]
Maybe checkout this? https://github.com/projectblacklight/blacklight/pull/1797

**Comment by ewlarson** [comment]
[That PR](projectblacklight/blacklight#1797) does fix things for email, sms, cite... but it doesn't solve the issue for our custom "metadata" action.

**Comment by ewlarson** [comment]
It may be pinning ourselves to 6.11.0 like Avalon for the time being:
https://github.com/avalonmediasystem/avalon/pull/2395
