### ISSUE TITLE
Multiple Geometries 

### ISSUE THREAD

**Issue by lauraneckstein** [geoblacklight/geoblacklight#572]
I'd love a feature to handle a record with multiple geographic points.
Example: a trade card representing one business that had multiple branches at multiple addresses ( Boston, NYC, Baltimore). The trade card says “Abe Cohen, Clothier, Boston, New York City, and Baltimore.”

**Comment by andrewbattista** [comment]
Hi, @lauraneckstein - we are attempting to organize our efforts for the Summer 2018 development sprint. Can you give us more of a sense of what this development would entail and how high of a priority it is? Thanks!

**Comment by lauraneckstein** [comment]
@andrewbattista

**Comment by andrewbattista** [comment]
@lauraneckstein - no worries! We were trying to organize and clean up issues for our summer sprint. Your comments are still welcome, as we can either "close" this issue, or reframe it and schedule it for an upcoming sprint. We just were a little unclear on what you meant.
