### ISSUE TITLE
Update for Blacklight 7 deprecations

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#578]
- [x] render_document_show_field_value is deprecated and will be removed from Blacklight version 7.0.0 (replaced by ShowPresenter#field_value). See #583
 - [x] BlacklightHelper#application_name will no longer delegate to config.application_name in version 7.0. Set the i18n for blacklight.application_name instead.

**Comment by eliotjordan** [comment]
Closed by #657
