### ISSUE TITLE
Add Thumbnails to search results pages

### ISSUE THREAD

**Issue by karenmajewicz** [geoblacklight/geoblacklight#584]
### Descriptive summary

This would provide a new layout for the search results pages that included a thumbnail when available.  This image would be either generated via IIIF/ web services or it could be provided via a static URL.

### Related work

Thumbnails for item pages: https://github.com/geoblacklight/geoblacklight/issues/257

**Comment by eliotjordan** [comment]
Closed because of https://github.com/geoblacklight/geoblacklight_sidecar_images
