### ISSUE TITLE
Icon facet "More" not displaying

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#587]
### Descriptive summary

The `_icon_facet.html.erb` partial is used for displaying facet lists for facets that have icons (institutions, data type). But the "more" link is not displaying for when there is a limit for the catalog controller.
### Expected behavior
The "More" link should be available.
### Actual behavior
No "more" link

![screen shot 2018-01-16 at 10 28 54 am](https://user-images.githubusercontent.com/1656824/35002810-12996a76-faa8-11e7-9046-4234bd77d67b.png)

**Comment by ewlarson** [comment]
We saw this [a long time ago](https://github.com/BTAA-Geospatial-Data-Project/geoportal/issues/7) (apologies for not acting on it). The _icon_facet partial just doesn't include any logic to render the more link.
