### ISSUE TITLE
Move layer preview map and attribute table / index map to a new row

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#599]
### Descriptive summary
Originally proposed by @ewlarson , this would allow layer previews and associated information to take up the entire page width

**Comment by jrgriffiniii** [comment]
After reviewing https://github.com/geoblacklight/geoblacklight/pull/693, it appears that there was a bug in #681 triggering a regression for this

**Comment by jrgriffiniii** [comment]
This was reopened in error, as it was indeed resolved in #681
