### ISSUE TITLE
Reconsider geometry type field

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#630]
At the moment the `layer_geometry_type_s` feels a bit overloaded. It is more of a data type field rather than a field that only describes vector data geometry. Should we change this field? Add another, more appropriate, field?

@KarenMajewicz and the Big10 Geoportal have done some user studies that revealed frustration with `layer_geometry_type_s`. As a result they added a Genre field and facet for this purpose.

https://github.com/OpenGeoMetadata/big-ten/blob/master/b1g_gbl_metadataschema.csv

**Comment by KarenMajewicz** [comment]
Here's some issues that came up during user testing and followup conversations:

- Image and Raster are not geometries
- "Image" is part of the [Dublin Core DCMI Type field controlled vocabulary](https://github.com/geoblacklight/geoblacklight/blob/master/schema/type-values.md), so the duplicated term can be confusing. Users also find the term "Image" very vague.
- The default GeoBlacklight behavior is to display these values in a facet called "Data Type," so the URI (`layer_geom_type_s`) does not really match the facet name.
- Many users asked for clarification on the term "Mixed," and did not find the term helpful. Why not make this a field that accepts multiple values (ex. `["Polygon","Point"]`? (although it would mess up the icon logic...)
- If an instance includes many scanned maps, this is not an intuitive/effective method for filtering between only scanned maps and GIS data.  Users wanted more of a toggle for maps vs data.

- Lastly, depending upon workflows, this value may be difficult to produce. Some institutions can automate the population of this value, but some projects need to manually determine it (like the Big Ten, but I think others have said they need to manually figure it out as well?).  A simpler, more general facet for designating the resource type (perhaps with associated icons) might be useful.

**Comment by eliotjordan** [comment]
Refs: #719

**Comment by karenmajewicz** [comment]
See new schema commentary that indicates this is now an optional field.
