### ISSUE TITLE
Missing category icons on home page

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#636]
![screenshot 2018-07-25 18 02 18](https://user-images.githubusercontent.com/784196/43232114-f872b7e2-9034-11e8-9092-c7b69a7a7464.png)

**Comment by jrgriffiniii** [comment]
Bootstrap 4 dropped Glyphicons: https://getbootstrap.com/docs/4.1/migration/#components

**Comment by mejackreed** [comment]
I'd be fine with not adding them back or having icons here.. other's thoughts? Who uses default homepage cc @andrewbattista

**Comment by ewlarson** [comment]
This feels like the place where if you really care about design, you'll go your own SVG icon way after adopting Geoblacklight regardless of what we choose here. I'd opt for not shipping icons, and have a "documented way" to support them baked into the app.

**Comment by jrgriffiniii** [comment]
Attempting to include [font-awesome-sass](https://rubygems.org/gems/font-awesome-sass) triggered strange errors in Solr, so I may explore integrating that into core when I have the opportunity to isolated precisely how it was broken.

**Comment by mejackreed** [comment]
We could also roll them into geoblacklight-icons and create a few nice ones instead of adding another package.

**Comment by jrgriffiniii** [comment]
Using the existing [font-awesome-rails](https://rubygems.org/gems/font-awesome-rails) provides a temporarily solution:

![geoblacklight_issues_636_screenshot_1](https://user-images.githubusercontent.com/1443986/43278208-62af8ea2-90d8-11e8-8746-52cc5099d9fb.png)


Would these be acceptable for the time being (@andrewbattista in particular)?

**Comment by andrewbattista** [comment]
@jrgriffiniii - definitely! Thank you

**Comment by mejackreed** [comment]
Do we only need these 4 icons or are there others? I'd be hesitant to require a new dependency for 4 icons.

I'll volunteer to create the icons too

**Comment by jrgriffiniii** [comment]
There are no new dependencies introduced @mejackreed, I'm just using the existing dependency for `font-awesome-rails`: https://github.com/geoblacklight/geoblacklight/blob/master/geoblacklight.gemspec#L25
