### ISSUE TITLE
Search result formatting changes

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#639]
Search result formatting is different:

- Icons are on the left instead of right (we should flip back).
- Text is very large (see other font issue), which causes crowding in the search area.
- No sorting and per page buttons

![screenshot 2018-07-25 18 14 54](https://user-images.githubusercontent.com/784196/43232507-e4ca4cd0-9036-11e8-9ebe-c0031e5518ef.png)

Versus

![screenshot 2018-07-25 18 15 07](https://user-images.githubusercontent.com/784196/43232512-ea17bd08-9036-11e8-88e6-2d0180c7d036.png)

**Comment by ewlarson** [comment]
Fixed in PR #652
