### ISSUE TITLE
Convert icons and fonts to SVGs and publish these to geoblacklight-icons

### ISSUE THREAD

**Issue by jrgriffiniii** [geoblacklight/geoblacklight#649]
@mejackreed raised an excellent point in https://github.com/geoblacklight/geoblacklight/issues/636#issuecomment-408175560, where if GeoBlacklight is using a limited number of FontAwesome icons, perhaps `font-awesome-rails` should be removed as a Gem dependency (with the needed icons being migrated upstream to [geoblacklight-icons](https://github.com/geoblacklight/geoblacklight-icons))

**Comment by andrewbattista** [comment]
I agree with this. Not a bad idea to concentrate all the icons to one place and remove the external dependency

**Comment by mejackreed** [comment]
I think this was done in https://github.com/geoblacklight/geoblacklight/pull/840
