### ISSUE TITLE
Limit your search - Mobile limit/facet menu toggle alignment

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#656]
### Descriptive summary

GBL blacklight-7 branch. In the smallest view, the mobile hamburger menu for Limiting/Facets floats above the heading instead of right-side/alongside.

![screen shot 2018-07-27 at 10 17 57 am](https://user-images.githubusercontent.com/69827/43329588-6a6d193a-9186-11e8-9fbb-1e4b877efe01.png)

### Expected behavior

It should float/align to the right-hand side.

![screen shot 2018-07-27 at 10 18 49 am](https://user-images.githubusercontent.com/69827/43329627-886ee044-9186-11e8-84a0-d61a81512b29.png)

### Actual behavior

It wraps above the "Limit your search" heading. This is an upstream issue from BL7.

![screen shot 2018-07-27 at 10 18 14 am](https://user-images.githubusercontent.com/69827/43329646-9e992528-9186-11e8-802b-c1d2fc69370a.png)

**Comment by eliotjordan** [comment]
Closed by #667
