### ISSUE TITLE
Audit view partials

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#660]
Are we using all the existing view partials? We should check and remove partials that are no longer needed.

**Comment by ewlarson** [comment]
- [ ] _data_dictionary.html.erb
- [ ] _document_action.html.erb
- [ ] _document_split.html.erb
- [ ] _downloads.html.erb
- [ ] _downloads_primary.html.erb
- [ ] _downloads_secondary.html.erb
- [ ] _exports.html.erb
- [ ] _facet_tag_item.html.erb
- [ ] _facet_tag_layout.html.erb
- [ ] _facets.html.erb
- [ ] _header_icons.html.erb
- [ ] _home_text.html.erb
- [ ] _icon_facet.html.erb
- [ ] _index_split_default.html.erb
- [ ] _metadata.html.erb
- [ ] _relations_container.html.erb
- [ ] _search_form_no_navbar.html.erb
- [ ] _show_default.html.erb
- [ ] _show_default_attribute_table.html.erb
- [ ] _show_default_viewer_container.html.erb
- [ ] _show_default_viewer_information.html.erb
- [ ] _show_header_default.html.erb
- [ ] _show_tools.html.erb
- [ ] _upper_metadata.html.erb
- [ ] _web_services.html.erb
- [ ] _web_services_default.html.erb
- [ ] _web_services_wfs.html.erb
- [ ] _web_services_wms.html.erb

**Comment by ewlarson** [comment]
Closing this ticket as not much work was uncovered here. Opened #702 to resolve BL bug fix redundancy.
