### ISSUE TITLE
Audit (and, where necessary, update) the fixture Documents for geospatial metadata

### ISSUE THREAD

**Issue by jrgriffiniii** [geoblacklight/geoblacklight#666]
There are currently metadata URL's which fail to resolve:

https://opengeometadata.github.io/edu.umn/08/32/9e/9637794cea9fa85d9939b6276f/iso19139.xml

(Which is found in https://github.com/geoblacklight/geoblacklight/blob/master/spec/fixtures/solr_documents/umn_state_result1.json)

@KarenMajewicz reports that these are likely out of date.

**Comment by KarenMajewicz** [comment]
I will look into replacing the fixture docs from Minnesota.  The current ones are from the Minnesota Geospatial Commons, which has had some turnover.  Is there a list anywhere of what attributes we are covering across the documents (metadata type, service type, etc.)?

**Comment by KarenMajewicz** [comment]
[Working sheet here](https://docs.google.com/spreadsheets/d/1byQ_Bfmua1uBQwzdc2-kAN1UDeTyZdVhdVkz4ern60w/edit?usp=sharing)

**Comment by KarenMajewicz** [comment]
See pull request #697 

I updated more errors on all the records this afternoon and loaded them into our [development site for testing here.](https://geodev.btaa.org/?f[dct_isPartOf_sm][]=Fixture+Test) (Note: our dev portal is not currently set up for logging in to see restricted items nor for index maps right now).

Next steps?
