### ISSUE TITLE
disable jQuery animations when Rails.env = test

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#669]
There are some transient feature spec failures in Travis that might be helped by an approach used in Spotlight:

https://github.com/projectblacklight/spotlight/commit/462a400578a9880c455f0262e64736a2184ce898

**Comment by mejackreed** [comment]
Did this help w/ the flapyness of the travis build?

**Comment by jrgriffiniii** [comment]
This did not seem to improve the problems with Travis testing, as rebasing in https://github.com/jrgriffiniii/geoblacklight/blob/issues-642-jrgriffiniii-restore-ws-modal/lib/generators/geoblacklight/install_generator.rb#L72 only led to https://travis-ci.org/geoblacklight/geoblacklight/builds/410457683
