### ISSUE TITLE
Change specs that access external services to mocks.

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#67]
It isn't advisable to have these tests run against external services. We probably need to modify this to use something like webmocks.

See: http://robots.thoughtbot.com/how-to-stub-external-services-in-tests

and

https://github.com/bblimke/webmock

**Comment by jrgriffiniii** [comment]
I would propose that the priority of this please be reconsidered - I'm seeing that there are failing tests which might be related to this on https://circleci.com/gh/geoblacklight/geoblacklight/900 (https://github.com/geoblacklight/geoblacklight/blob/master/spec/features/esri_viewer_spec.rb#L12 references https://github.com/geoblacklight/geoblacklight/blob/cd53af868eec18bbd1403ab3d4047dbab0764b1d/spec/fixtures/solr_documents/esri-dynamic-layer-all-layers.json#L21)

**Comment by eliotjordan** [comment]
@mejackreed Is this still an issue?

**Comment by mejackreed** [comment]
I'd say lets close and reopen if we need to
