### ISSUE TITLE
Develop method for displaying attribute table definitions/codebooks within metadata preview

### ISSUE THREAD

**Issue by karenmajewicz** [geoblacklight/geoblacklight#670]
### Descriptive summary

User tests demonstrated that users would like to inspect attribute table definitions/codebooks from within the interface. However, attribute table definitions are provided in a variety of formats - FGDC uses the Entities and Attributes section, ISO has a separate (but rarely used) 19110 specification, and many codebooks are simply charts or lists in HTML or PDF.

A potential solution would be to add a generic data dictionary key to `dct_references_s `that was agnostic about the format/standard.  The attribute table/codebook file would then appear as a tab in the metadata preview box.

A possible URI: Project Open Data has a Described By field: https://project-open-data.cio.gov/v1.1/schema/#dataset-describedBy

### Related work
- There is already support for zipped codebook downloads (#461 ).
- Issue #590 offers an improved view of the Entities & Attributes section of FGDC by formatting the values in a table
- Issue #602 outlines the steps for adding a key for ISO 19110 in XML.

Depends on #340

**Comment by KarenMajewicz** [comment]
URI: https://project-open-data.cio.gov/v1.1/schema/#dataset-describedBy
File format: native HTML
Tab name: Attributes

**Comment by KarenMajewicz** [comment]
Freezing for future discussions
