### ISSUE TITLE
Reevaluate testing and integration for JavaScript

### ISSUE THREAD

**Issue by jrgriffiniii** [geoblacklight/geoblacklight#680]
[Teaspoon](https://rubygems.org/gems/teaspoon/) is currently the Gem which is used for testing JavaScript, and this appears to have had waning maintenance: https://github.com/jejacks0n/teaspoon/pull/513

~Should a path towards integrating [Jasmine](https://jasmine.github.io/) be explored?  Rails 5.1 releases have used [Webpacker](https://github.com/rails/webpacker) (which would provide support for ES6 and [Jest](https://jestjs.io/)).  Perhaps these might be possible as well.~

Webpack is now supported using the `webpacker` Gem as of the merging of https://github.com/geoblacklight/geoblacklight/pull/729. However, Teaspoon now *must* be removed as a priority item given that it blocks support for Rails 6.y.z releases (please see the RubyGems page for the Gem linked above).

**Comment by jrgriffiniii** [comment]
After discussing this with @KarenMajewicz @ewlarson @hudajkhan @christinach and @eliotjordan , it was decided that attempting to support [Webpacker](https://github.com/rails/webpacker) in a future 2.x release would be a reasonable first step.

**Comment by jrgriffiniii** [comment]
https://github.com/jrgriffiniii/geoblacklight/tree/issues-680-jrgriffiniii-webpacker addresses the initial steps towards Webpacker integration, but I can see about migrating some simple JS functionality for feature testing with this new approach.

**Comment by jrgriffiniii** [comment]
74e118e worked for me locally, but I'm still working to debug this on CircleCI: https://circleci.com/gh/jrgriffiniii/geoblacklight/135

**Comment by jrgriffiniii** [comment]
783d2a6 fixed a problem I couldn't otherwise work-around with using Webpack to compile the manifest before testing on CI.  I'll need to squash my commits and review the documentation before issuing a PR.

**Comment by jrgriffiniii** [comment]
This should be shifted in priority given that it will block #862

**Comment by jrgriffiniii** [comment]
There are several JavaScript testing frameworks worthy of consideration for this. Two popular solutions I could be interested in seeing explored are:

- [Mocha](https://mochajs.org/)/[Chai](https://www.chaijs.com/)
- [Jest](https://jestjs.io/)/[Chai](https://www.chaijs.com/)
- [Testing Library](https://testing-library.com/docs/dom-testing-library/intro)

I'm slightly biased towards using Jest (my experience is that this is well-maintained, popular, and easier to configure), but I am also intrigued by the possibility of a properly configured integration of the Testing Library.

**Comment by mejackreed** [comment]
I'm biased towards Jest as well and would be 👍 with that approach
