### ISSUE TITLE
HGL download spec failing intermittently in CI

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#687]
HGL download spec is still failing intermittently in CI, although it's not happening as often using Circle. This test should be refactored.

**Comment by jrgriffiniii** [comment]
I had this refactored as a request spec: https://github.com/geoblacklight/geoblacklight/pull/664/commits/b26768f2adba2ae37919b1bdb1b0cba75cd61ba9

Would this be sufficient?

**Comment by eliotjordan** [comment]
Perfect! What PR is this a part of? I'm going to assign it to you.

**Comment by jrgriffiniii** [comment]
https://github.com/geoblacklight/geoblacklight/pull/664 should be ready for review (I believe that coverage was increased).

**Comment by eliotjordan** [comment]
Closed by #664
