### ISSUE TITLE
Explore integrating BrowserStack testing

### ISSUE THREAD

**Issue by jrgriffiniii** [geoblacklight/geoblacklight#696]
[BrowserStack](https://www.browserstack.com/) provides a service which offers automated testing (in hosted, virtualized environments), primarily focused upon app. user interfaces.  This would provide us with the ability to automate functional testing (with the ability to generate screenshots) across operating system environments, using various web browsers: (please see https://www.browserstack.com/list-of-browsers-and-platforms?product=live)

Further, BrowserStack provides open source projects with possible free testing: https://www.browserstack.com/open-source?ref=pricing

Given the prominence and increasing popularity of GeoBlacklight, I suspect that we may be granted free open source access to this service should we apply.

**Comment by eliotjordan** [comment]
Wee need to add this logo:

![browserstack-logo 2x](https://user-images.githubusercontent.com/784196/43614155-d65e3f98-9677-11e8-8ecf-89f0746f91e0.png)

**Comment by eliotjordan** [comment]
We now have a license. Good until August 2, 2019. They will reevaluate at that time.
