### ISSUE TITLE
Ensure Carto basemaps have https in the URL

### ISSUE THREAD

**Issue by hudajkhan** [geoblacklight/geoblacklight#721]
### Descriptive summary

1.9.1: https://github.com/geoblacklight/geoblacklight/blob/269fdd96276027edab2888b62dbc2f0842ef55cc/app/assets/javascripts/geoblacklight/basemaps.js does not use https for some of the basemaps and this leads to mixed content messages

### Expected behavior
No warnings in browser related to mixed-content/http URLs

### Actual behavior
Warnings happen

### Steps to reproduce the behavior
Get the latest code and deploy and check the browser

**Comment by eliotjordan** [comment]
Closed by #747
