### ISSUE TITLE
Document how to install and use geoblacklight_sidecar_images gem

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#723]
Add section to wiki and blacklight tutorials about installing this plugin:

https://github.com/geoblacklight/geoblacklight_sidecar_images

**Comment by ewlarson** [comment]
Added [this wiki page](https://github.com/geoblacklight/geoblacklight/wiki/Adding-support-for-item-images) on GeoBlacklight Sidecar Images to our Customization section. Closing.
