### ISSUE TITLE
Make sure GBL are tutorials are current

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#724]

**Comment by andrewbattista** [comment]
This can be treated in tandem with #725

**Comment by ewlarson** [comment]
Merged @andrewbattista work on https://github.com/geoblacklight/geoblacklight.github.io/pull/94  into master. Those changes are live on https://geoblacklight.org/ now.

I think there is more work left here, so leaving this issue open.

**Comment by karenmajewicz** [comment]
https://geoblacklight.org/blog/category/tutorials/
