### ISSUE TITLE
Create a Vagrant File / SolrWrapper setup for the GeoBlacklight Master

### ISSUE THREAD

**Issue by andrewbattista** [geoblacklight/geoblacklight#725]
### Descriptive summary

In addition to needing to update documentation and infrastructure for the GeoBlacklight tutorial, we need to incorporate some of the new features, like Sidecar. However, it would also be nice to have the Vagrantfile, virtual box setup that @ewlarson did for NYU in the master branch, if it is feasible. Comments or questions welcome.

**Comment by mejackreed** [comment]
This was proposed and implemented upstream in Blacklight in https://github.com/projectblacklight/blacklight/commit/19e30d9b60a638b1da2e68dd6ab832339edfbabc#diff-0ea0f59747296e1ef5353a231572d7b8 

Though I don't think it has really been maintained since.

**Comment by andrewbattista** [comment]
Good to know. I guess it's one thing we can test out to see if it still works. Then, the question can become, do we want to weave this into the tutorial or not?

**Comment by andrewbattista** [comment]
@ewlarson - that seems like a great idea to me. Also, we could pair it with the documentation created to enable others to load and test a GeoBlacklight out of the box?

**Comment by mejackreed** [comment]
Not sure if this is helpful or not, but here is what I'm using to create the GeoBlacklight workshop vms setup: https://github.com/mejackreed/packer-templates/tree/geoblacklight

Checkout https://github.com/mejackreed/packer-templates/tree/geoblacklight/ubuntu-16.04.3

I'll need to update this later in the week once 2.0 gets 🚢 . Some requirements for the workshop vm's:
 - we can't rely on network connection so, automate updating and downloading everything offline into the vm
   - gems
   - solr_wrapper
   - system dependencies (java, rbenv, rubies) etc

**Comment by andrewbattista** [comment]
After some discussion, we deemed this out of scope for now and will instead stick with the Packer-templates setup and the instructions surrounding it that exists already. In otherwords, this issue is turning into #724
