### ISSUE TITLE
Blacklight 7.0.x updates yield a `uninitialized constant Blacklight::Utils error`

### ISSUE THREAD

**Issue by jrgriffiniii** [geoblacklight/geoblacklight#738]
### Descriptive summary

When generating a new GeoBlacklight application off of `master`, using release 7.0.1 of Blacklight generates the following `User` Model:

```
class User < ApplicationRecord

  if Blacklight::Utils.needs_attr_accessible?
    attr_accessible :email, :password, :password_confirmation
  end
  # Connects this user object to Blacklights Bookmarks.
  include Blacklight::User
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Method added by Blacklight; Blacklight uses #to_s on your
  # user class to get a user-displayable login/identifier for
  # the account.
  def to_s
    email
  end
end
```

Unfortunately, this appears to have been removed in https://github.com/projectblacklight/blacklight/pull/1707

Please see https://github.com/projectblacklight/blacklight/issues/2055#issue-398438464 for the work-around which I found to be effective.

**Comment by eliotjordan** [comment]
Doesn't appear to be an issue anymore. If we need to we can re-open.
