### ISSUE TITLE
Remove geoblacklight-icons dependency; localize SVG assets

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#751]
### Descriptive summary

For GBL 2.0, I propose we remove the geoblacklight-icons gem dependency and move its SVG icon assets into the parent geoblacklight repository.

With evergreen browser support for inline SVG icons, webfont iconography is less desirable. And, [basic support](https://github.com/projectblacklight/blacklight/blob/3a04827dfa46fc8dbfd582575bf96ff9b88255de/app/models/blacklight/icon.rb) and [use of SVG icons](https://github.com/projectblacklight/blacklight/blob/85ee2619c207cbc054e3792e7acd2f272c26a532/app/helpers/blacklight/icon_helper_behavior.rb) has [already been added to Blacklight](https://github.com/projectblacklight/blacklight/pull/1585).

### Related work

#649

**Comment by andrewbattista** [comment]
I think that #840 accomplishes this issue, right?

**Comment by mejackreed** [comment]
Yes, already completed.
