### ISSUE TITLE
Web service in umn_metro_result2 fixture is not working

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#753]
The ArcGIS Dynamic Map webservice in the umn_metro_result2 fixture does not appear to be running.

https://github.com/geoblacklight/geoblacklight/blob/master/spec/fixtures/solr_documents/umn_metro_result2.json

When viewing the record show page, no features are loaded on the preview map.

**Comment by ewlarson** [comment]
@karenmajewicz and I will troubleshoot.

**Comment by andrewbattista** [comment]
It's also okay to remove the fixture if it's not possible to resolve it =)

**Comment by karenmajewicz** [comment]
I'll look to replace ArcGIS Rest services in the fixtures. I will try to find ones that will remain stable over time, but this is unlikely.

**Comment by eliotjordan** [comment]
Closed by #770
