### ISSUE TITLE
Metadata preview modal formatting looks odd

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#766]
Formatting in the metadata preview is off. 

- There isn't space between the metadata tab links.
- The tab links used to be centered and have an indication when they are active
- View metadata is pulled right instead of left.

<img width="792" alt="screenshot 2019-01-31 11 13 14" src="https://user-images.githubusercontent.com/784196/52072036-d6e9d600-2549-11e9-8cfb-80475f5aac02.png">

**Comment by christinach** [comment]
![screen shot 2019-01-31 at 4 38 24 pm](https://user-images.githubusercontent.com/9905193/52087183-b6844080-2576-11e9-8ded-4c6dd019b38a.png)

**Comment by christinach** [comment]
![screen shot 2019-01-31 at 4 39 33 pm](https://user-images.githubusercontent.com/9905193/52087257-e16e9480-2576-11e9-8531-069f350bef28.png)
