### ISSUE TITLE
Adoption into existing Blacklight application

### ISSUE THREAD

**Issue by stevenvandervalk** [geoblacklight/geoblacklight#77]
Hi!

Responding to @mejackreed  call for collaborators, testers and documenters - the [Digital Library](https://dl.vecnet.org/) of the [VecNet](https://www.vecnet.org/) project is looking to adopt geoblacklight as much as possible. We were previously looking to add map related search via blacklight-maps and some front-end redesign but then geoblacklight appeared - looking awesome.   Is integration with an existing Blacklight application something that is possible or planned? 

Also as someone brand new to the entire GIS+Blacklight field I would love to help test the documentation to gain familiarity and if possible help out.

**Comment by mejackreed** [comment]
Closing for now, please reopen to discuss additional adoption issues in vecnet
