### ISSUE TITLE
Add a filter for Georeferenced and non-Georeferenced maps

### ISSUE THREAD

**Issue by christinach** [geoblacklight/geoblacklight#783]
For example: https://collections.leventhalmap.org/georeferencing

**Comment by andrewbattista** [comment]
This seems to be something that is handled at the level of making metadata (or it could be).

**Comment by karenmajewicz** [comment]
Yes, it looks like Leventhal has added a boolean field to their metadata: `georeferenced_bsi: true`

Someone could add a field like this and then add a custom facet for it?

**Comment by karenmajewicz** [comment]
Gather use cases on how institutions would like to handle this.

**Comment by karenmajewicz** [comment]
solved through Aardvark metadata schema
