### ISSUE TITLE
Waffle.io is deprecated

### ISSUE THREAD

**Issue by jrgriffiniii** [geoblacklight/geoblacklight#795]
Unfortunately, the Waffle.io project management service is no longer available: https://waffle.io/geoblacklight/geoblacklight

There are several options for proceeding with identifying a project/task management solution (GitHub Projects, ZenHub, and Trello all come to mind for me).  Does anyone have any thoughts or suggestions on how best to proceed before the next scheduled community sprint?

**Comment by mejackreed** [comment]
👍 to GitHub Project boards

**Comment by mejackreed** [comment]
👍 to GitHub Project boards

**Comment by andrewbattista** [comment]
Agreed! GitHub project boards works for me. As a car dealer once told me (while trying to upsell a ski rack), there's something to be said for integration

**Comment by andrewbattista** [comment]
Seems like we’re all in agreement here! Onward with GitHub project boards

**Comment by karenmajewicz** [comment]
I think Princeton was still using Waffle, but we have used the GitHub project boards for the past several sprints already: https://github.com/geoblacklight/geoblacklight/projects?query=is%3Aclosed
