### ISSUE TITLE
jQuery 3+ readmore-js 

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight#800]
### Descriptive summary

GBL 2.1+ / jQuery 3.4+ 

The readmore-js library included in vendor/assets is a jquery plugin, which requires jQuery < 2.0. New versions of readmore-js do not support jQuery, with the most recent versions of the readmore-js tool having gone to vanilla javascript.
https://github.com/jedfoster/Readmore.js/issues/177

So! If you update the version of jQuery used by GBL from 1.X to 3.X, the readmore feature will break.

### Steps to reproduce the behavior

1. In application.js change require jquery to require jquery3
1. Load http://localhost:3000/catalog/2eddde2f-c222-41ca-bd07-2fd74a21f4de
1. See readme fail

### Fix will be...

We'll want to drop the jquery plugin version of readmore and ship the most recent 3.0 version (beta-1 at this point). Then in modules/item.js we'll change the call from jquery plugin syntax to vanilla js.

From: 
`
  $('.truncate-abstract').readmore({
    maxHeight: 60
  });
`

To:
`
  new Readmore(
    '.truncate-abstract',
    {
      maxHeight: 60
    }
  );
`

### Related work

B1G Geoportal: https://github.com/BTAA-Geospatial-Data-Project/geoportal/issues/224

**Comment by andrewbattista** [comment]
Seems worthy and attainable for the upcoming sprint!
