### ISSUE TITLE
Update the Webpacker dependency to 4.x releases

### ISSUE THREAD

**Issue by jrgriffiniii** [geoblacklight/geoblacklight#804]
Updating to the latest versions of [Webpack](https://webpack.js.org/concepts) is supported in `webpacker` Gem 4.x releases. 
 (Please see https://github.com/rails/webpacker/blob/master/docs/v4-upgrade.md).  Also, please note that by updating `webpacker`, current versions of Babel are supported (for supporting ES6/7/* transpilation: https://www.npmjs.com/package/@rails/webpacker/v/4.0.0)

**Comment by jrgriffiniii** [comment]
https://github.com/geoblacklight/geoblacklight/compare/master...jrgriffiniii:issues-804-jrgriffiniii-webpacker4 gets everything upgraded without any real problems.  There will be some documentation needed in order to address how best to migrate configurations to Webpack 4.32: https://github.com/rails/webpacker/blob/master/package.json#L49

**Comment by ewlarson** [comment]
Closing as out of date.
