### ISSUE TITLE
Add the ability to configure display of carto and ArcGIS export links

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#810]
We want to display the "Open in ArcGIS" button, but not the the "Open in Carto" button. It would be nice to have this configurable instead of having to override the exports partial or the cartodb_reference method in the solr document.

**Comment by andrewbattista** [comment]
I agree. While it’s more complicated, it would be nice if users could set this as an option in the vein of how users select baselayers, as in the [catalog controller](https://github.com/geoblacklight/geoblacklight/blob/fce385acc9da59f4b94b7785d0595e72f9e99682/lib/generators/geoblacklight/templates/catalog_controller.rb#L261) file.

`    config.basemap_provider = 'positron'`
