### ISSUE TITLE
Acknowledge Blacklight 7-related changes to .json output

### ISSUE THREAD

**Issue by andrewbattista** [geoblacklight/geoblacklight#813]
### Descriptive summary

Evidently with the upgrade to Blacklight 7, the JSON output returns a nested schema that isn’t as operable for us. We should perhaps acknowledge this and think about making a page on the documentation wiki that explains how to return records as .json the old way (by adding /raw) at the end. 

### Related work

This also gestures at #811 perhaps

**Comment by karenmajewicz** [comment]
Was this ever documented on the Blacklight repo?

**Comment by andrewbattista** [comment]
I haven’t done a thorough search, but it appears that nothing has been said about it for a long time! -https://github.com/projectblacklight/blacklight/wiki/JSON-API perhaps @mejackreed @tampakis or someone more familiar with Blacklight proper would know. If not, this seems like a chance to contribute to two wikis!

**Comment by andrewbattista** [comment]
I realize this change was already somewhat acknowledged on the upgrade guide on the wiki. I added some clarifying text there, but we plan to build out more documentation on the metadata guide on the wiki. I think we can close this for now if others are okay.

**Comment by karenmajewicz** [comment]
Added more info on the Wiki here: https://github.com/geoblacklight/geoblacklight/wiki/GeoBlacklight-Metadata#viewing-metadata

**Comment by andrewbattista** [comment]
Awesome! This is great, and I think we can close this issue now =)
