### ISSUE TITLE
Add basic instructions on how to launch local GBL with fixtures

### ISSUE THREAD

**Issue by andrewbattista** [geoblacklight/geoblacklight#814]
### Descriptive summary

I might be doing something wrong, but in following the instructions for launching a new GeoBlacklight, I am able to get the rails server going and get a local GeoBlacklight running, but it doesn’t have any fixture records in it. Better instructions on what to do here would be good and should be documented somewhere

**Comment by andrewbattista** [comment]
As an update, I added instructions on the readMe, which I think is the important part, but after some convo, I intend to build out a bit of documentation on the wiki about development.

**Comment by karenmajewicz** [comment]
info added to wiki here: https://github.com/geoblacklight/geoblacklight/wiki/Development
