### ISSUE TITLE
Selenium warning

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#835]
When running specs this warning appears.

``` 
WARN Selenium [DEPRECATION] Selenium::WebDriver::Chrome#driver_path= is deprecated. Use Selenium::WebDriver::Chrome::Service#driver_path= instead.
```

**Comment by christinach** [comment]
When a new rails app is being created using rails 5 it will install by default chromedriver-helper. If the gem chromedriver-helper is removed from the internal test app Gemfile, the warning is not triggered. 
With the rails 6 release the Gemfile will install the gem webdrivers and not chromedriver-helper. 
I think that as long as we use rails 5 as a dependency we will see this warning.
(Using the 'rails600rc2 tag' to create a new app it does not install the gem chromedriver-helper, )

**Comment by eliotjordan** [comment]
I'll close this issue then. Not much we can do about it at this point. Thanks @christinach.
