### ISSUE TITLE
Remove the HGL bespoke download behavior

### ISSUE THREAD

**Issue by andrewbattista** [geoblacklight/geoblacklight#848]
### Descriptive summary

The master branch of GeoBlacklight includes variables, such as the `hgl_download` and related behavior that enables a custom "cart based" download request to happen. see [https://github.com/geoblacklight/geoblacklight/blob/edd984268d17fa8639590b92f8251eee03320914/spec/controllers/download_controller_spec.rb](https://github.com/geoblacklight/geoblacklight/blob/edd984268d17fa8639590b92f8251eee03320914/spec/controllers/download_controller_spec.rb)

### Expected behavior

We shouldn't have hard-coded variables or behavior that deviate from the way the schema is designed (ideally).

**Comment by mejackreed** [comment]
I'm not sure what the issue is here? `hgl_download` relates to a specific way that Harvard processes downloads.

**Comment by andrewbattista** [comment]
In the spirit of not making a change that would break or strand the way Harvard processes downloads, we can punt on this.

**Comment by karenmajewicz** [comment]
This is working again and actively in use.
