### ISSUE TITLE
Consider changing some metadata elements from required to optional

### ISSUE THREAD

**Issue by karenmajewicz** [geoblacklight/geoblacklight#855]
### Descriptive summary

The GeoBlacklight schema requires several elements that effectively restrict what kind of layers can be loaded into a GeoBlacklight application. Examples of records that someone might want to add to GeoBlacklight without adding a value for a required element include:

- Scanned map without bounding box coordinates (no solr_geom)
- Collection level record describing a group or subject (potentially no layer_geom_type_s, solr_geom, or provenance) 
- Collective record held by multiple institutions (multiple provenances)
- Resource held by external organization (no institutional or obvious provenance)

---------------------------------------

Additionally, there is a slight discrepancy between the required elements in the schema documentation as opposed to what is actually necessary to load into the application. This table shows the affected elements (at least as configured for the BTAA geoportal - please update if these are incorrect for default GeoBlacklight):

| element name | required by schema documentation | required for loading into application | tied to icon  display |
| -------------- | ------------------------------------ | ----------------------------------- | ------ |
dc_identifier_s | X | X |
dc_rights_s | X | X | X |
dc_title_s | X | X |
dct_provenance_s | X | X | X |
geoblacklight_version | X | |
layer_slug_s | X | X |
solr_geom | X | ? |
layer_geom_type_s | | X | X |

### Proposed Changes
This ticket proposes that we consider releasing the requirement for the following elements to facilitate more flexible records:
- [x] dct_provenance_s
- [x] solr_geom
- [x] layer_geom_type_s

Perhaps we could add another level to the schema beyond **Required** & **Optional** to indicate that these values are "**Strongly Recommended**"?

### Related work

Link to related tickets or prior related work here.

#628 (geometry type is still causing browser error for BTAA; anyone else?)

**Comment by karenmajewicz** [comment]
Some investigations:

Omitting Provenance: the record loads to Solr, but the page does not display in the application. A workaround is including the field in the record and setting the value to a space. 

Omitting Geometry Type: the records loads to Solr and a direct link to the page works. However, faceted search pages that include the record will return a 500 error.

Omitting Solr Geom (bounding box): this seems to work fine in the BTAA geoportal. Does it work for others?

**Comment by karenmajewicz** [comment]
[testRecords.zip](https://github.com/geoblacklight/geoblacklight/files/4105331/testRecords.zip)

@ewlarson Here are 3 records to use for testing.

**Comment by ewlarson** [comment]
Running your test docs using GeoBlacklight#master. Here's what I'm seeing:

### No Solr Geom
Mostly this just seems to work, with the caveat any map-based query will exclude these documents from a bounding-box-scoped search.

Also, clicking on a result item to view the show page creates a JS error: "Uncaught Invalid bounding box string"

https://github.com/geoblacklight/geoblacklight/blob/1baabea3909c507624914c223657047f43b47060/app/assets/javascripts/geoblacklight/geoblacklight.js#L8-L20

![no_solr_geom_js_error](https://user-images.githubusercontent.com/69827/73024571-76574700-3df3-11ea-8862-836ef075c1c9.gif)

#### Possible resolution

We'll need to adjust the event handler here to not expect every result to have a bbox.

----

### Omitting Provenance

Show action does not display. Record errs calling BL's "fetch" method in this GBL function:

https://github.com/geoblacklight/geoblacklight/blob/master/app/models/concerns/geoblacklight/solr_document.rb#L47-L49

<img width="1280" alt="Screen Shot 2020-01-23 at 3 16 27 PM" src="https://user-images.githubusercontent.com/69827/73024558-6f303900-3df3-11ea-824a-84cee1b1942e.png">

#### Possible resolution

Wrap the GBL same_institution? method to check the doc for provenance.

----

### Omitting Geometry Type

I'm not seeing anything wrong here. Doc works in GeoBlacklight. Perhaps a Geoportal customization is causing this document to fail there?

![omitting_geom_type](https://user-images.githubusercontent.com/69827/73025593-7d7f5480-3df5-11ea-84ae-61d98f095e14.gif)

----

I'll start working on fixes for the first two scenarios here.

**Comment by ewlarson** [comment]
@karenmajewicz The code side of this issue is now resolved in my branch. Once this is merged, we'll need to update our schema documentation accordingly.

**Comment by karenmajewicz** [comment]
Updated chart [in progress]


element name | required by schema documentation | errors if missing | tied to app behavior
-- | -- | -- | --
dc_identifier_s | X |   |  
dc_rights_s | X | record will not display| icon and layer access
dc_title_s | X |   |  if missing, slug will display as title
dct_provenance_s | X | [requirement removed in PR #871 ]  | icon
geoblacklight_version | X |   |  
layer_slug_s | X | will not load to Solr (assuming it is configured as key) |solr key and item slug
solr_geom | X |  |spatial index, bbox display  
layer_geom_type_s |   | [js errors fixed in PR #871]   | icon
