### ISSUE TITLE
Add support for ISO 19115

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#856]
### Descriptive summary

Add support for viewing and referencing ISO 19115 metadata.

Also make sure to update docs

**Comment by karenmajewicz** [comment]
Adding the Icebox tag to this - after investigating, we found that current users don't need this and the ISO 19115-3 standard is not widely used yet.

**Comment by akuckartz** [comment]
> Geographic information -- Metadata -- Part 1: Fundamentals (ISO 19115) is the basis for the metadata profile in INSPIRE
https://inspire-reference.jrc.ec.europa.eu/vocabularies/geospatial-standards/iso-19115
