### ISSUE TITLE
Investigate Rails 6 support

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#862]

**Comment by jrgriffiniii** [comment]
`teaspoon` can no longer be supported if we are to upgrade support for Rails 6.0.z releases:

```
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    rails (= 6.0.2.1) was resolved to 6.0.2.1, which depends on
      railties (= 6.0.2.1)

    teaspoon was resolved to 1.1.4, which depends on
      railties (< 5, >= 3.2.5)
```

The last release of `teaspoon` was in 2016, and does not support Rails 6.y.z releases: https://rubygems.org/gems/teaspoon

**Comment by mejackreed** [comment]
Seems perhaps worthwhile to look at migrating JavaScript tests as a first step then?

**Comment by jrgriffiniii** [comment]
Yes, certainly, I just wanted to progress a bit with this issue by documenting what needed to be addressed to get the Rails/Ruby tests passing first (there are a number of deprecation warnings and some issues due to the changes in the Controller structure).

**Comment by jrgriffiniii** [comment]
Upgrading `rspec-rails` to the `4.0.0.beta4` release triggered the following errors:

```
# NoMethodError:                                                                                                                                                                        [205/5063]
     #   undefined method `aggregations' for #<ActionDispatch::Response:0x00007f94d495b378>
     #   /.../.rvm/gems/ruby-2.5.7@bundler2/gems/blacklight-7.5.0/app/controllers/concerns/blacklight/facet.rb:46:in `facet_by_field_name'
```

Downgrading this to `4.0.0.beta2` (in order to match https://github.com/projectblacklight/blacklight/blob/master/blacklight.gemspec#L35) seems to have resolved this issue, but I suspect that it might affect Blacklight upstream.

**Comment by jrgriffiniii** [comment]
https://github.com/geoblacklight/geoblacklight/commit/ec5043aa18e836177b5d69b3a8d3e3750c6b18f2 resolved the JavaScript-related failures which I was experiencing for the functional Selenium test suites.

**Comment by jrgriffiniii** [comment]
https://circleci.com/workflow-run/2a5d4261-300e-4338-a740-84c4a08b2875 looks pretty promising for the Rails testing from changes introduced on https://github.com/geoblacklight/geoblacklight/compare/master...jrgriffiniii:issues-862-jrgriffiniii-rails-6. I still need to resolve some Rubocop and code coverage configuration errors.

I apologize, the need to completely rewrite JavaScript testing without Teaspoon is going to block me from completing this before the conclusion of the current sprint.

**Comment by mejackreed** [comment]
> the need to completely rewrite JavaScript testing without Teaspoon is going to block me from completing this before the conclusion of the current sprint.

We could perhaps separate this task as a separate piece of work that maybe someone else could tackle?

**Comment by jrgriffiniii** [comment]
I'm going to please propose that https://github.com/geoblacklight/geoblacklight/issues/680 be repurposed for this.

**Comment by mejackreed** [comment]
FWIW, Rails 6.0 and Rails 6.1 are now supported in GeoBlacklight.
