### ISSUE TITLE
Support Ruby 2.7.z releases

### ISSUE THREAD

**Issue by jrgriffiniii** [geoblacklight/geoblacklight#878]
https://github.com/projectblacklight/blacklight/pull/2226/commits/02c70cabdc2ebc50479e8a7b02217a606d98fe8c resolves this upstream in Blacklight, but this has not yet been released: https://rubygems.org/gems/blacklight

**Comment by ewlarson** [comment]
Closing. Ruby 2.7.1 is in our test matrix.
