### ISSUE TITLE
Map zoom issue

### ISSUE THREAD

**Issue by pdante-ubc** [geoblacklight/geoblacklight#886]
When I am on the homepage, if I zoom into somewhere on the map and then click "Search here", the map displayed on the results page is either slightly zoomed out if I'm using a PC or it is centered on a completely different location if I'm on a Mac. 
<img width="742" alt="Screen Shot 2020-02-07 at 1 01 19 PM" src="https://user-images.githubusercontent.com/46582128/74286019-d7c85280-4cdb-11ea-8446-bb363b010601.png"> 

**Transitions from the North America view to a Eurasia/Africa/Australia view when using a Mac**

<img width="721" alt="Screen Shot 2020-02-07 at 1 01 32 PM" src="https://user-images.githubusercontent.com/46582128/74286827-786b4200-4cdd-11ea-92be-29e5e12355f3.png">

The listed results seem to be correct in that they are based on the map location I chose on the starting page rather than based on the new map location.

### Expected behavior
Map displayed in the search results will be the same as the map displayed on the starting search page.
### Actual behavior
Map displayed in the search results is different than the map displayed on the starting search page.
### Steps to reproduce the behavior
1. Zoom in on the map on the starting search location
2. Click "Search here"

### Related work

Link to related tickets or prior related work here.
Maybe #195

**Comment by frizatch** [comment]
##Tested Behavior on Mac running High Sierra on Chrome and Safari on geo.colorado.edu

1. Zoomed map to location
2. Clicked "Search here"

I was unable to reproduce the behavior of jumping to the wrong part of the map in either browser.

The map DID zoom out to a view beyond the search area, but I suspect this may be purposeful as the map element displays have different aspect ratios?

##Safari test:
![MapSearchAreaTest_Safari](https://user-images.githubusercontent.com/20845777/74379535-36a5ce80-4da5-11ea-857f-7a8dc74f6fec.gif)

##Chrome test:
![MapSearchAreaTest_ChromeClose](https://user-images.githubusercontent.com/20845777/74379554-402f3680-4da5-11ea-889b-6b1973b297a1.gif)

**Comment by pdante-ubc** [comment]
We were able to reproduce it on several, but not all, devices during the last community call (Feb 12th).

**Comment by pdante-ubc** [comment]
The Bounding Box tag shows (177.890625 4.565474 2.460938 80.928426) for the NA to Asia jump, which is a bounding box for Eurasia. But they are not always exactly the same.

Here are some of the geoblacklight records that are showing up in the list alongside the map of Eurasia:

[geoblacklight.json (example 3).txt](https://github.com/geoblacklight/geoblacklight/files/4320298/geoblacklight.json.example.3.txt)
[geoblacklight.json (example 4).txt](https://github.com/geoblacklight/geoblacklight/files/4320299/geoblacklight.json.example.4.txt)
[geoblacklight.json (example 5).txt](https://github.com/geoblacklight/geoblacklight/files/4320300/geoblacklight.json.example.5.txt)
[geoblacklight.json (example 1).txt](https://github.com/geoblacklight/geoblacklight/files/4320302/geoblacklight.json.example.1.txt)
[geoblacklight.json (example 2).txt](https://github.com/geoblacklight/geoblacklight/files/4320303/geoblacklight.json.example.2.txt)

**Comment by ewlarson** [comment]
Hi Paul (@pdante-ubc) I'm walking thru the GeoBlacklight issue board here. Is this problem still relevant?

**Comment by pdante-ubc** [comment]
I haven't touched this issue nor had anyone mention to me that they have, so I'm assuming it has not been fixed. I don't have a Mac, so I can't test the jumping to a new location part of the issue. The slight zoom out on a PC is still happening on our site, but we haven't pulled in any GBL updates recently and it may just be what @frizatch said about aspect ratios.

**Comment by andrewbattista** [comment]
@pdante-ubc Can you confirm that the records you have in your live instance are current with what's in opengeometadata? https://github.com/OpenGeoMetadata/ca.frdr.geodisy  If so, we may try to replicate by indexing them all and seeing if there is a record gone awry.

**Comment by pdante-ubc** [comment]
We are in the transition process of switching our source for metadata, so the files in OGM are not exactly what we have on our site at the moment, but they should be the records we were using when the issue was found.

**Comment by eliotjordan** [comment]
We decided at the 2/23/2022 Sprint standup that we are going to discuss this at an upcoming community meeting.
@karenmajewicz - For your records.

**Comment by karenmajewicz** [comment]
Requires more research and verifying that this is still an issue.
