### ISSUE TITLE
Blacklight 7.8 release breaks Geoblacklight deployment

### ISSUE THREAD

**Issue by mbstacy** [geoblacklight/geoblacklight#895]
### Descriptive summary

New blacklight version 7.8(released 05.21.2020) breaks [installation instructions](https://github.com/geoblacklight/geoblacklight#installation) 

### Expected behavior

Geoblackight deployment works on local system.

### Actual behavior

Geoblacklight produces error:

```
 .../gems/blacklight-7.8.0/app/views/catalog/_constraints.html.erb
undefined method `to_unsafe_h' for #<Blacklight::SearchState:0x00007fd736431998>
 ...
localized_params = localized_params.to_unsafe_h unless localized_params.is_a?(Hash)
 ...
```

### Steps to reproduce the behavior

1. Follow instructions https://github.com/geoblacklight/geoblacklight#installation

Rolled back to blacklight 7.7 and everything works.

**Comment by mbstacy** [comment]
I'm not sure if this is a geoblacklight issue or a Blacklight issue!

**Comment by mejackreed** [comment]
@mbstacy can you see if 7.8.1 resolves the issue for you?
