### ISSUE TITLE
Update EPSG code used for WMS and KMZ?

### ISSUE THREAD

**Issue by Wiscmapper** [geoblacklight/geoblacklight#897]
It feels like the EPSG code used in GeoBlacklight could be updated to the more recent, official code of 3857.  Functionally, I doubt it matters.  But I ran into some issues recently where the service I was attempting to reach balked at the 900913 CRS request.

https://github.com/geoblacklight/geoblacklight/blob/ad1ef63684f076bb249ad71963ab5737b58d5b64/app/assets/javascripts/geoblacklight/viewers/wms.js#L26

https://github.com/geoblacklight/geoblacklight/blob/f9f1cd4b13f0cc1344230d8d3b7efb2a489714f2/lib/geoblacklight/download/kmz_download.rb#L6

... change from EPSG:900913 to EPSG:3857

References:
https://epsg.io/900913
https://wiki.openstreetmap.org/wiki/EPSG:3857

**Comment by mejackreed** [comment]
Do you have some examples of services that had issues with these?

I believe we used these legacy ones to support tiling services for those who haven't yet updated. Happy to rethink this though with some examples of services and how they respond with caching.

**Comment by Wiscmapper** [comment]
Thanks Jack.  Here is an example of a service that we couldn't get to work with GeoBlacklight because requests are made in 900913 instead of 3857:

https://realearth.ssec.wisc.edu/cgi-bin/mapserv?map=NAIPWI.map&request=GetCapabilities&service=WMS&version=1.3

**Comment by andrewbattista** [comment]
Without knowing much about this, would making this CRS change "break" existing layers that have been indexed by adopters?

**Comment by hudajkhan** [comment]
I reviewed this by overriding the same files using a commit version of GeoBlacklight from about a week ago (I'm having trouble getting the app to run with the most recent code).  That said, I can see the changed protocol values being sent over in the JavaScript and the WMS preview works correctly.  The app setup I'm using to test doesn't usually allow GeoServer downloads through the interface, but I can see the correct value being passed in the rails logs for the KMZ download step.  When I do try the direct url for GeoServer download with the changed EPSG code, that works fine.

**Comment by karenmajewicz** [comment]
@frizatch @hudajkhan I am tidying up the summer sprint board - can we close this issue?

**Comment by hudajkhan** [comment]
Yes we can! :)

**Comment by frizatch** [comment]
Yep yep!

In my futzing it got changed to #967.
