### ISSUE TITLE
Improve CircleCI build time

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#905]
This might be a factor of the plan we have, but one build will take > 30min. Because we run 2 different versions of Rails + multiple Rubies + rubocoping. 8 x builds. I propose we look into:
 - getting a different plan somehow
 - reducing the builds or short circuiting
 - get them parallelized
 - switch back to travis

Open to alternative suggestions here, but > 30min to a run a test suite that takes 6min seems too much.

**Comment by andrewbattista** [comment]
Is the main question here, do we move back to Travis? If so, would that be the pathway to resolving these excessive build times?

**Comment by eliotjordan** [comment]
I sent a message to CircleCI support about this. If they aren't able to help, then we'll have to pursue other options such as switching back to Travis.

The message I sent:

```
Hi there. I am interested in enrolling an open source project that I'm a committer on into the open source projects program: https://circleci.com/open-source/

The project and organization is called GeoBlacklight:
https://github.com/geoblacklight/geoblacklight
https://geoblacklight.org/

We've been using CircleCI for some time now, but we are coming close to our allotted 2,500 credits for the month and could benefit from additional parallel builds.

Thanks for your help.
```

**Comment by eliotjordan** [comment]
Also, reducing the number of rubocop runs would help to some extent. I don't think rubocop needs to be run on every version of ruby.
