### ISSUE TITLE
Add label customization to data relations widget

### ISSUE THREAD

**Issue by ggeisler** [geoblacklight/geoblacklight#906]
In a current Earthworks workcycle at Stanford, we're hoping to add more information to item show pages to inform the user about how a given item is related to other items. If I understand correctly (I'm new to GeoBlacklight), there is a Data Relations widget that can be used to highlight item relationships. This widget provides a nice way to show item relationships, but it seems potentially useful if implementers were able to customize the label of the Data Relations widget based on different types of item relationships.

For example, in the two existing implementations that I've come across, the Data Relations box essentially uses two headings to describe the item relationship:

In these examples ([first](https://geo.nyu.edu/catalog/nyu-2451-40736) and [second](https://geo.nyu.edu/catalog/nyu-2451-38716)) from NYU, the box has a label of "Data Relations" and the list of related items a label of "Source Datasets" or "Derived Datasets":

<img width="785" alt="Screen Shot 2020-06-23 at 11 57 47 AM" src="https://user-images.githubusercontent.com/101482/85446135-f9b6c900-b548-11ea-8b9e-3069af075800.png">

In these examples ([first](https://maps.princeton.edu/catalog/princeton-n009w382v) and [second](https://maps.princeton.edu/catalog/princeton-1r66j405w)) from Princeton, the box has a label of "Relationships" and the list of related items a label of "Parent Records" or "Child Records":

<img width="810" alt="Screen Shot 2020-06-23 at 11 56 44 AM" src="https://user-images.githubusercontent.com/101482/85446419-469a9f80-b549-11ea-9a2c-c50dca254bba.png">

What we'd like to do is make the box label more specific to the type of relationship in play, which would enable us to eliminate the second label and provide the user with a more clear indication of the relationship type in the box label itself. Here are some examples of what we'd like to be able to do:

### Parent/child relationships

<img width="892" alt="Screen Shot 2020-06-23 at 12 06 34 PM" src="https://user-images.githubusercontent.com/101482/85447033-01c33880-b54a-11ea-9c86-ece56a5ef918.png">

### Version relationships

<img width="991" alt="Screen Shot 2020-06-23 at 11 41 07 AM" src="https://user-images.githubusercontent.com/101482/85447200-2e775000-b54a-11ea-93ec-fb3f4f8c007f.png">

### Series relationships

<img width="991" alt="Screen Shot 2020-06-23 at 11 41 38 AM" src="https://user-images.githubusercontent.com/101482/85447239-3e8f2f80-b54a-11ea-96a2-555d302ce85c.png">

---

I'm posting this ticket here rather than in the Earthworks repo in case this functionality seems useful to GeoBlacklight implementers beyond Stanford.

**Comment by andrewbattista** [comment]
+1 on this idea and work. Although we've had many discussions about expanding the scope of relationship types, it seems like the best course forward would be to implement something like the D-CAT relationship type short ontology to allow for a more robust representation of relationship types. Another might be to create our own (even shorter) set of relationship types that better match what we are looking for and then make the string values for what those relationships say in GeoBlacklight internationalized.

**Comment by jkeck** [comment]
@ggeisler it seems like it may be possible for an item to be both in a collection, and have items (at least in theory).  Should that then be separated out into separate "boxes" in the sidebar?  I imagine we may also find ourselves where an item in a collection has version or series relationships.  Will these be in a separate "box" if these relationships co-exist in the same record?

**Comment by ggeisler** [comment]
@jkeck Yeah, I'd say we stick to the distinct box types, and if a given item matches multiple box types, each of those is displayed.

**Comment by jkeck** [comment]
Okay, so just to be clear, currently both the ancestors/collections and the descendants/items share the same "Data relations" box. The ask here is to split them out into their own?

**Comment by ggeisler** [comment]
> The ask here is to split them out into their own?

@jkeck Definitely speak up more strongly if you see a problem with that approach, but that makes sense to me.

So on an item show page that is part of a larger collection, and is a collection with children itself, there would be two data relations boxes:

```
|-----------------
| Collection items
|-----------------
| item 1
| item 2
| item 3   
| 
| Show all 10 items 
|-----------------

|-----------------
| Item belongs to a collection
|-----------------
| Collection title
|
| 23 items in this collection 
|-----------------
```

And a similar rendering if the item was, say, part of a collection and also a version of another item. Of course for this to work we need to customize the box labels as noted earlier in the ticket (I wouldn't suggest this approach if all the boxes had to have the same "Data Relations" label). But I assume that is part of what you are working on.

**Comment by jkeck** [comment]
I agree, that makes sense.  One thing that came up during our pairing is that getting the count of the items in the collection (from the item page) would require an additional solr request, so we've punted on that piece for now (and simply added a link w/o the count to see all the items).  This is all in draft, but we'll split out issue for anything that we weren't able to get to on the initial pass.

**Comment by ggeisler** [comment]
>  so we've punted on that piece for now (and simply added a link w/o the count to see all the items)

Just double-checking, because I realized "added a link w/o the count to see all the items" could mean two things (linking a modified count message, or linking the collection title). If you don't show the item count, then I assume you're just showing the collection title, which is linked:

```
|-----------------
| Item belongs to a collection
|-----------------
| Collection title
|-----------------
```

Or if it belonged to two collections:

```
|-----------------
| Item belongs to a collection
|-----------------
| Collection title
|
| Another collection title
|-----------------
```

In other words, if we can't show the item count, we don't want to show that message under the collection title, since we'd end up with two links pointing to the same thing (the collection item). Might be what you already are doing but I realized  that although my mockups are accurate, it could be confusing because the message string at the bottom of the box **is** a link in some of the other scenarios (Series, Collection items).

**Comment by jkeck** [comment]
In the final example on #913

## nyu_2451_34502 (after)
![nyu_2451_34502 (after)](https://user-images.githubusercontent.com/96776/85907684-2546e700-b7c7-11ea-85cc-e271aaa7a0b8.png)

There are two `Browse all records ...` links that link to results of all the items.  I can strike that link, since it was probably only intended to be text,  and we'll just link to the collections.

**Comment by jkeck** [comment]
Updated screenshot: 
<img width="279" alt="nyu_2451_34502-after" src="https://user-images.githubusercontent.com/96776/85908762-50333a00-b7cb-11ea-8bfa-a8dedcce7fc4.png">

**Comment by ggeisler** [comment]
Yeah that's what I had in mind. The other approach certainly is a valid option (assuming the Browse all link goes to the search results of all records rather than the collection item show page) but it seems like if we have a collection record, we want the user to see that first (since it could have more context with collection level metadata) and if they want to see all the collection records they could do it from that page's Items in this collection box.

It's an extra click to get to all of the records with that option, but the two-link version is more ambiguous (why are both things in this box links?). The "Browse all" link will probably attract more attention and then the user will miss the existence of the collection record. But maybe we can evaluate the options better when the other pieces (box label, collection icon) are in place.

**Comment by andrewbattista** [comment]
On this issue, see #888 and #547 - Ideally the UI would respond to the type of relationship as declared somewhere in the GeoBlacklight schema metadata

**Comment by mejackreed** [comment]
Discussed on standup 08/13/2020 we think this is likely done with work on this.
