### ISSUE TITLE
Add support for collection show pages

### ISSUE THREAD

**Issue by ggeisler** [geoblacklight/geoblacklight#908]
As part of a current Earthworks workcycle at Stanford, we're considering adding collection items to Earthworks. As best I can tell, GeoBlacklight currently supports a Collection facet, but selecting a given collection leads to a search result page with the collection items. Ideally, if a collection has an indexed record with collection-level metadata, it should instead lead to a collection show page so the user can get a more detailed view of the collection itself.

This proposal wouldn't affect the current behavior of collections that don't have a specific indexed record; selecting one of those collections would lead to a search results page as it does now.

If, however, there is an indexed record for a collection, it would instead lead to a show page. At least to start, this could (I guess?) be the same view template as the current item show page. So something like:

<img width="1094" alt="Screen Shot 2020-06-23 at 4 09 40 PM" src="https://user-images.githubusercontent.com/101482/85476074-44960800-b56c-11ea-906f-7a1a977d111a.png">

---

- **A**: Use a collection-specific icon to distinguish the collection type page. I'm not sure if this is complicated by the fact that "collection" isn't really a data format the way the other item pages are? In any case, if we can do it, I suggest using the FA `archive` icon  (unless someone can think of a better icon to represent "collection"):

https://fontawesome.com/icons/archive?style=solid

- **B**: I think we'd only show this collection show page if the collection has some metadata. So whatever collection-level metadata there is would follow the title, as on the existing item show page.

- **C**: A collection should have items that we know about and can display using the Data Relations widget. There are some other relevant suggestions around that in #907 and #906. But the general idea is that for a collection, the Data Relations widget would use "Collection items" as the box label and list up to 3 collection items, which are linked to their item show page. 

- **D**: If there are more than 3 items in the collection, provide a link to the search results page for the collection that lists all collection items. I'm not sure if the Data Relations widget currently supports customizing this label; the only example I see is in an NYU example where the label is "Browse all 33 records...". For Earthworks, I think we'd prefer to use "Show all 33 items" as the label (for consistency with how we refer to things in other SUL applications).

**Comment by mejackreed** [comment]
Just adding a few comments here on the individual pieces:

**A**: This can already be accomplished by an adopter by adding the icon locally.  Seems like a good thing to do adding here upstream in GeoBlacklight. Caveat, the "collection" will need to be indexed with `layer_geom_type_s` as "Collection" but that seems reasonable given the other uses of that field.
**B**: ✅ The "collection" here is really just an indexed record, so if someone indexes the record, the show page will exist.
**C**: I think the remaining work here is in #906.
**D**: A lot of this is already available today.

Given all of this, I think the actionable piece of work here is adding the icon "collection.svg" here in GeoBlacklight.

Here is also a fixture we can use:

```json
{
  "dc_identifier_s": "http://purl.stanford.edu/bq589tv8583",
  "dc_title_s": "Metropolitan Transportation Commission GIS Maps & Data",
  "dc_description_s": "by Bay Area Metropolitan Transportation Commission These are geospatial data layers acquired from the Bay Area Metropolitan Transportation Commission (MTC) spatial data library. Layers contain feature data related to transportation, administrative boundaries, demographics, environmental factors, census activities, and regional projects. New data layers are added on an ongoing basis.",
  "dc_rights_s": "Public",
  "layer_modified_dt": "2020-03-21T21:39:02Z",
  "dct_issued_s": "c2010",
  "layer_geom_type_s": "Collection",
  "dc_language_s": "English",
  "dc_subject_sm": [
    "Transportation",
    "Boundaries",
    "Census"
  ],
  "dct_spatial_sm": [
    "San Francisco Bay Area",
    "California"
  ],
  "dc_publisher_s": "California. Metropolitan Transportation Commission",
  "dc_creator_sm": [
    "California Metropolitan Transportation Commission"
  ],
  "layer_availability_score_f": 1,
  "geoblacklight_version": "1.0",
  "dct_references_s": "{\"http://schema.org/url\":\"https://purl.stanford.edu/bq589tv8583\",\"http://www.loc.gov/mods/v3\":\"https://purl.stanford.edu/bq589tv8583.mods\"}",
  "solr_geom": "ENVELOPE(-123.10749999999999, -122.32777777777777, 37.92972222222222, 37.69333333333333)",
  "layer_slug_s": "stanford-bq589tv8583",
  "dct_provenance_s": "Stanford",
  "stanford_rights_metadata_s": "<rightsMetadata>\n    <access type=\"discover\">\n      <machine>\n        <world/>\n      </machine>\n    </access>\n    <access type=\"read\">\n      <machine>\n        <world/>\n      </machine>\n    </access>\n    <use>\n      <human type=\"useAndReproduction\">This item is in the public domain.  There are no restrictions on use.</human>\n      <human type=\"creativeCommons\"/>\n      <machine type=\"creativeCommons\"/>\n    </use>\n    <copyright>\n      <human>This work is in the Public Domain, meaning that it is not subject to copyright.</human>\n    </copyright>\n  </rightsMetadata>",
  "solr_year_i": 2010,
}
```
