### ISSUE TITLE
Customize data relations box for collection item

### ISSUE THREAD

**Issue by ggeisler** [geoblacklight/geoblacklight#909]
Related to #908 and #906. This is only relevant if we can add collection show pages as described in #908.

When a user visits the show page of an item that is part of an indexed collection (might not be the more accurate term, but I mean a collection that can be see on its own show page as described in #908), the Data Relations widget in the sidebar should help the user see which collection it is part of and enable the user to go to that collection page.

<img width="478" alt="Screen Shot 2020-06-23 at 4 39 11 PM" src="https://user-images.githubusercontent.com/101482/85478291-cee06b00-b570-11ea-9dcc-16bebc1a30e5.png">

- **A**: Ideally, we use a collection item specific label for the Data Relations box of "Item belongs to a collection".

- **B**: Show the parent collection title, linked to its collection show page. The icon should be the same one we use in the collection show page title. 

- **C**: A message that indicates the total number of items in the collection: "49 items in this collection". Not linked, since we already link to the collection above. 

(Alternatively, we could link that message to the search results page that would list all of the collection items? That could be useful, I'm just worried about having the two different collection-related links in such close proximity, and the user can --with one extra click--get to that results page by following the collection link and using the "Show all 49 items" link in its data relations box.)

**Comment by jkeck** [comment]
@ggeisler how should this behave if an item is in multiple collections?  Multiple boxes or should all the collections be listed w/i the same "Item belongs in a collection" box?

e.g. nyu_2451_34502

<img width="289" alt="Screen Shot 2020-06-26 at 1 36 18 PM" src="https://user-images.githubusercontent.com/96776/85898923-08ec7f80-b7b2-11ea-9e82-b0492e02f5a5.png">

**Comment by ggeisler** [comment]
@jkeck I think we should stick to a single box, and list each collection separately within that box.

I didn't consider the possibility of that case in the layout of the box elements (title and item count message) but I'd say we just stick with the layout I have above and when I can work with an example with multiple collections in the box I can look at whether the layout/styling needs adjusting.

**Comment by karenmajewicz** [comment]
This is not an issue for version 4 going forward.
