### ISSUE TITLE
Wrap "Data Relations" heading in an H2

### ISSUE THREAD

**Issue by ggeisler** [geoblacklight/geoblacklight#927]
In the item show page sidebar the Tools, Downloads, and Export Formats boxes have `.card-header`s where the box label is wrapped in an `H2`. The Data Relations box, however, doesn't wrap its `.card-header` label in a heading.

<img width="287" alt="Screen Shot 2020-07-08 at 2 26 42 PM" src="https://user-images.githubusercontent.com/101482/86972792-56f57180-c128-11ea-8001-203aca9e7ef3.png">

For a consistent visual and screenreader experience, I think the Data Relations box should also wrap its `.card-header` label in an `H2`.

I know work on this component is spread in several tickets, some of which aren't completed, so perhaps this is a known thing, but I wanted to note it in case it isn't.

**Comment by mejackreed** [comment]
This will be resolved in https://github.com/geoblacklight/geoblacklight/pull/913/files#diff-e6af1312ad329abfbe94a8fb2c2b7fd9R5

**Comment by mejackreed** [comment]
Resolved in #913
