### ISSUE TITLE
Update <title> labels for Data relations icons

### ISSUE THREAD

**Issue by ggeisler** [geoblacklight/geoblacklight#935]
#910 enables using the format type icon for items shown in the Data relations box, rather than the previous leaf and branch icons. However, an implementer has the option of using the leaf and branch icons instead of the format type icon. But the current SVG `<title>` labels for the leaf and branch icons are not very informative to the user:

<img width="536" alt="Screen Shot 2020-07-14 at 10 53 37 AM" src="https://user-images.githubusercontent.com/101482/87459545-5c3b3c00-c5c0-11ea-95d5-9ddda5432e54.png">

I suggest updating the title labels for these two SVGs:

- `leaf` becomes `Child item`
- `pagelines-brands` becomes `Parent item`

(Alternatively, we could use `Child record` and `Parent record` to be more consistent with the within-card labels that use the term `record` but I personally feel that "record" is a term more appropriate for librarians than non-librarian end-users.)

Those labels work better for collection-type relationships than they do for derived-type of relationships, but they are at least an improvement on the current labels, which are just the source names of the icons and not informative to the user.

**Comment by andrewbattista** [comment]
Agree on fixing the SVG <title> icons. As for the language of parent and child, we could continue to roll with that until we are ready / able to map out a widget that responds to more complex relationship types, as gestured at in #888 and #547

**Comment by hackartisan** [comment]
Blacklight allows you to add additional context to an icon name, but not replace its label / title entirely. see https://github.com/projectblacklight/blacklight/blob/31a3990ccf9e389a0962876b09b6ff31f5e3fd77/app/models/blacklight/icon.rb

The easiest way to do this is to make copies of those svgs and give them the new names, then use those names in configuration.
