### ISSUE TITLE
Map view sometimes changes when paginating

### ISSUE THREAD

**Issue by gravesm** [geoblacklight/geoblacklight#94]
Calling `L.fitBounds()` on an extent does not necessarily result in the same map view. This was the reason zoom/center were being tracked (4f2c93831bfd3eac1eaa376f78e450d29805c412). It was a bigger problem when turbolinks was used, but it looks like it's still a problem with history.js. The results set is still the same since it's being generated from the bbox param which remains the same from one page to the next. It's not a huge problem, but does create an unexpected behavior sometimes when the map view changes while paginating. Do we want to start tracking zoom/center again? If so, where?

Compare page 1 and 2:

![page1](https://cloud.githubusercontent.com/assets/1382348/4955574/557d4e38-6696-11e4-9de7-670088b40a7a.png)

![page2](https://cloud.githubusercontent.com/assets/1382348/4955578/5c723c26-6696-11e4-9019-2e54066f32ea.png)

**Comment by mejackreed** [comment]
Not relevant anymore (I believe) as the map view zooms to bounding box of current page results
