### ISSUE TITLE
Change the name of the default branch

### ISSUE THREAD

**Issue by karenmajewicz** [geoblacklight/geoblacklight#940]
There is a growing consensus for projects to change the default branch of their code in GitHub from "master" to "main."

## Related Links:
- https://sfconservancy.org/news/2020/jun/23/gitbranchname/
- https://github.com/github/renaming
- https://wiki.lyrasis.org/display/samvera/Samvera+Branch+Renaming+WG+Charter
-----

**Comment by eliotjordan** [comment]
Fully in support of this. Should be easy to do.

**Comment by karenmajewicz** [comment]
Send email & Slack asking for feedback

**Comment by karenmajewicz** [comment]
[I made a draft of a feedback form here.](https://docs.google.com/forms/d/e/1FAIpQLSd1mXCLsm1PcwHQ4dENFQRb-INiW8UAVsgftXn6Pxaohc2FhQ/viewform) Any other information or questions we should add?

**Comment by karenmajewicz** [comment]
The only questions I came up with for feedback thus far are:

1. What should the primary branch in GeoBlacklight be called in the future?
Main
Default
Primary
Other:

2. Please add your comments and feedback about this proposed change

----
I wanted to keep it simple, but there might be more info we would like to know about.

**Comment by karenmajewicz** [comment]
Here are the anonymous responses to the community survey:

Would your organization encounter any technical challenges to changing the name of this branch? | What should the primary branch in GeoBlacklight be called in the future? | Please add any other comments and feedback about this proposed change.
-- | -- | --
no | Main | GitHub has stated that "main" is the most popular replacement across GitHub repos, and will also be the default for new repos.
No, not to my knowledge | Main | I second K's assessment
No | Main | I really support this change as part of becoming a more inclusive, equitable community. Hope that we make it soon.
Not at this point, still in initial stages. | Main | I think it makes sense to follow what most others in the development community are shifting towards.
Unlikely | Main | Using "Main" will match the new standard, so good!
Not that I am aware of | Main | I'm very glad the community is proposing this change. Thank you for sharing the links to read more about the movement!

**Comment by eliotjordan** [comment]
This might be helpful. We're renaming the default branch to `main` on Monday: https://github.com/pulibrary/figgy/issues/4167

**Comment by karenmajewicz** [comment]
Places in our repo that include the word master: https://github.com/geoblacklight/geoblacklight/search?p=1&q=master&unscoped_q=master

**Comment by karenmajewicz** [comment]
The default branch has now been changed to Main.
