### ISSUE TITLE
Replace default Blacklight Favicon with GeoBlacklight Favicon

### ISSUE THREAD

**Issue by andrewbattista** [geoblacklight/geoblacklight#948]
### Descriptive summary

This issue suggests that we should add the newly created GeoBlacklight favicon as an asset to the project codebase so that adopters will be able to launch a test app that has a GeoBlacklight-branded favicon on the browser tab

### Pathway to do this

- Copy the icon asset from https://github.com/geoblacklight/geoblacklight.github.io/blob/master/images/gbl-favicon.png
- Replace the existing default Blacklight favicon

**Comment by ewlarson** [comment]
Fixed by #1009
