### ISSUE TITLE
Add an svg logo for University of Colorado Boulder

### ISSUE THREAD

**Issue by eliotjordan** [geoblacklight/geoblacklight#980]
https://geo.colorado.edu/

https://github.com/geoblacklight/geoblacklight/tree/main/app/assets/images/blacklight

**Comment by frizatch** [comment]
I am going to coordinate with Phil about having a generic University of Colorado svg.

**Comment by frizatch** [comment]
My PR is premature in that it only addresses getting the svg into the assets. I'm interested in working on how it needs to be *used* and could use a pointers... but I'll look at my cloned repo and hunt for other svg files to start.
