### ISSUE TITLE
Clarify some terms in Metadata Wiki

### ISSUE THREAD

**Issue by lenathelibrarian** [geoblacklight/geoblacklight#982]
### Question about terminology used in GeoBlacklight Metadata Wiki

I was reviewing the wiki and I wanted to point out some elements that are mentioned on [What is GeoBlacklight Metadata?](https://github.com/geoblacklight/geoblacklight/wiki/GeoBlacklight-Metadata) but for which I couldn't find definitions in subsequent pages or in the current notes spreadsheet of terms for 2.0.

- [ ] _Layer Identifier for external services (layer_id_s)_

- [ ] _Originating Layer data (dc_source_sm)_

Additionally, I think it would be helpful to go through and make sure _External References_ is consistent. It's _External References_ on that landing page and [on its own page where the reference URIs are listed](https://github.com/geoblacklight/geoblacklight/wiki/External-references), but otherwise it's just _References_ everywhere else, as far as I can tell. To a newbie, this could be confusing.

- [ ] _External References_ versus _References_

Thanks!

**Comment by karenmajewicz** [comment]
Thank you @lenathelibrarian! I will review these.

**Comment by ewlarson** [comment]
All has been addressed or discussed.
