### ISSUE TITLE
geographic relevance ranking sort not default from home screen

### ISSUE THREAD

**Issue by smpowell** [geoblacklight/geoblacklight#985]
### Descriptive summary
The first results screen reached from the home screen by clicking on any of the facets lists the results in alphabetical order not by geographic relevance.

### Expected behavior
I would expect the results to be consistently listed by default with geographical relevance.

### Actual behavior
Even if the map is manipulated on the home screen, the first results page defaults to alphabetical order. Alphabetical continues to be default until the map screen on the results page is interacted with.

### Steps to reproduce the behavior

1. Go to a Geoblacklight instance home page, eg https://geodata.lib.berkeley.edu
2. Zoom in on the map
3. Click on any of the facets under "Find by..."
4. Note that the results are listed in alphabetical order even though the sort by drop down lists relevance.

**Comment by eliotjordan** [comment]
@smpowell Would you be willing to discuss this at a future community meeting?

**Comment by ewlarson** [comment]
Closing. Adding issue to map UX discussion.
