### ISSUE TITLE
Some helper methods are not overrideable when using zeitwerk loader in Rails 6.0, 6.1

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight#996]
### Descriptive summary

When using the zeitwerk loader in Rails 6.0,6.1 some helper methods, `Geoblacklight::ViewHelperOverride` are not overrideable.

### Expected behavior
These should be able to be extended for custom functionality.

Likely do to how we initialize things here: https://github.com/geoblacklight/geoblacklight/blob/main/lib/geoblacklight.rb#L38-L46

Not present in the classic loader and users who never override these methods will not see these problems.

**Comment by andrewbattista** [comment]
Adding in some ancillary comments

- This could become a part of the need to create a roadmap for the entire application. In other words, we need to document the general plans for keeping compatible with the Ruby on Rails web framework support

**Comment by eliotjordan** [comment]
This can possibly be closed when this work is finished and merged:
https://github.com/geoblacklight/geoblacklight/commit/ac5e088d72fd9b08c360aee6eadd5b6caddefffb

Additional documentation might be useful.
