### ISSUE TITLE
Convert existing fixture documents to new schema

### ISSUE THREAD

**Issue by Ziiiiing** [geoblacklight/geoblacklight#999]
Transform the metadata schema of existing fixture documents from GBL version 1.0 to Aardvark version.

**Comment by ewlarson** [comment]
@Ziiiiing / Groundbreaking work here:
https://github.com/BTAA-Geospatial-Data-Project/GBL-Schema-Update

**Comment by karenmajewicz** [comment]
Initial set of fixtures was created and tested for version 3.3. These helped remove hard coded fields in GeoBlacklight. Closing this issue as next steps will involve creating new and updated fixtures with final version of Aardvark, TBD.
